<?php

namespace Database\Seeders;

use App\Models\ConsentType;
use Illuminate\Database\Seeder;

class ConsentTypesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $consentTypes = [
            [
                'name' => 'General Care and Support',
                'category' => 'care',
                'description' => 'Consent to receive general care and support services, including personal care, medication management, and daily living assistance.',
                'purpose' => 'To provide comprehensive care and support services as outlined in the support plan.',
                'legal_basis' => 'consent',
                'is_mandatory' => true,
                'requires_capacity_assessment' => true,
                'allows_withdrawal' => true,
                'withdrawal_notice_days' => 14,
                'validity_period_days' => 365,
                'renewal_required' => true,
                'renewal_reminder_days' => 30,
                'version' => 1,
                'active' => true,
            ],
            [
                'name' => 'Medical Treatment and Interventions',
                'category' => 'medical',
                'description' => 'Consent for medical treatments, interventions, and procedures including medication administration, wound care, and health monitoring.',
                'purpose' => 'To provide medical care and treatment as prescribed by healthcare professionals.',
                'legal_basis' => 'consent',
                'is_mandatory' => true,
                'requires_capacity_assessment' => true,
                'allows_withdrawal' => true,
                'withdrawal_notice_days' => 0,
                'validity_period_days' => 180,
                'renewal_required' => true,
                'renewal_reminder_days' => 30,
                'version' => 1,
                'active' => true,
            ],
            [
                'name' => 'Photograph and Video Recording',
                'category' => 'communication',
                'description' => 'Consent to take photographs and videos for care planning, activities, and promotional purposes.',
                'purpose' => 'To document activities, celebrate achievements, and promote our services (where appropriate).',
                'legal_basis' => 'consent',
                'is_mandatory' => false,
                'requires_capacity_assessment' => true,
                'allows_withdrawal' => true,
                'withdrawal_notice_days' => 0,
                'validity_period_days' => 365,
                'renewal_required' => true,
                'renewal_reminder_days' => 60,
                'version' => 1,
                'active' => true,
            ],
            [
                'name' => 'Information Sharing with Family',
                'category' => 'communication',
                'description' => 'Consent to share personal information and care updates with designated family members or representatives.',
                'purpose' => 'To keep family members informed about care, wellbeing, and any significant events.',
                'legal_basis' => 'consent',
                'is_mandatory' => false,
                'requires_capacity_assessment' => true,
                'allows_withdrawal' => true,
                'withdrawal_notice_days' => 7,
                'validity_period_days' => 365,
                'renewal_required' => true,
                'renewal_reminder_days' => 30,
                'version' => 1,
                'active' => true,
            ],
            [
                'name' => 'Information Sharing with Healthcare Providers',
                'category' => 'communication',
                'description' => 'Consent to share relevant health and care information with GPs, hospitals, and other healthcare professionals.',
                'purpose' => 'To ensure continuity of care and appropriate medical treatment.',
                'legal_basis' => 'consent',
                'is_mandatory' => true,
                'requires_capacity_assessment' => true,
                'allows_withdrawal' => true,
                'withdrawal_notice_days' => 7,
                'validity_period_days' => 365,
                'renewal_required' => true,
                'renewal_reminder_days' => 30,
                'version' => 1,
                'active' => true,
            ],
            [
                'name' => 'Emergency Contact and Treatment',
                'category' => 'medical',
                'description' => 'Consent for emergency medical treatment and to contact designated emergency contacts in urgent situations.',
                'purpose' => 'To enable rapid response to medical emergencies and ensure appropriate care.',
                'legal_basis' => 'vital_interests',
                'is_mandatory' => true,
                'requires_capacity_assessment' => true,
                'allows_withdrawal' => false,
                'validity_period_days' => 365,
                'renewal_required' => true,
                'renewal_reminder_days' => 60,
                'version' => 1,
                'active' => true,
            ],
            [
                'name' => 'Participation in Activities and Outings',
                'category' => 'activities',
                'description' => 'Consent to participate in organized activities, social events, and community outings.',
                'purpose' => 'To support social inclusion, community participation, and enjoyment of activities.',
                'legal_basis' => 'consent',
                'is_mandatory' => false,
                'requires_capacity_assessment' => false,
                'allows_withdrawal' => true,
                'withdrawal_notice_days' => 0,
                'validity_period_days' => 365,
                'renewal_required' => true,
                'renewal_reminder_days' => 60,
                'version' => 1,
                'active' => true,
            ],
            [
                'name' => 'Data Processing (GDPR)',
                'category' => 'data_protection',
                'description' => 'Consent to process personal data in accordance with GDPR regulations for care delivery and service improvement.',
                'purpose' => 'To lawfully process personal data for care provision, safety monitoring, and regulatory compliance.',
                'legal_basis' => 'consent',
                'is_mandatory' => true,
                'requires_capacity_assessment' => true,
                'allows_withdrawal' => true,
                'withdrawal_notice_days' => 14,
                'validity_period_days' => null,
                'renewal_required' => false,
                'version' => 1,
                'active' => true,
            ],
            [
                'name' => 'Restrictive Practices (if applicable)',
                'category' => 'safeguarding',
                'description' => 'Consent for any restrictive practices that may be necessary for safety, as documented in Positive Behaviour Support plans.',
                'purpose' => 'To ensure restrictive practices are only used with proper consent and oversight.',
                'legal_basis' => 'vital_interests',
                'is_mandatory' => false,
                'requires_capacity_assessment' => true,
                'allows_withdrawal' => true,
                'withdrawal_notice_days' => 7,
                'validity_period_days' => 90,
                'renewal_required' => true,
                'renewal_reminder_days' => 14,
                'version' => 1,
                'active' => true,
            ],
            [
                'name' => 'Research and Service Improvement',
                'category' => 'data_protection',
                'description' => 'Consent to use anonymized data for research, service improvement, and quality audits.',
                'purpose' => 'To improve service quality through analysis of outcomes and best practices.',
                'legal_basis' => 'consent',
                'is_mandatory' => false,
                'requires_capacity_assessment' => false,
                'allows_withdrawal' => true,
                'withdrawal_notice_days' => 14,
                'validity_period_days' => null,
                'renewal_required' => false,
                'version' => 1,
                'active' => true,
            ],
        ];

        foreach ($consentTypes as $type) {
            ConsentType::create($type);
        }

        $this->command->info('Consent types seeded successfully.');
    }
}
