<?php

namespace Database\Seeders;

use App\Models\TrainingCourse;
use Illuminate\Database\Seeder;

class TrainingCoursesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $courses = [
            [
                'name' => 'Safeguarding Adults',
                'code' => 'SG-ADULT-001',
                'category' => 'Safeguarding',
                'description' => 'Comprehensive training on safeguarding adults at risk, recognizing abuse, and responding appropriately to concerns.',
                'learning_outcomes' => json_encode([
                    'Understand different types of abuse and neglect',
                    'Recognize signs and indicators of abuse',
                    'Know how to respond to safeguarding concerns',
                    'Understand the legal framework and local procedures',
                    'Apply Making Safeguarding Personal principles',
                ]),
                'duration_minutes' => 180,
                'requires_renewal' => true,
                'validity_period_months' => 12,
                'renewal_reminder_months' => 1,
                'mandatory_for_all' => true,
                'requires_assessment' => true,
                'pass_mark_percentage' => 80,
                'delivery_method' => 'blended',
                'active' => true,
            ],
            [
                'name' => 'Mental Capacity Act 2005',
                'code' => 'MCA-001',
                'category' => 'Legislation',
                'description' => 'Understanding the Mental Capacity Act, capacity assessments, best interests decisions, and Deprivation of Liberty Safeguards.',
                'learning_outcomes' => json_encode([
                    'Understand the five statutory principles',
                    'Conduct functional capacity assessments',
                    'Make best interests decisions',
                    'Understand DoLS and Liberty Protection Safeguards',
                    'Apply the Act in daily practice',
                ]),
                'duration_minutes' => 240,
                'requires_renewal' => true,
                'validity_period_months' => 12,
                'renewal_reminder_months' => 1,
                'mandatory_for_all' => true,
                'requires_assessment' => true,
                'pass_mark_percentage' => 80,
                'delivery_method' => 'classroom',
                'active' => true,
            ],
            [
                'name' => 'Medication Administration',
                'code' => 'MED-ADMIN-001',
                'category' => 'Clinical Skills',
                'description' => 'Safe medication administration, storage, recording, and management of errors. Includes practical competency assessment.',
                'learning_outcomes' => json_encode([
                    'Understand medication legislation and policies',
                    'Safely administer medications via different routes',
                    'Complete accurate medication records',
                    'Recognize and respond to medication errors',
                    'Manage controlled drugs appropriately',
                ]),
                'duration_minutes' => 360,
                'requires_renewal' => true,
                'validity_period_months' => 12,
                'renewal_reminder_months' => 1,
                'mandatory_for_roles' => json_encode(['support_worker', 'senior_support_worker', 'team_leader']),
                'prerequisites' => json_encode(['Basic Care Certificate']),
                'requires_assessment' => true,
                'pass_mark_percentage' => 85,
                'delivery_method' => 'practical',
                'active' => true,
            ],
            [
                'name' => 'Moving and Handling',
                'code' => 'MH-001',
                'category' => 'Health and Safety',
                'description' => 'Safe moving and handling techniques, risk assessment, and use of equipment to prevent injury to staff and service users.',
                'learning_outcomes' => json_encode([
                    'Understand legislation and responsibilities',
                    'Conduct moving and handling risk assessments',
                    'Apply safe handling techniques',
                    'Use equipment safely and effectively',
                    'Recognize and manage risks',
                ]),
                'duration_minutes' => 180,
                'requires_renewal' => true,
                'validity_period_months' => 12,
                'renewal_reminder_months' => 1,
                'mandatory_for_all' => true,
                'requires_assessment' => true,
                'pass_mark_percentage' => 75,
                'delivery_method' => 'practical',
                'active' => true,
            ],
            [
                'name' => 'First Aid at Work',
                'code' => 'FA-001',
                'category' => 'Health and Safety',
                'description' => 'HSE-approved First Aid at Work course covering emergency first aid and CPR.',
                'learning_outcomes' => json_encode([
                    'Assess emergency situations',
                    'Perform CPR and use AED',
                    'Manage unconscious casualties',
                    'Treat wounds, fractures, and burns',
                    'Recognize and respond to medical emergencies',
                ]),
                'duration_minutes' => 1080,
                'requires_renewal' => true,
                'validity_period_months' => 36,
                'renewal_reminder_months' => 2,
                'mandatory_for_roles' => json_encode(['team_leader', 'senior_support_worker']),
                'requires_assessment' => true,
                'pass_mark_percentage' => 100,
                'provider' => 'St John Ambulance',
                'delivery_method' => 'classroom',
                'active' => true,
            ],
            [
                'name' => 'Positive Behaviour Support',
                'code' => 'PBS-001',
                'category' => 'Behaviour Support',
                'description' => 'Positive Behaviour Support approaches, functional assessment, and person-centered interventions.',
                'learning_outcomes' => json_encode([
                    'Understand PBS principles and values',
                    'Conduct functional behavior assessments',
                    'Develop positive support plans',
                    'Use proactive and reactive strategies',
                    'Monitor and review interventions',
                ]),
                'duration_minutes' => 360,
                'requires_renewal' => true,
                'validity_period_months' => 24,
                'renewal_reminder_months' => 2,
                'mandatory_for_roles' => json_encode(['behaviour_specialist', 'team_leader']),
                'requires_assessment' => true,
                'pass_mark_percentage' => 80,
                'delivery_method' => 'blended',
                'active' => true,
            ],
            [
                'name' => 'Infection Prevention and Control',
                'code' => 'IPC-001',
                'category' => 'Clinical Skills',
                'description' => 'Infection prevention and control, hand hygiene, PPE use, and outbreak management.',
                'learning_outcomes' => json_encode([
                    'Understand infection transmission',
                    'Apply standard precautions',
                    'Use PPE correctly',
                    'Maintain environmental hygiene',
                    'Respond to outbreaks',
                ]),
                'duration_minutes' => 120,
                'requires_renewal' => true,
                'validity_period_months' => 12,
                'renewal_reminder_months' => 1,
                'mandatory_for_all' => true,
                'requires_assessment' => true,
                'pass_mark_percentage' => 75,
                'delivery_method' => 'elearning',
                'active' => true,
            ],
            [
                'name' => 'Fire Safety',
                'code' => 'FIRE-001',
                'category' => 'Health and Safety',
                'description' => 'Fire safety awareness, prevention, evacuation procedures, and use of fire fighting equipment.',
                'learning_outcomes' => json_encode([
                    'Understand fire risks and prevention',
                    'Recognize fire alarm signals',
                    'Follow evacuation procedures',
                    'Use fire fighting equipment',
                    'Know emergency contact procedures',
                ]),
                'duration_minutes' => 90,
                'requires_renewal' => true,
                'validity_period_months' => 12,
                'renewal_reminder_months' => 1,
                'mandatory_for_all' => true,
                'requires_assessment' => false,
                'delivery_method' => 'elearning',
                'active' => true,
            ],
            [
                'name' => 'GDPR and Information Governance',
                'code' => 'GDPR-001',
                'category' => 'Data Protection',
                'description' => 'GDPR compliance, data protection principles, confidentiality, and secure information handling.',
                'learning_outcomes' => json_encode([
                    'Understand GDPR principles and rights',
                    'Handle personal data securely',
                    'Recognize and report data breaches',
                    'Maintain confidentiality',
                    'Apply information governance policies',
                ]),
                'duration_minutes' => 120,
                'requires_renewal' => true,
                'validity_period_months' => 12,
                'renewal_reminder_months' => 1,
                'mandatory_for_all' => true,
                'requires_assessment' => true,
                'pass_mark_percentage' => 80,
                'delivery_method' => 'elearning',
                'active' => true,
            ],
            [
                'name' => 'Equality, Diversity and Inclusion',
                'code' => 'EDI-001',
                'category' => 'Values and Culture',
                'description' => 'Promoting equality, valuing diversity, challenging discrimination, and creating inclusive environments.',
                'learning_outcomes' => json_encode([
                    'Understand protected characteristics',
                    'Recognize and challenge discrimination',
                    'Promote inclusive practice',
                    'Value diversity',
                    'Apply equality legislation',
                ]),
                'duration_minutes' => 120,
                'requires_renewal' => true,
                'validity_period_months' => 24,
                'renewal_reminder_months' => 2,
                'mandatory_for_all' => true,
                'requires_assessment' => true,
                'pass_mark_percentage' => 75,
                'delivery_method' => 'elearning',
                'active' => true,
            ],
            [
                'name' => 'Person-Centred Care',
                'code' => 'PCC-001',
                'category' => 'Care Practice',
                'description' => 'Person-centred approaches, active participation, dignity in care, and outcome-focused support.',
                'learning_outcomes' => json_encode([
                    'Apply person-centred values',
                    'Support active participation',
                    'Promote dignity and respect',
                    'Plan outcome-focused support',
                    'Empower choice and control',
                ]),
                'duration_minutes' => 180,
                'requires_renewal' => true,
                'validity_period_months' => 24,
                'renewal_reminder_months' => 2,
                'mandatory_for_all' => true,
                'requires_assessment' => true,
                'pass_mark_percentage' => 75,
                'delivery_method' => 'blended',
                'active' => true,
            ],
            [
                'name' => 'Care Certificate',
                'code' => 'CARE-CERT',
                'category' => 'Induction',
                'description' => 'Nationally recognized Care Certificate covering 15 standards for new care workers.',
                'learning_outcomes' => json_encode([
                    'Complete all 15 Care Certificate standards',
                    'Demonstrate competence in fundamental care skills',
                    'Understand duty of care and safeguarding',
                    'Communicate effectively',
                    'Work in a person-centred way',
                ]),
                'duration_minutes' => 4800,
                'requires_renewal' => false,
                'mandatory_for_roles' => json_encode(['support_worker']),
                'requires_assessment' => true,
                'pass_mark_percentage' => 100,
                'delivery_method' => 'blended',
                'active' => true,
            ],
        ];

        foreach ($courses as $course) {
            TrainingCourse::updateOrCreate(
                ['code' => $course['code']],
                $course
            );
        }

        $this->command?->info('Training courses seeded successfully.');
    }
}
