<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: Arial, sans-serif; font-size: 10px; }
        h1 { font-size: 16px; margin-bottom: 5px; }
        .header { border-bottom: 2px solid #333; padding-bottom: 10px; margin-bottom: 15px; }
        .client-info { width: 100%; }
        .client-info td { vertical-align: top; padding: 0; }
        .client-info .left { width: 50%; }
        .client-info .right { width: 50%; text-align: right; }
        table.cd-table { width: 100%; border-collapse: collapse; margin-bottom: 15px; }
        table.cd-table th, table.cd-table td { border: 1px solid #999; padding: 4px 6px; text-align: left; }
        table.cd-table th { background: #f3f4f6; font-weight: bold; }
        .type-receipt { color: #16a34a; }
        .type-administration { color: #2563eb; }
        .type-destruction { color: #dc2626; }
        .type-return { color: #d97706; }
        .footer { text-align: center; font-size: 8px; color: #666; margin-top: 20px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Controlled Drug Register</h1>
        <table class="client-info" cellpadding="0" cellspacing="0">
            <tr>
                <td class="left">
                    <strong>Client:</strong> {{ $client->last_name }}, {{ $client->first_name }}<br>
                    <strong>NHI:</strong> {{ $client->nhi_number ?? 'N/A' }}<br>
                    <strong>DOB:</strong> {{ $client->date_of_birth ? date('d/m/Y', strtotime($client->date_of_birth)) : 'N/A' }}
                </td>
                <td class="right">
                    <strong>Period:</strong> {{ date('d/m/Y', strtotime($dateFrom)) }} - {{ date('d/m/Y', strtotime($dateTo)) }}<br>
                    <strong>Generated:</strong> {{ now()->format('d/m/Y H:i') }}<br>
                    <strong>Generated By:</strong> {{ auth()->user()->name }}
                </td>
            </tr>
        </table>
    </div>

    <table class="cd-table">
        <thead>
            <tr>
                <th>Date / Time</th>
                <th>Medication</th>
                <th>Type</th>
                <th>Qty</th>
                <th>Balance Before</th>
                <th>Balance After</th>
                <th>Reason / Notes</th>
                <th>Recorded By</th>
                <th>Witnessed By</th>
            </tr>
        </thead>
        <tbody>
            @foreach($entries as $entry)
            <tr>
                <td>{{ $entry->recorded_at->format('d/m/Y H:i') }}</td>
                <td>{{ $entry->medication->name ?? '—' }}</td>
                <td>
                    <span class="type-{{ $entry->entry_type }}">
                        {{ ucfirst(str_replace('_', ' ', $entry->entry_type)) }}
                    </span>
                </td>
                <td>{{ $entry->quantity }} {{ $entry->unit }}</td>
                <td>{{ $entry->on_hand_before }}</td>
                <td>{{ $entry->on_hand_after }}</td>
                <td>{{ $entry->reason ?? '' }} {{ $entry->notes ? "— {$entry->notes}" : '' }}</td>
                <td>{{ $entry->recordedBy->name ?? '—' }}</td>
                <td>{{ $entry->witnessedBy->name ?? '—' }}</td>
            </tr>
            @endforeach
            @if($entries->isEmpty())
            <tr>
                <td colspan="9" style="text-align: center; padding: 10px; color: #999;">No controlled drug entries for this period.</td>
            </tr>
            @endif
        </tbody>
    </table>

    <div class="footer">
        Generated by Oblivion Findings eMAR System | {{ now()->format('d/m/Y H:i:s') }}
    </div>
</body>
</html>
