<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: Arial, sans-serif; font-size: 10px; }
        h1 { font-size: 16px; margin-bottom: 5px; }
        h2 { font-size: 13px; margin-top: 15px; margin-bottom: 8px; }
        .header { border-bottom: 2px solid #333; padding-bottom: 10px; margin-bottom: 15px; }
        .client-info { width: 100%; }
        .client-info td { vertical-align: top; padding: 0; }
        .client-info .left { width: 50%; }
        .client-info .right { width: 50%; text-align: right; }
        .allergy-banner { background: #fee2e2; padding: 5px 10px; border: 1px solid #dc2626; margin-bottom: 10px; }
        table.med-table { width: 100%; border-collapse: collapse; margin-bottom: 15px; }
        table.med-table th, table.med-table td { border: 1px solid #999; padding: 4px 6px; text-align: left; }
        table.med-table th { background: #f3f4f6; font-weight: bold; }
        .status-given { color: #16a34a; font-weight: bold; }
        .status-refused { color: #ea580c; font-weight: bold; }
        .status-withheld { color: #d97706; font-weight: bold; }
        .status-missed { color: #dc2626; font-weight: bold; }
        .footer { text-align: center; font-size: 8px; color: #666; margin-top: 20px; }
        .legend { margin-top: 10px; font-size: 9px; }
        .legend span { margin-right: 15px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Medication Administration Record (MAR)</h1>
        <table class="client-info" cellpadding="0" cellspacing="0">
            <tr>
                <td class="left">
                    <strong>Client:</strong> {{ $client->last_name }}, {{ $client->first_name }}<br>
                    <strong>NHI:</strong> {{ $client->nhi_number ?? 'N/A' }}<br>
                    <strong>DOB:</strong> {{ $client->date_of_birth ? date('d/m/Y', strtotime($client->date_of_birth)) : 'N/A' }}
                </td>
                <td class="right">
                    <strong>Period:</strong> {{ date('d/m/Y', strtotime($dateFrom)) }} - {{ date('d/m/Y', strtotime($dateTo)) }}<br>
                    <strong>Generated:</strong> {{ now()->format('d/m/Y H:i') }}<br>
                    <strong>Generated By:</strong> {{ auth()->user()->name }}
                </td>
            </tr>
        </table>
    </div>

    @if($allergies->isNotEmpty())
    <div class="allergy-banner">
        <strong>ALLERGIES:</strong>
        @foreach($allergies as $allergy)
            {{ $allergy->allergen }} ({{ $allergy->severity }})@if(!$loop->last), @endif
        @endforeach
    </div>
    @endif

    <h2>Scheduled Medications</h2>
    <table class="med-table">
        <thead>
            <tr>
                <th>Medication</th>
                <th>Dose</th>
                <th>Route</th>
                <th>Frequency</th>
                @foreach($dates as $date)
                <th style="text-align: center; min-width: 30px;">{{ date('d/m', strtotime($date)) }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @foreach($scheduledMedications as $med)
            <tr>
                <td>{{ $med->name }}</td>
                <td>{{ $med->dosage }}</td>
                <td>{{ $med->route ?? '—' }}</td>
                <td>{{ $med->frequency }}</td>
                @foreach($dates as $date)
                <td style="text-align: center;">
                    @php
                        $admins = $med->administrations->filter(function ($a) use ($date) {
                            return $a->scheduled_for && $a->scheduled_for->toDateString() === $date;
                        });
                    @endphp
                    @foreach($admins as $admin)
                        <span class="status-{{ $admin->status }}">{{ strtoupper(substr($admin->status, 0, 1)) }}</span>
                    @endforeach
                </td>
                @endforeach
            </tr>
            @endforeach
            @if($scheduledMedications->isEmpty())
            <tr>
                <td colspan="{{ 4 + count($dates) }}" style="text-align: center; padding: 10px; color: #999;">No scheduled medications.</td>
            </tr>
            @endif
        </tbody>
    </table>

    @if($prnMedications->isNotEmpty())
    <h2>PRN / As-Needed Medications</h2>
    <table class="med-table">
        <thead>
            <tr>
                <th>Medication</th>
                <th>Dose</th>
                <th>Route</th>
                <th>Indication</th>
                <th>Max/Day</th>
                @foreach($dates as $date)
                <th style="text-align: center; min-width: 30px;">{{ date('d/m', strtotime($date)) }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @foreach($prnMedications as $med)
            <tr>
                <td>{{ $med->name }}@if($med->controlled_drug) <strong>[CD]</strong>@endif</td>
                <td>{{ $med->dosage }}</td>
                <td>{{ $med->route ?? '—' }}</td>
                <td>{{ $med->prn_reason ?? '—' }}</td>
                <td>{{ $med->max_per_day ?? '—' }}</td>
                @foreach($dates as $date)
                <td style="text-align: center;">
                    @php
                        $admins = $med->administrations->filter(function ($a) use ($date) {
                            return $a->administered_at && $a->administered_at->toDateString() === $date;
                        });
                    @endphp
                    @if($admins->count() > 0)
                        <span class="status-given">{{ $admins->count() }}</span>
                    @endif
                </td>
                @endforeach
            </tr>
            @endforeach
        </tbody>
    </table>
    @endif

    <div class="legend">
        <strong>Key:</strong>
        <span class="status-given">G = Given</span>
        <span class="status-refused">R = Refused</span>
        <span class="status-withheld">W = Withheld</span>
        <span class="status-missed">M = Missed</span>
    </div>

    <div class="footer">
        Generated by Oblivion Findings eMAR System | {{ now()->format('d/m/Y H:i:s') }}
    </div>
</body>
</html>
