<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: Arial, sans-serif; font-size: 10px; }
        h1 { font-size: 16px; margin-bottom: 5px; }
        h2 { font-size: 13px; margin-top: 15px; margin-bottom: 8px; border-bottom: 1px solid #ccc; padding-bottom: 4px; }
        .header { border-bottom: 2px solid #333; padding-bottom: 10px; margin-bottom: 15px; }
        .header-info { font-size: 11px; }
        table.round-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        table.round-table th, table.round-table td { border: 1px solid #999; padding: 5px 6px; text-align: left; }
        table.round-table th { background: #f3f4f6; font-weight: bold; }
        .round-meta { margin-bottom: 5px; font-size: 10px; color: #555; }
        .checkbox { width: 18px; height: 18px; border: 2px solid #333; display: inline-block; }
        .tick-col { text-align: center; width: 40px; }
        .footer { text-align: center; font-size: 8px; color: #666; margin-top: 20px; }
        .signature-line { margin-top: 30px; border-top: 1px solid #333; width: 200px; display: inline-block; }
        .signatures { margin-top: 40px; }
        .signatures td { border: none; padding: 10px 20px 0 0; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Medication Round Sheet</h1>
        <div class="header-info">
            <strong>Date:</strong> {{ date('d/m/Y', strtotime($date)) }} |
            <strong>Generated:</strong> {{ now()->format('d/m/Y H:i') }} |
            <strong>Generated By:</strong> {{ auth()->user()->name }}
        </div>
    </div>

    @forelse($rounds as $round)
        <h2>{{ $round->name }} &mdash; {{ $round->scheduled_time }}</h2>
        <div class="round-meta">
            <strong>Assigned To:</strong> {{ $round->assignedTo->name ?? 'Unassigned' }} |
            <strong>Status:</strong> {{ ucfirst($round->status) }} |
            <strong>Window:</strong> {{ $round->window_minutes }} minutes
        </div>

        <table class="round-table">
            <thead>
                <tr>
                    <th>Client</th>
                    <th>Medication</th>
                    <th>Dose</th>
                    <th>Route</th>
                    <th class="tick-col">Given</th>
                    <th class="tick-col">Refused</th>
                    <th class="tick-col">Withheld</th>
                    <th>Notes</th>
                </tr>
            </thead>
            <tbody>
                @forelse($round->administrations as $admin)
                <tr>
                    <td>{{ $admin->client->last_name ?? '' }}, {{ $admin->client->first_name ?? '' }}</td>
                    <td>{{ $admin->medication->name ?? '—' }}</td>
                    <td>{{ $admin->medication->dosage ?? '—' }}</td>
                    <td>{{ $admin->medication->route ?? '—' }}</td>
                    <td class="tick-col"><div class="checkbox"></div></td>
                    <td class="tick-col"><div class="checkbox"></div></td>
                    <td class="tick-col"><div class="checkbox"></div></td>
                    <td></td>
                </tr>
                @empty
                <tr>
                    <td colspan="8" style="text-align: center; color: #999;">No medications assigned to this round.</td>
                </tr>
                @endforelse
            </tbody>
        </table>

        <table class="signatures" cellpadding="0" cellspacing="0">
            <tr>
                <td>
                    <strong>Staff Signature:</strong><br>
                    <div class="signature-line">&nbsp;</div>
                </td>
                <td>
                    <strong>Witness Signature:</strong><br>
                    <div class="signature-line">&nbsp;</div>
                </td>
                <td>
                    <strong>Time Completed:</strong><br>
                    <div class="signature-line">&nbsp;</div>
                </td>
            </tr>
        </table>
    @empty
        <p style="text-align: center; color: #999; margin-top: 40px;">No rounds scheduled for this date.</p>
    @endforelse

    <div class="footer">
        Generated by Oblivion Findings eMAR System | {{ now()->format('d/m/Y H:i:s') }}
    </div>
</body>
</html>
