import React, {useState, useEffect} from 'react';
import {ActionOverview} from './action-overview';
import {createRoot} from 'react-dom/client';
import {ItHero} from '@/components/it/it-hero';
import {PageHeaderRail, PageHeaderFilterSelect} from '@/components/page/page-header';
import {EventHorizonWordmark} from '@/components/event-horizon-wordmark';
import {StatusBadge} from '@/components/ui/status-badge';
import {Button} from '@/components/ui/button';
import {Dialog, DialogContent, DialogTitle, DialogDescription} from '@/components/ui/dialog';
import {TooltipProvider} from '@/components/ui/tooltip';
import {EntityKebab, EntityContextMenu} from '@/components/lists/entity-menu';
import {Ticket, LayoutDashboard, Search, Clock, MessageSquareText, Bell, ChevronRight, ChevronDown, ChevronLeft, Plus, ArrowUpRight, ArrowRight, AlertTriangle, UserRound, UsersRound, Inbox, CircleHelp, Check, BookOpen, Server, CalendarDays, ShieldCheck, House, Settings, Activity, Flag, FileText, RefreshCw, Eye, CircleCheck, BriefcaseBusiness, HeartPulse, Layers, Timer, FilterX, ExternalLink} from 'lucide-react';

// A complete synthetic open-ticket set. No live records or outbound requests.
const initialTickets = [
 {id:2048,title:'Medication room printer offline',priority:'urgent',owner:null,requester:'Hana Williams',site:'Aurora House',status:'open',party:'it',first:true,age:0.04,ageLabel:'58m',state:'breached',response:'Breached · 32m overdue',resolution:'Due in 3h 02m',next:'Record the first response',detail:'The medication room printer stopped connecting this morning. The requester has checked power and restarted the printer. Staff are using the approved fallback process.'},
 {id:2039,title:'Shared drive access lost after role change',priority:'high',owner:'Maya Patel',requester:'Tom Harris',site:'Kauri House',status:'in_progress',party:'it',first:false,age:2,ageLabel:'2d',state:'breached',response:'Met',resolution:'Breached · 1h 12m overdue',next:'Review access and update requester',detail:'Tom can sign in but cannot open the shared drive after a role change. A public reply confirmed the device and account details.'},
 {id:2051,title:'Roster workstation cannot sign in',priority:'high',owner:'Alex Morgan',requester:'Grace Martin',site:'Aurora House',status:'open',party:'it',first:true,age:0.03,ageLabel:'42m',state:'at_risk',response:'At risk · due in 18m',resolution:'Due in 7h 18m',next:'Record the first response',detail:'The office workstation is rejecting sign-in. Another approved workstation is available while IT investigates.'},
 {id:2053,title:'Staff Wi-Fi unavailable in east wing',priority:'urgent',owner:null,requester:'Ben Scott',site:'Kauri House',status:'open',party:'it',first:true,age:0.02,ageLabel:'36m',state:'at_risk',response:'At risk · due in 24m',resolution:'Due in 4h 24m',next:'Assign a technician and respond',detail:'Staff Wi-Fi is unavailable in the east wing. Wired office access remains available. Two devices have been checked.'},
 {id:2026,title:'Scanner still disconnecting after replacement',priority:'normal',owner:'Alex Morgan',requester:'Ella Wilson',site:'Harbour House',status:'in_progress',party:'it',first:false,age:8,ageLabel:'8d',state:'at_risk',response:'Met',resolution:'At risk · due in 45m',next:'Review the latest requester reply',detail:'The replacement scanner is still disconnecting. Ella has confirmed that the new cable is connected and has supplied the device identifier.'},
 {id:2046,title:'New label printer needs setup',priority:'normal',owner:null,requester:'Sam Lee',site:'Harbour House',status:'open',party:'unknown',first:true,age:1,ageLabel:'1d',state:'unmeasured',response:'Unmeasured',resolution:'Unmeasured',next:'Assign a technician',detail:'A new label printer is ready for setup. SLA targets and next public reply responsibility are not recorded.'},
 {id:2018,title:'Confirm replacement laptop collection',priority:'normal',owner:'Alex Morgan',requester:'Mia Taylor',site:'Aurora House',status:'waiting',party:'requester',first:false,age:11,ageLabel:'11d',state:'paused',response:'Met',resolution:'Paused · awaiting requester',next:'Waiting for collection confirmation',detail:'IT has prepared the replacement laptop and asked Mia to confirm a collection time. The next public response is with the requester.'},
 {id:2009,title:'Door entry tablet replacement',priority:'low',owner:'Chris Ng',requester:'Noah Thomas',site:'Kauri House',status:'waiting',party:'vendor',first:false,age:16,ageLabel:'16d',state:'paused',response:'Met',resolution:'Paused · awaiting vendor',next:'Check the vendor update',detail:'Replacement hardware is on order. The ticket is waiting on the vendor; public conversation responsibility is not recorded.'},
 {id:2042,title:'Shared mailbox permissions review',priority:'normal',owner:'Maya Patel',requester:'Ruby King',site:'Head office',status:'in_progress',party:'unknown',first:false,age:1,ageLabel:'1d',state:'ok',response:'Met',resolution:'Due in 2d',next:'Continue permissions review',detail:'The mailbox permission list needs a review. The requester has supplied the list of staff who need access.'},
 {id:2049,title:'Meeting room display flickers',priority:'low',owner:'Chris Ng',requester:'Leo White',site:'Head office',status:'open',party:'unknown',first:true,age:0.12,ageLabel:'3h',state:'unmeasured',response:'Unmeasured',resolution:'Unmeasured',next:'Record the first response',detail:'The meeting room display flickers intermittently. No SLA targets or public reply responsibility are recorded.'},
 {id:2050,title:'Check approved software installation',priority:'normal',owner:'Alex Morgan',requester:'Isla Brown',site:'Harbour House',status:'open',party:'it',first:false,age:0.08,ageLabel:'2h',state:'ok',response:'Met',resolution:'Due in 1d',next:'Review the requester’s device details',detail:'Isla has replied with the device identifier for the requested software installation.'},
 {id:2031,title:'Confirm access needed for visiting coordinator',priority:'high',owner:'Maya Patel',requester:'Oliver Green',site:'Kauri House',status:'waiting',party:'requester',first:false,age:6,ageLabel:'6d',state:'unmeasured',response:'Met',resolution:'Unmeasured · target missing',next:'Waiting for access requirements',detail:'The requester has been asked to clarify which approved systems are needed. A resolution SLA target is missing.'},
 {id:2012,title:'Equipment request awaiting approval',priority:'normal',owner:'Chris Ng',requester:'Aria Evans',site:'Harbour House',status:'waiting',party:'approver',first:false,age:13,ageLabel:'13d',state:'paused',response:'Met',resolution:'Paused · awaiting approver',next:'Review the approval follow-up',detail:'The equipment request is waiting on an approver. Its resolution clock is paused.'},
 {id:2044,title:'Configure accessible keyboard shortcuts',priority:'low',owner:'Maya Patel',requester:'Jack Turner',site:'Aurora House',status:'in_progress',party:'unknown',first:false,age:1,ageLabel:'1d',state:'ok',response:'Met',resolution:'Due in 3d',next:'Continue workstation setup',detail:'The approved keyboard shortcuts are being configured for the shared workstation.'},
];
type T = typeof initialTickets[number];
type View = 'attention'|'mine'|'unassigned'|'breached'|'breaching'|'awaiting_it'|'awaiting_reply'|'waiting_requester'|'waiting'|'aging'|'all_open'|'unmeasured'|'recently_resolved';
const viewInfo: Record<View,{label:string;blurb:string;icon:any;href:string}> = {
 attention:{label:'SLA attention',blurb:'Breached clocks first, then the nearest deadline.',icon:AlertTriangle,href:''},
 mine:{label:'My work',blurb:'Open tickets assigned to Alex Morgan, the simulated technician.',icon:UserRound,href:'/it?tab=tickets&view=mine'},
 unassigned:{label:'Unassigned',blurb:'No assigned technician. Pick up urgent work first.',icon:UsersRound,href:'/it?tab=tickets&view=unassigned'},
 breached:{label:'SLA breached',blurb:'Includes earlier breaches, even when a later clock is on track.',icon:AlertTriangle,href:'/it?tab=tickets&view=breached'},
 breaching:{label:'SLA at risk',blurb:'Measured clocks approaching their deadline.',icon:Timer,href:'/it?tab=tickets&view=breaching'},
 awaiting_it:{label:'Awaiting IT',blurb:'The next public response is recorded as IT’s responsibility.',icon:MessageSquareText,href:'/it?tab=tickets&view=awaiting_it'},
 awaiting_reply:{label:'First reply needed',blurb:'No first response recorded on open or in-progress tickets.',icon:Inbox,href:'/it?tab=tickets&view=awaiting_reply'},
 waiting_requester:{label:'Waiting on requester',blurb:'Waiting work whose recorded waiting party is the requester.',icon:Clock,href:'/it?tab=tickets&view=waiting_requester'},
 waiting:{label:'All waiting work',blurb:'Includes requester, vendor and approver waits.',icon:Clock,href:'/it?tab=tickets&view=waiting'},
 aging:{label:'Ageing tickets',blurb:'Open for more than 7 days, oldest first.',icon:Clock,href:'/it?tab=tickets&view=all_open&sort=created&dir=asc'},
 all_open:{label:'All open tickets',blurb:'All 14 synthetic open tickets, including waiting work.',icon:Ticket,href:'/it?tab=tickets&view=all_open'},
 unmeasured:{label:'SLA unmeasured',blurb:'A missing measurement is not evidence of compliance.',icon:CircleHelp,href:'/it?tab=tickets&view=unmeasured'},
 recently_resolved:{label:'Recently resolved',blurb:'Resolved or closed within the last 30 days.',icon:CircleCheck,href:'/it?tab=tickets&view=recently_resolved'},
};
const cap = (s:string)=>s.replaceAll('_',' ').replace(/^./,x=>x.toUpperCase());
const ref = (t:T)=>`IT-${t.id}`;
const match = (t:T,view:View) => ({attention:['breached','at_risk'].includes(t.state),mine:t.owner==='Alex Morgan',unassigned:!t.owner,breached:t.state==='breached',breaching:t.state==='at_risk',awaiting_it:t.party==='it',awaiting_reply:t.first,waiting_requester:t.status==='waiting'&&t.party==='requester',waiting:t.status==='waiting',aging:t.age>7,all_open:true,unmeasured:t.state==='unmeasured',recently_resolved:false})[view];
const priorityTone=(p:string)=>p==='urgent'||p==='high'?'critical':p==='normal'?'info':'neutral';
const clockTone=(text:string)=>text.includes('Breached')?'critical':text.includes('At risk')?'warning':'neutral';
function ClockLine({label,text}:{label:string;text:string}) {return <div className={`clock-line ${clockTone(text)}`}><span>{label}</span><strong>{text}</strong></div>}
function App(){
 const [tickets,setTickets]=useState(initialTickets);
 const [priority,setPriority]=useState('all');
 const [view,setView]=useState<View>('attention');
 const [slice,setSlice]=useState('all');
 const [peek,setPeek]=useState<number|null>(null);
 const [destination,setDestination]=useState<{href:string;title:string;view?:View;priority?:string}|null>(null);
 const [logOpen,setLogOpen]=useState(false);
 const [toast,setToast]=useState('');
 const [context,setContext]=useState<any>(null);
 const [draft,setDraft]=useState(false);
 const [ticketTitle,setTicketTitle]=useState('');
 const [note,setNote]=useState('');
 const [noteSaved,setNoteSaved]=useState(false);
 const [composeMode,setComposeMode]=useState<'note'|'reply'>('note');
 const count=(v:View)=>tickets.filter(t=>match(t,v)).length;
 const choose=(v:View)=>{setView(v);setSlice('all');};
 const notify=(message:string)=>{setToast(message);};
 useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(''),5000);return()=>clearTimeout(id);},[toast]);
 useEffect(()=>{setNote('');setNoteSaved(false);},[peek]);
 useEffect(()=>{if(peek===null)setComposeMode('note');},[peek]);
 function go(href:string,title?:string){
  const u=new URL(href,'https://mock.invalid');
  if(/^\/it\/tickets\/\d+$/.test(u.pathname)){setPeek(Number(u.pathname.split('/').at(-1)));return;}
  let v=u.searchParams.get('view') as View;
  if(u.searchParams.get('sort')==='created')v='all_open';
  if(u.pathname==='/it')setDestination({href,title:title??viewInfo[v||'all_open']?.label??'Ticket queue',view:v||'all_open',priority:u.searchParams.get('ticket_priority')||'all'});
  else setDestination({href,title:title??({'/it/knowledge':'Knowledge & Documentation','/it/provisioning':'Provisioning','/it/reports':'Reports'}[u.pathname]??'Linked workspace')});
 }
 useEffect(()=>{const handler=(e:any)=>go(e.detail);window.addEventListener('mock-navigate',handler);return()=>window.removeEventListener('mock-navigate',handler);},[priority]);
 const summary:any={my:{open:0,waiting:0,resolved_30d:0},tickets:{open:tickets.length,unassigned:count('unassigned'),urgent_unassigned:tickets.filter(t=>!t.owner&&t.priority==='urgent').length,urgent_open:tickets.filter(t=>t.priority==='urgent').length,at_risk:count('breaching'),breached:count('breached'),awaiting_reply:count('awaiting_reply'),conversation_ready:true,awaiting_it:count('awaiting_it'),waiting:count('waiting'),resolved_30d:0,met_30d:0,measured_30d:0,sla_open:{total:14,by_coverage:{full:11,partial:1,none:2},by_state:{paused:3,unmeasured:3}},sla_watchdog:{state:'unverified',last_success_at:null}}};
 const rows=tickets.filter(t=>match(t,view)&&(priority==='all'||t.priority===priority)&&(slice==='all'||t.state===slice)).sort((a,b)=>view==='aging'?b.age-a.age:0);
 const take=(t:T)=>{setTickets(old=>old.map(x=>x.id===t.id?{...x,owner:'Alex Morgan'}:x));notify(`${ref(t)} assigned to you in this mockup. No real ticket changed.`);};
 const actions=(t:T)=>[{label:'Preview ticket',icon:Eye,onClick:()=>setPeek(t.id)},{label:'Open ticket view',icon:ExternalLink,onClick:()=>setDestination({href:`/it/tickets/${t.id}`,title:`${ref(t)} · Ticket view`})},...(!t.owner?[{label:'Assign to me (mock)',icon:UserRound,onClick:()=>take(t)}]:[]),{label:'Add internal note (mock)',icon:FileText,onClick:()=>setPeek(t.id)}];
 const selected=tickets.find(t=>t.id===peek);
 function QueueLink({v}:{v:View}){const info=viewInfo[v];const Icon=info.icon;return <button type="button" className={`queue-option ${v===view?'selected':''}`} aria-pressed={v===view} onClick={()=>choose(v)}><Icon size={16}/><span>{info.label}</span><b>{tickets.filter(t=>match(t,v)&&(priority==='all'||t.priority===priority)).length}</b><ChevronRight size={14}/></button>}
 function TicketTable({list,compact=false}:{list:T[];compact?:boolean}){return <div className="ticket-scroll"><table className={`work-table ${compact?'compact':''}`}><thead><tr><th>Ticket</th><th>SLA clocks</th><th>Technician</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{list.map(t=><tr key={t.id} onContextMenu={e=>{e.preventDefault();setContext({x:e.clientX,y:e.clientY,t});}}><td><button type="button" className="ticket-identity" onClick={()=>setPeek(t.id)}><span className="ticket-title">{t.title}</span><span className="ticket-meta"><span>{ref(t)}</span><StatusBadge variant={priorityTone(t.priority)} size="sm">{cap(t.priority)}</StatusBadge><span>{t.ageLabel} old</span></span><span className="waiting-line">{t.first?'First reply needed':t.party==='it'?'Awaiting IT':t.party==='requester'?'Awaiting requester':t.party==='vendor'?'Waiting on vendor':t.party==='approver'?'Waiting on approver':'Next public reply not recorded'}</span></button></td><td><ClockLine label="Response" text={t.response}/><ClockLine label="Resolution" text={t.resolution}/></td><td>{t.owner?<div className="person"><span className="person-disc">{t.owner.split(' ').map(n=>n[0]).join('')}</span><span>{t.owner==='Alex Morgan'?'You':t.owner.split(' ')[0]}</span></div>:<button type="button" className="assign-link" onClick={()=>take(t)}><UserRound size={14}/><span>Assign to me</span></button>}</td><td><EntityKebab actions={actions(t)} label={`Actions for ${ref(t)}`}/></td></tr>)}</tbody></table></div>}
 return <TooltipProvider><div className="of-app">
 <a className="skip-link" href="#overview-content">Skip to Overview content</a>
 <header className="shell-header">
  <button className="wordmark-link" onClick={()=>go('/dashboard','Home')}><EventHorizonWordmark/></button>
  <span className="shell-date"><span className="long-date"><b>Sunday</b> 13 September 2026</span><span className="short-date"><b>Sun</b> 13 Sep</span></span>
  <button className="shell-search" onClick={()=>setDestination({href:'/it',title:'Find in IT & Support'})}><Search size={16}/><span>Search or jump to…</span><kbd>Ctrl K</kbd></button>
  <div className="shell-actions"><Button size="sm" onClick={()=>notify('Report incident belongs to the application shell. This review stays in the mockup.')}><AlertTriangle/>Report incident</Button><button className="shell-clock" onClick={()=>notify('Clock in/out is simulated in this mockup.')}><Clock size={16}/>Clock in/out</button><button className="shell-icon" aria-label="Messages" onClick={()=>notify('Messages are simulated. No communications are sent.')}><MessageSquareText size={19}/></button><button className="shell-icon" aria-label="Notifications" onClick={()=>notify('No live notifications are connected to this mockup.')}><Bell size={19}/></button><button className="shell-avatar" aria-label="User menu for Alex Morgan" onClick={()=>notify('Alex Morgan · simulated Service Desk technician')}>AM</button></div>
 </header>
 <div className="shell-layout"><aside className="shell-sidebar" aria-label="Primary navigation">
  <div className="sidebar-main">{[[House,'Home'],[CalendarDays,'My day'],[UsersRound,'People'],[HeartPulse,'Operations'],[ShieldCheck,'Governance'],[BriefcaseBusiness,'Finance']].map(([Icon,title]:any)=><button key={title} className="sidebar-module" onClick={()=>notify(`${title} is outside this Overview review.`)}><Icon size={16}/><span>{title}</span><ChevronRight size={14}/></button>)}
  <button className="sidebar-module active" onClick={()=>notify('Service Desk is the active workspace.')}><Server size={16}/><span>IT & Support</span><ChevronDown size={14}/></button>
  <nav className="sidebar-sub" aria-label="IT & Support">{[['Service desk','/it'],['Knowledge & Documentation','/it/knowledge'],['Provisioning','/it/provisioning'],['Work planning','/it/work'],['Problems','/it/problems'],['Changes','/it/changes'],['Major incidents','/it/major-incidents'],['Reports','/it/reports'],['Setup','/it/setup']].map(([label,href])=><a key={href} href={href} className={href==='/it'?'active':''} onClick={e=>{e.preventDefault();href==='/it'?choose('attention'):go(href,label);}}>{label}</a>)}</nav>
  {[[Layers,'Assets & facilities'],[Activity,'Reporting'],[ShieldCheck,'Security & Devices']].map(([Icon,title]:any)=><button key={title} className="sidebar-module" onClick={()=>notify(`${title} is outside this Overview review.`)}><Icon size={16}/><span>{title}</span><ChevronRight size={14}/></button>)}
  </div><div className="sidebar-footer"><button onClick={()=>notify('Help is simulated in this review.')}><CircleHelp size={16}/>Help & support</button><button onClick={()=>notify('Settings are outside this review.')}><Settings size={16}/>Settings</button></div>
  <button className="sidebar-edge" aria-label="Sidebar collapse (shell reference)" onClick={()=>notify('The shell dimensions stay fixed for this desktop review.')}><ChevronLeft size={12}/></button>
 </aside><main className="shell-content">
  <div className="breadcrumbs"><a href="/dashboard" onClick={e=>{e.preventDefault();go('/dashboard','Home');}}>Home</a><ChevronRight size={12}/><span>Service Desk</span></div>
  <div className="page-inner">
  <ItHero workspace="desk" summary={summary} can={{view:true,manage:true,request:false}} onLog={()=>{setDraft(false);setLogOpen(true);}} onRaise={()=>setLogOpen(true)} filters={<PageHeaderFilterSelect label="Priority" value={priority} allValue="all" options={['urgent','high','normal','low'].map(v=>({value:v,label:cap(v)}))} onChange={setPriority}/>} rail={<PageHeaderRail value="overview" onSelect={key=>key==='tickets'?go('/it?tab=tickets&view=all_open'):choose('attention')} items={[{key:'overview',label:'Overview',icon:LayoutDashboard},{key:'tickets',label:'Tickets',icon:Ticket,count:tickets.length}]} ariaLabel="IT views"/>}/>
  <ActionOverview tickets={tickets} priority={priority} view={view} viewInfo={viewInfo} isMatch={match} onViewChange={choose} onClearPriority={()=>setPriority('all')} onPeek={(id,reply=false)=>{setComposeMode(reply?'reply':'note');setPeek(id);}} onTake={take} onNavigate={go} renderTable={list=>TicketTable({list})}/></div>
 </main></div>
 <Dialog open={!!selected} onOpenChange={open=>{if(!open)setPeek(null);}}><DialogContent className="mock-peek sm:max-w-[720px]" onOpenAutoFocus={e=>{e.preventDefault();document.querySelector<HTMLButtonElement>('[data-slot="dialog-content"] button[aria-label="Close preview"]')?.focus();}}>
 {selected&&<><div className="peek-heading"><span className="preview-tag">Ticket preview · synthetic</span><DialogTitle>{selected.title}</DialogTitle><DialogDescription>{ref(selected)} · {selected.site} · Raised by {selected.requester}</DialogDescription></div><div className="peek-body"><div className="peek-state"><StatusBadge variant={priorityTone(selected.priority)}>{cap(selected.priority)}</StatusBadge><StatusBadge status={selected.status}/><span>{selected.ageLabel} old</span></div><h3>Next action</h3><p className="next-action">{selected.next}</p><div className="clock-panel"><ClockLine label="Response SLA" text={selected.response}/><ClockLine label="Resolution SLA" text={selected.resolution}/></div><p className="peek-detail">{selected.detail}</p><div className="peek-owner"><span>Assigned technician</span><strong>{selected.owner??'Unassigned'}</strong>{!selected.owner&&<Button variant="outline" size="sm" onClick={()=>take(selected)}>Assign to me</Button>}</div><form onSubmit={e=>{e.preventDefault();setNoteSaved(true);notify(composeMode==='reply'?'Reply preview ready. Nothing was sent.':'Internal note saved in this preview only. Nothing was sent.');}}><label htmlFor="mock-note">{composeMode==='reply'?'Public reply draft':'Internal note'} <span>{composeMode==='reply'?'Mock only · no message will be sent':'Mock only · visible to IT'}</span></label><textarea id="mock-note" rows={3} value={note} onChange={e=>{setNote(e.target.value);setNoteSaved(false);}} placeholder={composeMode==='reply'?'Draft the first response to the requester…':'Add context for the next technician…'} required/><div className="note-actions"><span aria-live="polite">{noteSaved?(composeMode==='reply'?'Reply preview ready · nothing sent.':'Saved in this preview only.'):'No public reply will be sent.'}</span><Button type="submit" variant="outline" size="sm" disabled={!note.trim()}>{composeMode==='reply'?'Preview reply':'Save mock note'}</Button></div></form></div><div className="peek-footer"><Button variant="outline" aria-label="Close preview" onClick={()=>setPeek(null)}>Back to Overview</Button><Button onClick={()=>{setDestination({href:`/it/tickets/${selected.id}`,title:`${ref(selected)} · Ticket view`});setPeek(null);}}>Open ticket view<ArrowUpRight/></Button></div></>}
 </DialogContent></Dialog>
 <Dialog open={!!destination} onOpenChange={open=>{if(!open)setDestination(null);}}><DialogContent className="mock-destination sm:max-w-[1000px]"><DialogTitle>{destination?.title}</DialogTitle><DialogDescription>Simulated destination · this link stays inside the review.</DialogDescription>{destination&&<><div className="destination-route"><span>Existing destination</span><code>{destination.href}</code></div>{destination.view?<><p className="destination-count">{tickets.filter(t=>match(t,destination.view!)&&(!destination.priority||destination.priority==='all'||t.priority===destination.priority)).length} synthetic tickets{destination.priority&&destination.priority!=='all'?` · ${cap(destination.priority)}`:''}</p>{tickets.some(t=>match(t,destination.view!)&&(!destination.priority||destination.priority==='all'||t.priority===destination.priority))?TicketTable({compact:true,list:tickets.filter(t=>match(t,destination.view!)&&(!destination.priority||destination.priority==='all'||t.priority===destination.priority)).sort((a,b)=>destination.href.includes('sort=created')?b.age-a.age:0)}):<div className="empty-state"><Inbox size={28}/><h3>No tickets match this queue</h3><p>There are no matching records in the synthetic ticket set. This does not establish SLA compliance.</p><Button variant="outline" onClick={()=>setDestination({...destination,href:viewInfo.all_open.href,title:'All open tickets',view:'all_open',priority:'all'})}>View all open tickets</Button></div>}</>:<div className="linked-view"><ExternalLink size={28}/><h3>{destination.href.startsWith('/it/tickets/')?'Continue in the ticket workspace':'A separate workspace'}</h3><p>{destination.href.startsWith('/it/tickets/')?'The production link opens the full ticket page. This mockup focuses on Overview navigation and its ticket preview.':'This destination remains outside the Service Desk tabs. The link is simulated for this Overview review.'}</p>{destination.href.startsWith('/it/tickets/')&&<Button variant="outline" onClick={()=>{setPeek(Number(destination.href.split('/').at(-1)));setDestination(null);}}>Open mock ticket preview</Button>}</div>}<div className="destination-footer"><Button variant="outline" onClick={()=>setDestination(null)}>Back to Overview</Button></div></>}</DialogContent></Dialog>
 <Dialog open={logOpen} onOpenChange={setLogOpen}><DialogContent className="mock-log sm:max-w-[600px]"><DialogTitle>{draft?'Mock ticket draft ready':'Log ticket · mock quick action'}</DialogTitle><DialogDescription>This small interaction previews entry from Overview. The production ticket wizard is outside this design review.</DialogDescription>{draft?<div className="draft-success"><CircleCheck size={30}/><h3>{ticketTitle}</h3><p>Stored only in this open preview. No ticket was created and no message was sent.</p><Button variant="outline" onClick={()=>setLogOpen(false)}>Return to Overview</Button></div>:<form onSubmit={e=>{e.preventDefault();setDraft(true);}}><label htmlFor="mock-title">Ticket title</label><input id="mock-title" autoFocus required value={ticketTitle} onChange={e=>setTicketTitle(e.target.value)} placeholder="Describe what needs attention"/><label htmlFor="mock-description">Details</label><textarea id="mock-description" rows={3} placeholder="What is happening, and who is affected?"/><div className="note-actions"><span>Mock draft only</span><Button type="submit">Preview draft<ArrowRight/></Button></div></form>}</DialogContent></Dialog>
 {context&&<EntityContextMenu x={context.x} y={context.y} title={ref(context.t)} icon={Ticket} items={actions(context.t)} onClose={()=>setContext(null)}/>}
 {toast&&<div className="mock-toast" role="status"><Check size={17}/>{toast}</div>}
 </div></TooltipProvider>
}
createRoot(document.getElementById('service-desk-overview-mockup')!).render(<App/>);
