#!/usr/bin/env php
<?php

declare(strict_types=1);

/**
 * Lab-only: mint a dedicated collector CA, a loopback TLS server certificate,
 * an Ed25519 configuration signing key, and a TLS public-key pin.
 *
 * Never reuse this material in production. Never print enrolment tokens.
 */

$root = dirname(__DIR__, 2);
$state = $root.DIRECTORY_SEPARATOR.'collector'.DIRECTORY_SEPARATOR.'lab-state';
$config = $root.DIRECTORY_SEPARATOR.'resources'.DIRECTORY_SEPARATOR.'monitoring'.DIRECTORY_SEPARATOR.'lab-collector-openssl.cnf';
if (! is_file($config)) {
    fwrite(STDERR, "lab-collector-bootstrap: OpenSSL config is missing.\n");
    exit(1);
}
if (! is_dir($state) && ! mkdir($state, 0700, true) && ! is_dir($state)) {
    fwrite(STDERR, "lab-collector-bootstrap: lab-state directory is unavailable.\n");
    exit(1);
}

$options = [
    'config' => $config,
    'digest_alg' => 'sha256',
    'private_key_bits' => 3072,
    'private_key_type' => OPENSSL_KEYTYPE_RSA,
];

$caKey = openssl_pkey_new($options);
$caRequest = $caKey === false ? false : openssl_csr_new([
    'commonName' => 'Oblivion lab collector CA',
    'organizationName' => 'Oblivion Findings',
    'organizationalUnitName' => 'Lab Collectors',
], $caKey, $options);
$caCertificate = $caRequest === false || $caKey === false
    ? false
    : openssl_csr_sign($caRequest, null, $caKey, 3650, $options + ['x509_extensions' => 'v3_ca'], random_int(1, PHP_INT_MAX));

$tlsKey = openssl_pkey_new($options);
$tlsRequest = $tlsKey === false ? false : openssl_csr_new([
    'commonName' => '127.0.0.1',
    'organizationName' => 'Oblivion Findings',
    'organizationalUnitName' => 'Lab Collector Proxy',
], $tlsKey, $options);
$tlsCertificate = $tlsRequest === false || $tlsKey === false || $caCertificate === false || $caKey === false
    ? false
    : openssl_csr_sign($tlsRequest, $caCertificate, $caKey, 30, $options + ['x509_extensions' => 'v3_server'], random_int(1, PHP_INT_MAX));

if ($caKey === false || $caCertificate === false || $tlsKey === false || $tlsCertificate === false
    || ! openssl_x509_export($caCertificate, $caCertificatePem)
    || ! openssl_pkey_export($caKey, $caKeyPem, null, $options)
    || ! openssl_x509_export($tlsCertificate, $tlsCertificatePem)
    || ! openssl_pkey_export($tlsKey, $tlsKeyPem, null, $options)) {
    fwrite(STDERR, "lab-collector-bootstrap: certificate generation failed.\n");
    exit(1);
}

$pin = spkiPin($tlsCertificatePem);
$signingKeyPair = sodium_crypto_sign_keypair();
$signingSecret = base64_encode(sodium_crypto_sign_secretkey($signingKeyPair));
sodium_memzero($signingKeyPair);

writePrivate($state.DIRECTORY_SEPARATOR.'ca.crt.pem', $caCertificatePem);
writePrivate($state.DIRECTORY_SEPARATOR.'ca.key.pem', $caKeyPem);
writePrivate($state.DIRECTORY_SEPARATOR.'proxy.crt.pem', $tlsCertificatePem);
writePrivate($state.DIRECTORY_SEPARATOR.'proxy.key.pem', $tlsKeyPem);
writePrivate($state.DIRECTORY_SEPARATOR.'tls-pin.txt', $pin."\n");
writePrivate($state.DIRECTORY_SEPARATOR.'central.env.snippet', implode("\n", [
    '# Lab-only values generated by scripts/monitoring/lab-collector-bootstrap.php',
    '# Copy into the Herd .env on STEPHAN-PC. Do not commit. Do not use in production.',
    'MONITORING_COLLECTOR_SIGNING_SECRET_KEY='.$signingSecret,
    'MONITORING_COLLECTOR_TRUSTED_PROXY_CIDRS=127.0.0.1/32,::1/128,172.16.0.0/12',
    'MONITORING_COLLECTOR_CA_CERTIFICATE_PATH='.$state.DIRECTORY_SEPARATOR.'ca.crt.pem',
    'MONITORING_COLLECTOR_CA_PRIVATE_KEY_PATH='.$state.DIRECTORY_SEPARATOR.'ca.key.pem',
    'MONITORING_COLLECTOR_CA_PRIVATE_KEY_PASSPHRASE=',
    'MONITORING_COLLECTOR_REPLAY_STORE=redis',
    'MONITORING_COLLECTOR_ALLOW_PROXY_FINGERPRINT_HEADER=false',
    '',
]));
writePrivate($state.DIRECTORY_SEPARATOR.'collector-id.txt', generateUuid()."\n");

fwrite(STDOUT, "lab-collector-bootstrap: wrote collector/lab-state (gitignored)\n");
fwrite(STDOUT, "lab-collector-bootstrap: TLS pin {$pin}\n");
fwrite(STDOUT, "lab-collector-bootstrap: copy collector/lab-state/central.env.snippet into Herd .env, then restart PHP\n");

function spkiPin(string $certificatePem): string
{
    $certificate = openssl_x509_read($certificatePem);
    $publicKey = $certificate === false ? false : openssl_pkey_get_public($certificate);
    $details = $publicKey === false ? false : openssl_pkey_get_details($publicKey);
    $pem = is_array($details) ? ($details['key'] ?? null) : null;
    if (! is_string($pem)) {
        throw new RuntimeException('Lab TLS public-key pin could not be derived.');
    }
    $der = base64_decode((string) preg_replace('/-----[^-]+-----|\s/', '', $pem), true);
    if (! is_string($der) || $der === '') {
        throw new RuntimeException('Lab TLS public-key pin encoding failed.');
    }

    return 'sha256//'.base64_encode(hash('sha256', $der, true));
}

function writePrivate(string $path, string $contents): void
{
    if (file_put_contents($path, $contents, LOCK_EX) !== strlen($contents)) {
        throw new RuntimeException('Lab state file could not be written.');
    }
    @chmod($path, 0600);
}

function generateUuid(): string
{
    $bytes = random_bytes(16);
    $bytes[6] = chr((ord($bytes[6]) & 0x0f) | 0x40);
    $bytes[8] = chr((ord($bytes[8]) & 0x3f) | 0x80);
    $hex = bin2hex($bytes);

    return substr($hex, 0, 8).'-'.substr($hex, 8, 4).'-'.substr($hex, 12, 4).'-'.substr($hex, 16, 4).'-'.substr($hex, 20, 12);
}
