<?php
declare(strict_types=1);
$root=realpath(__DIR__.'/../../../../../..');chdir($root);require $root.'/vendor/autoload.php';
$state=json_decode(file_get_contents(__DIR__.'/runtime-state.json'),true);
if(!preg_match('/^oblivion_gov_review_runtime_20260913_[0-9]+$/',$state['database']??''))throw new RuntimeException('Disposable database guard failed');
foreach(simplexml_load_file($root.'/phpunit.xml')->php->env as $e){$k=(string)$e['name'];$v=(string)$e['value'];putenv($k.'='.$v);$_ENV[$k]=$_SERVER[$k]=$v;}
foreach(['DB_DATABASE'=>$state['database'],'APP_CONFIG_CACHE'=>__DIR__.'/unused-config.php','MAIL_MAILER'=>'array','QUEUE_CONNECTION'=>'sync'] as $k=>$v){putenv($k.'='.$v);$_ENV[$k]=$_SERVER[$k]=$v;}
$app=require $root.'/bootstrap/app.php';$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();
use App\Domain\Governance\Models as M;
use App\Domain\Governance\Services as S;
use Illuminate\Support\Facades\DB;
class ExtraReview extends Tests\TestCase {
 use Tests\Support\GovernanceTestHelpers;
 public function attach($app):void{$this->app=$app;$this->withoutVite();}
 public function paper($u,$a=[]){return $this->createResolution($u,$a);}
 public function budget($u,$a=[]){return $this->createBudget($u,$a);}
}
$h=new ExtraReview('attach');$h->attach($app);Illuminate\Support\Facades\Mail::fake();Illuminate\Support\Facades\Notification::fake();
$actors=[];foreach($state['actors'] as $k=>$a)$actors[$k]=App\Models\User::findOrFail($a['user_id']);
$out=['checked_at'=>gmdate('c'),'database'=>$state['database'],'cases'=>[]];
function probe($name,Closure $fn){global $out;DB::beginTransaction();try{$out['cases'][$name]=$fn();}catch(Throwable $e){$out['cases'][$name]=['exception'=>get_class($e),'message'=>substr($e->getMessage(),0,800)];}finally{DB::rollBack();}}
probe('policy_old_acknowledgement_claims_new_version',function()use($h,$actors){$p=M\GovernancePolicy::create(['title'=>'Review versioned policy','policy_code'=>'REVIEW-POL-13','category'=>'governance','content'=>'Version one content','version_number'=>1,'status'=>'approved','requires_attestation'=>true,'owner_id'=>$actors['chair']->id,'created_by'=>$actors['chair']->id]);$response=$h->actingAs($actors['chair'])->post('/governance/policies/'.$p->id.'/attest',['acknowledged'=>true]);$att=M\PolicyAttestation::where('governance_policy_id',$p->id)->first();$before=$att?->toArray();$p->update(['content'=>'Materially changed version two','version_number'=>2]);$feed=app(S\GovernanceWorkQuery::class)->queryFeed($actors['chair'],['status'=>'completed']);return ['attest_status'=>$response->status(),'original_receipt'=>$before,'policy_version_now'=>$p->fresh()->version_number,'feed_contains_v2_attestation'=>str_contains(json_encode($feed),'Review versioned policy'),'feed'=>$feed];});
probe('unrelated_resolution_approves_strategy',function()use($h,$actors){$r=$h->paper($actors['chair'],['title'=>'Approve board meeting catering','status'=>'closed','outcome'=>'carried']);$p=M\StrategicPlan::create(['title'=>'Unrelated five year strategy','vision_statement'=>'Review vision','mission_statement'=>'Review mission','values'=>['Respect'],'planning_horizon'=>'5_year','period_start'=>'2026-01-01','period_end'=>'2030-12-31','status'=>'draft','version_number'=>1,'created_by'=>$actors['chair']->id]);$p->approve($r->id);return ['resolution_title'=>$r->title,'plan_title'=>$p->title,'plan_status'=>$p->fresh()->status,'approval_resolution_id'=>$p->fresh()->approval_resolution_id];});
probe('closed_evaluation_accepts_invalid_response',function()use($h,$actors){$e=M\BoardEvaluation::create(['title'=>'Review closed evaluation','evaluation_type'=>'board','year'=>2026,'status'=>'closed','questions'=>[['id'=>1,'question'=>'Rate board assurance','type'=>'rating']],'created_by'=>$actors['chair']->id]);$resp=$h->actingAs($actors['member'])->post('/governance/evaluations/'.$e->id.'/respond',['answers'=>[999]]);$stored=M\BoardEvaluationResponse::where('board_evaluation_id',$e->id)->first();return ['http_status'=>$resp->status(),'evaluation_status'=>$e->status,'response'=>$stored?->only(['board_member_id','answers','submitted_at'])];});
probe('evaluation_period_and_deadline_roundtrip',function()use($h,$actors){$resp=$h->actingAs($actors['chair'])->post('/governance/evaluations',['title'=>'Return review custom evaluation','evaluation_type'=>'board','period_start'=>'2026-03-01','period_end'=>'2026-06-30','due_date'=>'2026-11-15','questions'=>[['text'=>'Board quality','type'=>'rating']]]);$e=M\BoardEvaluation::where('title','Return review custom evaluation')->first();$detail=$e?$h->actingAs($actors['chair'])->get('/governance/evaluations/'.$e->id):null;return ['http_status'=>$resp->status(),'stored'=>$e?->toArray(),'detail_contains_requested_start'=>$detail?str_contains($detail->getContent(),'2026-03-01'):null,'detail_contains_requested_due'=>$detail?str_contains($detail->getContent(),'2026-11-15'):null];});
probe('missing_compliance_file_satisfies_completion',function()use($actors,$state){$o=M\ComplianceObligation::findOrFail($state['obligation_id']);$o->update(['evidence_required'=>true]);$e=M\ComplianceEvidence::create(['compliance_obligation_id'=>$o->id,'evidence_type'=>'document','title'=>'Evidence metadata without bytes','file_path'=>'return-review-does-not-exist.pdf','valid_until'=>'2027-01-01','uploaded_by'=>$actors['chair']->id,'uploaded_at'=>now(),'verified'=>false]);app(S\ComplianceEngineService::class)->completeObligation($o,$actors['chair'],[$e->id],'Claimed compliance evidence',$o->version_number);return ['file_exists'=>Illuminate\Support\Facades\Storage::disk('local')->exists($e->file_path),'evidence_verified'=>$e->verified,'obligation_status'=>$o->fresh()->status,'evidence_provided'=>$o->fresh()->evidence_provided];});
probe('duplicate_voting_reminders',function()use($h,$actors){$r=$h->paper($actors['chair']);app(S\VotingService::class)->openVoting($r);Illuminate\Support\Facades\Notification::fake();$j=new App\Domain\Governance\Jobs\SendVotingReminder($r,$actors['member']->boardMember);$j->handle();$j->handle();return ['same_job_invocations'=>2,'notifications_to_member'=>Illuminate\Support\Facades\Notification::sent($actors['member'],App\Domain\Governance\Notifications\VotingReminderNotification::class)->count()];});
probe('pack_recipient_receives_confidential_agenda',function()use($h,$actors,$state){
    Illuminate\Support\Facades\Auth::setUser($actors['chair']);
    $meeting=M\GovernanceMeeting::findOrFail($state['meeting_id']);
    $data=['widgets'=>[]];
    $snapshot=M\DashboardSnapshot::create(['snapshot_data'=>$data,'period_type'=>'month','period_start'=>'2026-09-01','period_end'=>'2026-09-30','checksum'=>M\DashboardSnapshot::generateChecksum($data),'captured_at'=>now(),'captured_by'=>$actors['chair']->id]);
    $content=(new ReflectionMethod(S\BoardPackBuilderService::class,'buildPackContent'))->invoke(app(S\BoardPackBuilderService::class),$meeting,$snapshot);
    $oldRoot=config('filesystems.disks.local.root');config(['filesystems.disks.local.root'=>__DIR__.'/runtime-storage/pack-probe']);Illuminate\Support\Facades\Storage::forgetDisk('local');
    try {
        Illuminate\Support\Facades\Storage::disk('local')->put('synthetic-pack.json',json_encode($content));
        $pack=M\BoardPack::create(['governance_meeting_id'=>$meeting->id,'dashboard_snapshot_id'=>$snapshot->id,'revision_number'=>1,'build_status'=>'published','is_current'=>true,'document_manifest'=>['manifest_sections'=>[],'content_sections'=>$content],'generated_at'=>now(),'generated_by'=>$actors['chair']->id,'file_path'=>'synthetic-pack.json','distributed_at'=>now(),'distributed_to'=>[$actors['member']->boardMember->id]]);
        $resp=$h->actingAs($actors['member'])->get('/governance/packs/'.$pack->id.'/download');
        $bytes=$resp->getStatusCode()===200?(function()use($resp){ob_start();$resp->sendContent();return ob_get_clean();})():'';
        return ['builder_content_contains_private_agenda'=>str_contains(json_encode($content),'REVIEW CONFIDENTIAL agenda'),'member_can_view_pack'=>app(S\BoardPackAccessService::class)->canView($actors['member'],$pack),'download_http_status'=>$resp->getStatusCode(),'download_contains_private_agenda'=>str_contains($bytes,'REVIEW CONFIDENTIAL agenda'),'note'=>'Real content builder and download controller; synthetic JSON used instead of PDF rendering.'];
    } finally {Illuminate\Support\Facades\Storage::disk('local')->delete('synthetic-pack.json');config(['filesystems.disks.local.root'=>$oldRoot]);Illuminate\Support\Facades\Storage::forgetDisk('local');}
});
probe('empty_action_evidence_in_local_environment',function()use($actors,$state){$old=app()->environment();app()->instance('env','local');try{$a=M\ActionItem::findOrFail($state['normal_action_id']);$a->update(['evidence_required'=>true]);$receipt=$a->markComplete($actors['member']->id,'No evidence bytes submitted',[[]],$a->version_number);return ['environment'=>app()->environment(),'status'=>$a->fresh()->status,'stored_evidence'=>$a->fresh()->evidence_attachments,'receipt'=>$receipt];}finally{app()->instance('env',$old);}});
probe('invalid_governance_setting_saved',function()use($h,$actors){$resp=$h->actingAs($actors['chair'])->put('/governance/settings',['settings'=>['spend_approval.threshold.capex'=>'not-a-number']]);return ['http_status'=>$resp->getStatusCode(),'saved_value'=>M\GovernanceSetting::where('key','spend_approval.threshold.capex')->value('value')];});
probe('wizard_followup_owner_name_ignored',function()use($h,$actors){$r=$h->paper($actors['chair'],['status'=>'closed','outcome'=>'carried','follow_up_actions'=>[['description'=>'Review owner round trip','assignee_name'=>$actors['member']->name,'due_date'=>'2026-10-01']]]);$r->generateActionItems();$a=$r->actionItems()->first();return ['requested_name'=>$actors['member']->name,'requested_user_id'=>$actors['member']->id,'actual_assigned_to'=>$a?->assigned_to,'proposed_by'=>$r->proposed_by];});
file_put_contents(__DIR__.'/extra-probe-results.json',json_encode($out,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES));echo json_encode($out,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES);

