<?php
declare(strict_types=1);
$root=realpath(__DIR__.'/../../../../../..');chdir($root);require $root.'/vendor/autoload.php';
$state=json_decode(file_get_contents(__DIR__.'/runtime-state.json'),true);
if(!preg_match('/^oblivion_gov_review_runtime_20260912_[0-9]+$/',$state['database']??''))throw new RuntimeException('Disposable database guard failed');
foreach(simplexml_load_file($root.'/phpunit.xml')->php->env as $e){$k=(string)$e['name'];$v=(string)$e['value'];putenv($k.'='.$v);$_ENV[$k]=$_SERVER[$k]=$v;}
foreach(['DB_DATABASE'=>$state['database'],'APP_CONFIG_CACHE'=>__DIR__.'/unused-config.php','MAIL_MAILER'=>'array','QUEUE_CONNECTION'=>'sync'] as $k=>$v){putenv($k.'='.$v);$_ENV[$k]=$_SERVER[$k]=$v;}
$app=require $root.'/bootstrap/app.php';$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();
use App\Domain\Governance\Models as M;
use App\Domain\Governance\Services as S;
use Illuminate\Support\Facades\DB;
class ExtraReview extends Tests\TestCase {
 use Tests\Support\GovernanceTestHelpers;
 public function attach($app):void{$this->app=$app;$this->withoutVite();}
 public function paper($u,$a=[]){return $this->createResolution($u,$a);}
 public function budget($u,$a=[]){return $this->createBudget($u,$a);}
}
$h=new ExtraReview('attach');$h->attach($app);Illuminate\Support\Facades\Mail::fake();Illuminate\Support\Facades\Notification::fake();
$actors=[];foreach($state['actors'] as $k=>$a)$actors[$k]=App\Models\User::findOrFail($a['user_id']);
$out=['checked_at'=>gmdate('c'),'database'=>$state['database'],'cases'=>[]];
function probe($name,Closure $fn){global $out;DB::beginTransaction();try{$out['cases'][$name]=$fn();}catch(Throwable $e){$out['cases'][$name]=['exception'=>get_class($e),'message'=>substr($e->getMessage(),0,800)];}finally{DB::rollBack();}}
probe('unanimous_all_entitled_for',function()use($h,$actors){$r=$h->paper($actors['chair'],['voting_threshold'=>'unanimous']);$s=app(S\VotingService::class);$s->openVoting($r);foreach(['chair','member','finance','other'] as $k)$s->castVote($r,$actors[$k]->boardMember,'for');$s->closeVoting($r);return ['outcome'=>$r->fresh()->outcome,'summary'=>$r->fresh()->vote_summary,'ratio_type'=>get_debug_type(4/4)];});
probe('ordinary_majority_written_without_authority',function()use($h,$actors){$r=$h->paper($actors['chair'],['voting_threshold'=>'simple_majority']);$s=app(S\VotingService::class);$s->openVoting($r);foreach(['chair'=>'for','member'=>'for','finance'=>'abstain'] as $k=>$v)$s->castVote($r,$actors[$k]->boardMember,$v);$s->closeVoting($r);return ['written_permitted'=>M\GovernanceVotingProfile::active()->first()->written_voting_permitted,'outcome'=>$r->fresh()->outcome];});
probe('ceo_raw_review_exposed',function()use($h,$actors,$state){$resp=$h->actingAs($actors['ceo'])->get('/governance/performance/'.$state['review_id']);return ['http_status'=>$resp->status(),'raw_assessment_in_response'=>str_contains($resp->getContent(),'REVIEW PRIVATE raw appraisal')];});
probe('private_decision_widget',function()use($actors,$state){Illuminate\Support\Facades\Auth::setUser($actors['member']);M\Resolution::findOrFail($state['private_resolution_id'])->update(['status'=>'open']);$data=app(S\DashboardAggregatorService::class)->getDecisionsRequired();return ['private_title_present'=>str_contains(json_encode($data),'REVIEW PRIVATE resolution')];});
probe('pack_confidential_agenda_and_motion',function()use($state){$meeting=M\GovernanceMeeting::findOrFail($state['meeting_id']);$snapshot=(object)['snapshot_data'=>['widgets'=>[]]];$svc=app(S\BoardPackBuilderService::class);$content=(new ReflectionMethod($svc,'buildPackContent'))->invoke($svc,$meeting,$snapshot);return ['confidential_title_in_content'=>str_contains(json_encode($content),'REVIEW CONFIDENTIAL agenda'),'paper_keys'=>array_keys($content['resolutions']['items'][0]??[])];});
probe('stale_minutes_approval',function()use($actors,$state){$m=M\MeetingMinute::findOrFail($state['minute_id']);$m->update(['status'=>'reviewed','version_number'=>1]);$s=app(S\MeetingMinuteService::class);$meeting=M\GovernanceMeeting::findOrFail($state['meeting_id']);$oldVersion=$m->version_number;$s->updateMinutes($meeting,[['heading'=>'Subsequent edit','content'=>'Content reviewer has not seen']],$actors['secretary'],1);$approved=$s->approveMinutes($meeting,$actors['chair']);return ['reviewer_saw_version'=>$oldVersion,'approved_version'=>$approved->version_number,'status'=>$approved->status];});
probe('unrelated_resolution_approves_budget',function()use($h,$actors){$u=$actors['chair'];$b=$h->budget($u);$line=M\BudgetLineItem::create(['budget_id'=>$b->id,'category'=>'operations','description'=>'Review budget baseline','budget_amount'=>100000,'forecast_amount'=>100000,'actual_amount'=>0]);$r=$h->paper($u,['status'=>'closed','outcome'=>'carried','title'=>'Unrelated vote: change meeting venue','cost_impact'=>null]);$adj=M\BudgetAdjustment::create(['budget_id'=>$b->id,'budget_line_item_id'=>$line->id,'adjustment_type'=>'increase','amount'=>6000,'reason'=>'Unrelated spending increase','proposed_by'=>$actors['secretary']->id,'proposed_at'=>now(),'status'=>'submitted','threshold_applies'=>true]);$result=app(S\GovernanceNestedMutationService::class)->approveBudgetAdjustment($u,$b,$adj,$r->id);return ['actor_role'=>'board_chair','resolution_title'=>$r->title,'resolution_cost_impact'=>$r->cost_impact,'adjustment_status'=>$result->status,'budget_total'=>$b->fresh()->total_budget];});
probe('implemented_decision_calendar_status',function()use($h,$actors){$r=$h->paper($actors['chair'],['status'=>'implemented','outcome'=>'carried','deadline'=>now()->subDay()]);$items=app(S\GovernanceCalendarQuery::class)->queryItems(now()->subDays(2),now()->addDay(),$actors['member'],['decisions']);return collect($items['events'])->firstWhere('id','governance:decision:'.$r->id);});
probe('policy_schema_and_work_feed',function()use($actors){$schema=Illuminate\Support\Facades\Schema::getColumnListing('policy_attestations');$policySchema=Illuminate\Support\Facades\Schema::getColumnListing('governance_policies');$feed=app(S\GovernanceWorkQuery::class)->queryFeed($actors['member']);return ['attestation_columns'=>$schema,'policy_version_column'=>array_values(array_filter($policySchema,fn($s)=>str_contains($s,'version'))),'policies_availability'=>$feed['availability']['policies'],'totals'=>$feed['totals']];});
probe('role_http_smoke',function()use($h,$actors,$state){$checks=[];foreach(['member','chair','secretary','finance','ceo','observer'] as $key){foreach(['/governance/dashboard','/governance/my-work','/governance/meetings/'.$state['private_meeting_id'],'/governance/performance/'.$state['review_id']] as $path){$response=$h->actingAs($actors[$key])->get($path);$checks[$key][$path]=$response->status();}}return $checks;});
file_put_contents(__DIR__.'/extra-probe-results.json',json_encode($out,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES));echo json_encode($out,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES);
