import React,{useState,useMemo} from 'react';
import {CalendarDays,ChevronLeft,ChevronRight} from 'lucide-react';
import {AgendaView,CalendarUIProvider,DayView,MonthView,WeekView,decorate,periodLabel,addDays,type CalView,type Decorated,type SourceDef} from '@/pages/sites/calendar/_parts';
import {DatePicker} from '@/components/fleet-assets/maintenance/date-picker';
import {Button,Alert} from './ui';
import {fleet,siteNames,TODAY,type Transport} from './domain';
import {matchText} from './connections';
const sources:SourceDef[]=[{key:'booking',label:'Fleet bookings',short:'Booking',group:'Fleet',icon:'Truck',origin:'auto',note:'The same linked Fleet reservation'},{key:'maintenance',label:'Fleet restrictions',short:'Unavailable',group:'Fleet',icon:'Wrench',origin:'auto',note:'Source-owned availability context'}];
const dayString=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
export function TransportCalendar({records,query,day,onDay,onOpen,onContext,onFleet}:{records:Transport[];query:string;day:string;onDay:(s:string)=>void;onOpen:(r:Transport)=>void;onContext:(e:React.MouseEvent,r:Transport)=>void;onFleet:()=>void}){
 const [view,setView]=useState<CalView>('week'),[vehicle,setVehicle]=useState('all'),[showFleet,setShowFleet]=useState(false);
 const navDate=useMemo(()=>new Date((day==='all'?TODAY:day)+'T12:00:00'),[day]);
 const rows=records.filter(r=>r.booking&&r.booking.state!=='cancelled'&&r.booking.state!=='rejected'&&(vehicle==='all'||r.booking.vehicle===vehicle)&&matchText([r.person,r.id,r.booking.id,r.booking.driver,fleet[r.booking.vehicle].name,r.destination].join(' '),query));
 const entries:Decorated[]=rows.map(r=>({...decorate({id:r.booking!.id,source:'booking',group:'auto',title:r.person+' · '+fleet[r.booking!.vehicle].name,start:r.start,end:r.end,allDay:false,status:r.booking!.state==='pending'?'pending':r.booking!.state==='returned'?'completed':'approved',owner:{id:1,name:r.booking!.driver},room:r.pickup,ref:r.booking!.id,site:{id:r.site==='aurora'?1:2,name:siteNames[r.site],type:'Site'},link:null,editable:false,desc:r.pickup+' → '+r.destination}),typeLabel:'Fleet booking',statusLabel:r.booking!.state==='pending'?'Proposed':'Confirmed'}));
 if(showFleet&&records.some(r=>r.site==='aurora')&&(vehicle==='all'||vehicle==='kea'))entries.push({...decorate({id:'FLEET-M-18',source:'maintenance',group:'auto',title:'Kea · workshop service',start:TODAY+'T15:30',end:TODAY+'T17:00',allDay:false,status:'scheduled',owner:null,room:'Workshop',ref:'M-18',site:{id:1,name:'Aurora House',type:'Site'},link:null,editable:false}),typeLabel:'Maintenance'});
 const select=(entry:Decorated)=>{const record=records.find(r=>r.booking?.id===entry.id);record?onOpen(record):onFleet()};
 const move=(direction:number)=>{const date=new Date(navDate);if(view==='month'||view==='agenda')date.setMonth(date.getMonth()+direction,1);else date.setDate(date.getDate()+direction*(view==='day'?1:7));onDay(dayString(date))};
 return <div className="page-stack transport-calendar"><div className="calendar-explanation"><CalendarDays/><div><strong>Transport calendar · shared Fleet bookings</strong><p>Plan passenger transport here. Each entry is the same reservation shown in Fleet and the vehicle profile.</p></div><Button variant="outline" onClick={()=>setShowFleet(v=>!v)}>{showFleet?'Show transport only':'Include other Fleet activity'}</Button></div><div className="calendar-toolbar"><div className="button-row"><Button variant="outline" aria-label="Previous calendar period" onClick={()=>move(-1)}><ChevronLeft/></Button><Button variant="outline" onClick={()=>onDay(TODAY)}>Example day</Button><Button variant="outline" aria-label="Next calendar period" onClick={()=>move(1)}><ChevronRight/></Button><strong>{periodLabel(view,navDate)}</strong><div className="calendar-date-jump"><DatePicker id="transport-calendar-date" label="Jump to calendar date" value={day==='all'?TODAY:day} onChange={onDay}/></div></div><div className="button-row"><label>Vehicle<select aria-label="Calendar vehicle" value={vehicle} onChange={e=>setVehicle(e.target.value)}><option value="all">All permitted vehicles</option>{Object.entries(fleet).filter(([id])=>records.some(r=>r.booking?.vehicle===id)).map(([id,v])=><option key={id} value={id}>{v.name}</option>)}</select></label><div className="queue-tabs" role="group" aria-label="Calendar view">{(['month','week','day','agenda'] as CalView[]).map(v=><button key={v} aria-pressed={v===view} className={v===view?'selected':''} onClick={()=>setView(v)}>{v[0].toUpperCase()+v.slice(1)}</button>)}</div></div></div><CalendarUIProvider value={{colorBy:'source',density:'comfortable',srcByKey:Object.fromEntries(sources.map(v=>[v.key,v])),onSelect:select,onEntryContext:(entry,e)=>{const r=records.find(v=>v.booking?.id===entry.id);r?onContext(e,r):select(entry)},onMore:d=>{onDay(dayString(d));setView('day')}}}><div className={"calendar-surface calendar-"+view}>{view==='month'?<MonthView events={entries} navDate={navDate}/>:view==='week'?<WeekView events={entries} navDate={navDate}/>:view==='day'?<DayView events={entries} navDate={navDate}/>:<AgendaView events={entries} navDate={navDate} sourcesOff={false} filtersActive={!!query||vehicle!=='all'}/>}</div></CalendarUIProvider><p className="muted">Select a booking for a quick view or right-click for its actions. Unallocated requests stay in Allocate requests. All availability checks and changes use the linked Fleet booking.</p>{showFleet&&<Alert title="Other Fleet activity shown">Workshop entry M-18 is synthetic source context. Fleet owns maintenance and unavailability; Transport does not create another reservation calendar.</Alert>}</div>;
}
