import React, {useEffect, useRef, useState} from 'react';
import {CheckCircle2, ClipboardList, Route, FileCheck, ArrowLeft} from 'lucide-react';
import {Textarea} from '@/components/ui/textarea';
import {FileDropzone, StagedFileCard} from '@/components/ui/file-dropzone';
import {WizardShell, WizardStepPane, ReviewCard, ReviewRow} from '@/components/wizard/shell';
import {DateTimeField, localDateTimeLabel} from '@/components/fleet-assets/maintenance/date-time-field';
import {displayTime} from '@/components/fleet-assets/maintenance/time-picker';
import {Alert, Button, Input, Modal, Picker, Tick} from './ui';
import {actors, fleet, siteNames, TODAY, NOW, type Role, type Transport, type Operation, type Command, type Availability, validDate} from './domain';

export const formTitles:Record<string,string>={request:'Request transport',assess:'Assess transport need',information:'Request more information',respond:'Provide missing information',allocate:'Allocate transport',reschedule:'Change resources or time',approve:'Review booking approval',reject:'Reject booking',check:'Vehicle pre-use check',checkout:'Collect keys and equipment',depart:'Record actual departure',return:'Record actual return',custody:'Receive outstanding items',passengers:'Confirm passenger return',medication:'Medication logistics source',complete:'Complete journey',cancel:'Record a demand outcome',handover:'Hand over to another shift',accept:'Acknowledge handover',dispute:'Dispute handover',exception:'Assign an exception',resolve:'Record reconciliation',note:'Add a record note',evidence:'Add supporting evidence'};
export const actionLabels:Record<string,string>={assess:'Save assessment',information:'Request information',respond:'Send information',allocate:'Save proposed allocation',reschedule:'Save booking changes',approve:'Confirm booking decision',reject:'Reject booking',check:'Submit vehicle check',checkout:'Record checkout',depart:'Record departure',return:'Save return receipt',custody:'Record later receipt',passengers:'Confirm passenger return',medication:'Refresh resolved source result',complete:'Complete journey',cancel:'Record outcome',handover:'Send handover',accept:'Acknowledge receipt',dispute:'Record dispute',exception:'Assign exception',resolve:'Save reconciliation',note:'Save note'};
export function Field({label,value,onChange,textarea=false,type='text'}:{label:string;value:string;onChange:(s:string)=>void;textarea?:boolean;type?:string}){
 const id=label.toLowerCase().replace(/[^a-z0-9]/g,'-');return <div><label className="field-label" htmlFor={id}>{label}</label>{textarea?<Textarea id={id} value={value} onChange={e=>onChange(e.target.value)}/>:<Input id={id} type={type} value={value} onChange={e=>onChange(e.target.value)}/>}</div>;
}
function DirtyPrompt({onKeep,onDiscard}:{onKeep:()=>void;onDiscard:()=>void}){return <Alert tone="warning" title="Discard these unsaved changes?"><p>The saved record stays as it was.</p><div className="button-row"><Button variant="outline" onClick={onKeep}>Keep editing</Button><Button onClick={onDiscard}>Discard changes</Button></div></Alert>}
export function RequestForm({role,entry,initialPerson='',initialSite='aurora',existing,onClose,onSave}:{role:Role;entry?:string;initialPerson?:string;initialSite?:string;existing?:Transport;onClose:()=>void;onSave:(p:Record<string,any>)=>void}){
 const [p,setP]=useState(existing?{person:existing.person,site:existing.site,purpose:existing.purpose,pickup:existing.pickup,destination:existing.destination,start:existing.start,end:existing.end,seats:String(existing.seats),wheelchair:existing.wheelchair,escortRequired:existing.escortRequired,need:existing.need}:{person:initialPerson||(entry==='client'?'Alex Morgan':''),site:initialSite,purpose:'',pickup:siteNames[initialSite],destination:'',start:TODAY+'T11:30',end:TODAY+'T12:30',seats:'2',wheelchair:false,escortRequired:false,need:''});
 const [step,setStep]=useState(0),[dirty,setDirty]=useState(false),[discard,setDiscard]=useState(false),[error,setError]=useState('');
 const set=(key:string,value:any)=>{setP(old=>({...old,[key]:value}));setDirty(true);setError('')};
 const validate=()=>{if(!p.person.trim()||!p.purpose.trim()||!p.pickup.trim()||!p.destination.trim())throw Error('Complete passenger, purpose, pickup and destination.');if(!validDate(p.start)||!validDate(p.end)||p.end<=p.start)throw Error('Expected return must be after the pickup date and time.');if(Number(p.seats)<2||Number(p.seats)>8||!Number.isInteger(Number(p.seats)))throw Error('Enter 2–8 total occupants, including the driver.');if(p.escortRequired&&Number(p.seats)<3)throw Error('Include the passenger, driver and escort in total occupants.')};
 useEffect(()=>{if(error)document.querySelector<HTMLElement>('[role=dialog] .form-error')?.focus()},[error]);
 const next=()=>{try{validate();setError('');setStep(1)}catch(e){setError((e as Error).message)}};
 const save=()=>{try{validate();onSave(p)}catch(e){setError((e as Error).message)}};
 return <WizardShell open onClose={()=>dirty?setDiscard(true):onClose()} title={existing?'Edit transport request':'Request transport'} description="Synthetic request. Vehicle and driver can be allocated after assessment." railIcon={Route} railTitle={existing?'Edit transport request':'Request transport'} railSub={entry==='client'?'From Client · '+p.person:entry==='site'?'From Site · '+siteNames[p.site]:'New transport need'} steps={[{key:'need',label:'Transport need',blurb:'Person, time and support',icon:Route},{key:'review',label:'Review request',blurb:'Confirm before sending',icon:FileCheck,disabled:step===0}]} stepIndex={step} onStepClick={n=>n===0?setStep(0):next()} pct={null} footerStart={<span className="muted">{dirty?'Unsaved draft · this dialog only':'Nothing submitted yet'}</span>} footerEnd={<><Button variant="outline" onClick={()=>step?setStep(0):dirty?setDiscard(true):onClose()}>{step?'Back':'Cancel'}</Button><Button onClick={step?save:next}>{step?existing?'Save request changes':'Submit transport request':'Review request'}</Button></>}>
  <div className="p-6 form-stack">{discard&&<DirtyPrompt onKeep={()=>setDiscard(false)} onDiscard={onClose}/>}<WizardStepPane><div className="form-intro"><h2>{step?'Review the transport need':'Where does the person need to go?'}</h2><p>{step?'This submits an unallocated request for assessment.':'Record only the information needed to arrange safe transport.'}</p></div>
   {step===0?<div className="form-stack"><div className="form-grid"><Picker label="Passenger" disabled={!!existing} value={p.person} onChange={v=>{const site=v==='Jordan Lee'?'kowhai':'aurora';set('person',v);set('site',site);set('pickup',siteNames[site]);set('need','');set('wheelchair',false);set('escortRequired',false);set('seats','2')}} options={[...((existing?.person||initialPerson)&&!['Alex Morgan','Jordan Lee'].includes(existing?.person||initialPerson)?[{id:existing?.person||initialPerson,name:existing?.person||initialPerson,detail:siteNames[existing?.site||initialSite]+' · permitted source context'}]:[]),{id:'Alex Morgan',name:'Alex Morgan',detail:'Aurora House · permitted client'},{id:'Jordan Lee',name:'Jordan Lee',detail:'Kōwhai House · permitted client',}].filter(option=>option.id!=='Jordan Lee'||actors[role].sites.includes('kowhai'))}/><Picker label="Request site" disabled={!!existing} value={p.site} onChange={v=>{set('site',v);set('pickup',siteNames[v]);set('person',v==='kowhai'?'Jordan Lee':'Alex Morgan');set('need','');set('wheelchair',false);set('escortRequired',false);set('seats','2')}} options={actors[role].sites.map(id=>({id,name:siteNames[id],detail:'Approved site'}))}/></div><Field label="Purpose" value={p.purpose} onChange={v=>set('purpose',v)}/><div className="form-grid"><Field label="Pickup point" value={p.pickup} onChange={v=>set('pickup',v)}/><Field label="Destination" value={p.destination} onChange={v=>set('destination',v)}/></div><DateTimeField id="pickup" label="Pickup" value={p.start} onChange={v=>set('start',v)}/><DateTimeField id="expected" label="Expected return" value={p.end} onChange={v=>set('end',v)}/><Field label="Total occupants including driver" type="number" value={p.seats} onChange={v=>set('seats',v)}/><Tick label="Wheelchair position required" checked={p.wheelchair} onChange={v=>set('wheelchair',v)}/><Tick label="Escort required" checked={p.escortRequired} onChange={v=>set('escortRequired',v)}/><Field label="Transport support or missing information" textarea value={p.need} onChange={v=>set('need',v)}/></div>:<ReviewCard title="Request for assessment" icon={ClipboardList}><ReviewRow label="Passenger / site" value={p.person+' · '+siteNames[p.site]}/><ReviewRow label="Purpose" value={p.purpose}/><ReviewRow label="Route" value={p.pickup+' → '+p.destination}/><ReviewRow label="Pickup" value={localDateTimeLabel(p.start)}/><ReviewRow label="Expected return" value={localDateTimeLabel(p.end)}/><ReviewRow label="Occupants" value={p.seats+' including driver'+(p.escortRequired?' and escort':'')}/><ReviewRow label="Support" value={(p.wheelchair?'Wheelchair position; restraints kit. ':'')+(p.escortRequired?'Escort required. ':'')+(p.need||'No additional information')}/><ReviewRow label="Requester" value={existing?.requester||actors[role].name}/><ReviewRow label="Next owner" value="Transport allocator · needs assessment"/></ReviewCard>}
  </WizardStepPane>{error&&<p role="alert" className="form-error" tabIndex={-1}>{error}</p>}</div>
 </WizardShell>;
}

type Props={kind:Operation;r:Transport;role:Role;availability:Availability;onAvailability:(a:Availability)=>void;lostResponse:boolean;onClose:()=>void;onCommit:(c:Command)=>string;onSaved:(result:string)=>void;inline?:boolean;onDirty?:(dirty:boolean)=>void};
export function RecordForm({kind,r,role,availability,onAvailability,lostResponse,onClose,onCommit,onSaved,inline=false,onDirty}:Props){
 const [p,setP]=useState<Record<string,any>>(()=>({
  note:'',reason:'',reviewed:false,confirmed:false,vehicle:r.booking?.vehicle||'',driver:r.booking?.driver||'',escort:r.booking?.escort||'',equipment:kind==='checkout'||kind==='return'||kind==='custody'?false:r.booking?.equipment||r.equipment,start:r.start,end:r.end,
  time:kind==='return'?(r.journey?.departed&&r.journey.departed>NOW?r.end:NOW):kind==='depart'?(r.checkout?.time||r.start):kind==='checkout'||kind==='check'?r.start:NOW,
  odometer:String(kind==='return'?(r.checkout?.odometer||48210)+38:48210),fuel:'¾',giver:'',receiver:'',site:r.site,keys:false,passengers:false,condition:'',damage:false,failed:false,
  incoming:'',items:'Keys and equipment',owner:'Mia Chen',outcome:'Requester cancelled',exception:r.exceptions.find(e=>e.state==='open')?.id||'',
 }));
 const [dirty,setDirty]=useState(false),[discard,setDiscard]=useState(false),[error,setError]=useState(''),[uncertain,setUncertain]=useState(''),[recovered,setRecovered]=useState(false),[availabilityMessage,setAvailabilityMessage]=useState('');
 const op=useRef(crypto.randomUUID()),version=useRef(r.version);
 const planning=kind==='allocate'||kind==='reschedule';
 const [checkedDraft,setCheckedDraft]=useState('');
 const draftKey=JSON.stringify([p.vehicle,p.driver,p.escort,p.equipment,p.start,p.end]);
 const currentCheck=checkedDraft===draftKey&&availability==='available';
 useEffect(()=>{if(error)document.querySelector<HTMLElement>('[role=dialog] .form-error')?.focus()},[error]);
 const set=(key:string,value:any)=>{setP(old=>({...old,[key]:value}));setDirty(true);onDirty?.(true);setError('');if(planning){setCheckedDraft('');setAvailabilityMessage('Selections changed. Check this proposal before saving.')}};
 const submit=()=>{try{if(planning&&!currentCheck)throw Error('Check availability for these exact resources and times before saving.');const result=onCommit({id:op.current,record:r.id,type:kind,version:version.current,payload:p});setError('');if(kind==='return'&&lostResponse&&!uncertain){setUncertain(result);setDirty(false);return}onSaved(result)}catch(e){setError((e as Error).message)}};
 const latestReceipt=r.receipts.find(v=>v.operation===op.current);
 const recheck=()=>{
  setCheckedDraft('');setError('');
  const vehicle=fleet[p.vehicle as keyof typeof fleet];
  if(!vehicle||!p.driver||!p.equipment||r.escortRequired&&!p.escort){setAvailabilityMessage('Choose the required vehicle, driver, escort and equipment first.');return}
  if(!validDate(p.start)||!validDate(p.end)||p.end<=p.start){setAvailabilityMessage('Expected return must be after a valid pickup date and time.');return}
  if(vehicle.seats<r.seats||r.wheelchair&&!vehicle.wheelchair||p.vehicle==='tui'||vehicle.site!==r.site){setAvailabilityMessage('This vehicle cannot meet the site, capacity or accessibility requirements.');return}
  if(r.wheelchair&&p.equipment!=='Wheelchair restraints kit'){setAvailabilityMessage('This request needs the wheelchair restraints kit.');return}
  if(availability==='unknown'){setAvailabilityMessage('Fleet readiness configuration is missing. The owning Fleet team must resolve it.');return}
  if(availability==='conflict'&&p.start===r.start&&p.vehicle===(r.booking?.vehicle||'koru')){setAvailabilityMessage('This vehicle and time still conflict. Change the time or a suitable vehicle, then check again.');return}
  onAvailability('available');setCheckedDraft(draftKey);setAvailabilityMessage('Available for this proposal: vehicle, team, equipment and full time window checked.');
 };
 const actorLabel=actors[role].name+' · '+actors[role].title;
 const observation=(label='Reason')=><Field label={label} textarea value={p.reason} onChange={v=>set('reason',v)}/>;
 const time=()=> <DateTimeField id="actual-time" label={kind==='return'?'Actual return':kind==='depart'?'Actual departure':'Observed at'} value={p.time} onChange={v=>set('time',v)}/>;
 const selectors=<><Picker label="Vehicle" value={p.vehicle} onChange={v=>set('vehicle',v)} options={Object.entries(fleet).map(([id,v])=>({id,name:v.name,detail:v.ref+' · '+v.seats+' seats · '+siteNames[v.site],unavailable:v.site!==r.site?'Outside the request site':id==='tui'?'Active Maintenance restriction':v.seats<r.seats?'Not enough seats':r.wheelchair&&!v.wheelchair?'No wheelchair position':undefined}))}/><div className="form-grid"><Picker label="Driver" value={p.driver} onChange={v=>set('driver',v)} options={[{id:'Nia Patel',name:'Nia Patel',detail:'Eligibility and availability confirmed for this example'},{id:'Liam Chen',name:'Liam Chen',detail:'Driver eligibility confirmed in this example'},{id:'Eli Thompson',name:'Eli Thompson',detail:'Eligibility needs assessment',unavailable:'Not confirmed for this window'}]}/><Picker optional label="Escort" value={p.escort} onChange={v=>set('escort',v)} options={[{id:'Sara Wilson',name:'Sara Wilson',detail:'Escort availability confirmed for this example'}]}/></div><Picker label="Required equipment" value={p.equipment} onChange={v=>set('equipment',v)} options={[{id:'Wheelchair restraints kit',name:'Wheelchair restraints kit',detail:'Confirmed with Koru in this example'},{id:'No additional equipment',name:'No additional equipment',detail:'Only if consistent with assessed need'}]}/></>;
 const body=()=>{
  switch(kind){
   case 'assess':return <><Alert title="Review this request before allocating"><p>{r.person} · {r.purpose}. {r.seats} occupants, {r.wheelchair?'wheelchair position required':'standard seating'}, {r.escortRequired?'escort required':'no escort requested'}.</p></Alert><Field label="Assessment and confirmed needs" textarea value={p.note} onChange={v=>set('note',v)}/></>;
   case 'information':return <><Alert title="Return the request to its owner">{r.requester} will see the missing information. A linked booking keeps its own decision state.</Alert>{observation('What information is needed?')}</>;
   case 'respond':return <><Alert title="Information requested">{r.need}</Alert><Field label="Response" textarea value={p.note} onChange={v=>set('note',v)}/></>;
   case 'allocate':case 'reschedule':return <><div className="allocation-intro"><strong>{r.booking?'Update '+r.booking.id:'Choose a vehicle and team'}</strong><p>{r.seats} occupants · {r.wheelchair?'wheelchair position':'standard seating'} · {r.escortRequired?'escort required':'no escort required'}</p></div><div className="planning-selectors">{selectors}</div><details className="plan-dates"><summary>Transport window · {localDateTimeLabel(p.start)} → {displayTime(p.end.slice(11))} <span>Change</span></summary><DateTimeField id="plan-pickup" label="Pickup" value={p.start} onChange={v=>set('start',v)}/><DateTimeField id="plan-return" label="Expected return" value={p.end} onChange={v=>set('end',v)}/></details><div className="availability-check"><div><strong>{currentCheck?'Available for this proposal':availability==='unknown'?'Fleet setup needs attention':availability==='conflict'?'Resolve the time conflict':'Check your selections'}</strong><p role="status">{availabilityMessage||'Confirm the complete window before saving. Changing a selection requires another check.'}</p></div><Button variant="outline" onClick={recheck}>Check availability</Button></div></>;
   case 'approve':return <><ReviewCard title={r.booking?.id+' · Fleet booking'} icon={FileCheck}><ReviewRow label="Requested by" value={r.booking?.requestedBy||''}/><ReviewRow label="Vehicle / driver" value={(r.booking?fleet[r.booking.vehicle].name:'')+' · '+r.booking?.driver}/><ReviewRow label="Route" value={r.pickup+' → '+r.destination}/><ReviewRow label="Decision route" value={r.booking?.approval==='not_required'?'Approval not required · source authority must be recorded':'Independent Fleet booking approval'}/><ReviewRow label="Authority" value="fleet.bookings.approve or fleet.manage + approved vehicle/site access"/></ReviewCard><Alert tone={availability==='available'?'success':'warning'} title={'Current readiness: '+availability}>Rechecked at decision time. Finance and vehicle safety release retain their own authority.</Alert>{availability!=='available'&&<Button variant="outline" onClick={recheck}>Recheck Fleet availability</Button>}{availabilityMessage&&<p role="status">{availabilityMessage}</p>}<Tick label="I reviewed the current booking and readiness result" checked={p.reviewed} onChange={v=>set('reviewed',v)}/>{observation('Decision note')}</>;
   case 'reject':return observation('Reason for rejecting this booking');
   case 'check':return <><p>Assigned vehicle: <strong>{r.booking?fleet[r.booking.vehicle].name:'Not allocated'}</strong>. Required template: assigned vehicle pre-use, version 3.</p><Tick label="A check item failed or a new defect was found" checked={p.failed} onChange={v=>set('failed',v)}/><Field label="Check observation" textarea value={p.note} onChange={v=>set('note',v)}/>{time()}<p className="muted">This bounded example submits the assigned source check. A failed check retains its original observation and links a Maintenance report; it prevents checkout.</p></>;
   case 'checkout':return <><p>{r.check?.id||'No submitted check'} · {r.check?.outcome==='pass'?'passed and retained':'successful check required'}</p><Picker label="Actual giver" value={p.giver} onChange={v=>set('giver',v)} options={[{id:'Ben Carter',name:'Ben Carter',detail:'Recorded holder · Aurora House'},{id:'Unknown holder',name:'Unknown holder',detail:'Requires reconciliation',unavailable:'Record an exception first'}]}/><p>Actual receiver: <strong>{actorLabel}</strong></p>{time()}<div className="form-grid"><Field label="Checkout odometer (km)" type="number" value={p.odometer} onChange={v=>set('odometer',v)}/><Picker label="Fuel / charge" value={p.fuel} onChange={v=>set('fuel',v)} options={['Full','¾','½','¼'].map(id=>({id,name:id,detail:'Observed level'}))}/></div><Tick label="Keys physically received" checked={p.keys} onChange={v=>set('keys',v)}/><Tick label="Required equipment physically received" checked={p.equipment===true} onChange={v=>set('equipment',v)}/></>;
   case 'depart':return <><p>Passenger: <strong>{r.person}</strong> · {r.pickup} → {r.destination}</p><p>Actual driver: <strong>{actors.driver.name}</strong>{r.booking?.escort?' · Escort: '+r.booking.escort:''}</p>{time()}<Tick label="Passenger list confirmed for departure" checked={p.passengers} onChange={v=>set('passengers',v)}/><p className="muted">The actual journey is created when the assigned driver records departure. The request and reservation remain linked records.</p></>;
   case 'return':return <>{time()}<div className="form-grid"><Field label="Return odometer (km)" type="number" value={p.odometer} onChange={v=>set('odometer',v)}/><Picker label="Fuel / charge" value={p.fuel} onChange={v=>set('fuel',v)} options={['Full','¾','½','¼'].map(id=>({id,name:id,detail:'Observed level'}))}/></div><Picker label="Actual receiver" value={p.receiver} onChange={v=>set('receiver',v)} options={[{id:'Ben Carter',name:'Ben Carter',detail:'Receiving worker · Aurora House'}]}/><Picker label="Return site" value={p.site} onChange={v=>set('site',v)} options={Object.entries(siteNames).map(([id,name])=>({id,name,detail:id===r.site?'Expected return site':'Unexpected site · needs reconciliation'}))}/><Tick label="Keys received by named worker" checked={p.keys} onChange={v=>set('keys',v)}/><Tick label="All expected equipment received" checked={p.equipment===true} onChange={v=>set('equipment',v)}/><Field label="Return condition" textarea value={p.condition} onChange={v=>set('condition',v)}/><Tick label="Report new damage or a post-use defect" checked={p.damage} onChange={v=>set('damage',v)}/><p className="muted">A partial return stays visible with an accountable exception. This receipt does not acknowledge a separate shift handover or release a safety restriction.</p></>;
   case 'custody':return <><p>The original return receipt stays unchanged. This records the later physical receipt by <strong>{actorLabel}</strong>.</p><Picker label="Actual giver" value={p.giver} onChange={v=>set('giver',v)} options={[{id:'Nia Patel',name:'Nia Patel',detail:'Outgoing worker · actual giver'},{id:'Sara Wilson',name:'Sara Wilson',detail:'Escort · actual giver'}]}/>{time()}<Tick label="Outstanding keys received" checked={p.keys} onChange={v=>set('keys',v)}/><Tick label="Outstanding equipment received" checked={p.equipment===true} onChange={v=>set('equipment',v)}/>{observation('Later receipt observation')}</>;
   case 'passengers':return <><p>{r.person} · actual arrival {localDateTimeLabel(r.journey?.arrived)}</p><Tick label="Passenger has returned and is accounted for" checked={p.confirmed} onChange={v=>set('confirmed',v)}/></>;
   case 'medication':return <><Alert tone="warning" title="Authorised medication logistics handoff">Only the permitted source can resolve custody and required clinical records. No medication names, orders or administration controls are copied here.</Alert><p>Journey {r.journey?.id} has an unresolved source obligation.</p><Tick label="Simulate a resolved result from the authorised source" hint="Design fixture only; this changes no medication records." checked={p.confirmed} onChange={v=>set('confirmed',v)}/></>;
   case 'complete':return <><ReviewCard title="Close the passenger journey" icon={CheckCircle2}><ReviewRow label="Journey" value={r.journey?.id||'No actual journey'}/><ReviewRow label="Actual departure" value={localDateTimeLabel(r.journey?.departed)}/><ReviewRow label="Actual return" value={localDateTimeLabel(r.journey?.arrived)}/><ReviewRow label="Passenger return" value={r.journey?.accounted?'Confirmed':'Confirmation still required'}/><ReviewRow label="Medication logistics" value={r.journey?.medication==='outstanding'?'Outstanding source action':'No unresolved source obligation'}/></ReviewCard><p>Open equipment, key or Maintenance exceptions remain assigned after this passenger journey is completed.</p></>;
   case 'cancel':return <><Picker label="Outcome" value={p.outcome} onChange={v=>set('outcome',v)} options={['Requester cancelled','Client chose not to travel','No suitable transport'].map(id=>({id,name:id,detail:'Record an attributable demand outcome'}))}/>{observation('Outcome reason')}<p>Any linked reservation is cancelled through its source. Existing history is retained.</p></>;
   case 'handover':return <><p>Outgoing: <strong>{actorLabel}</strong> · {siteNames[r.site]}</p><Picker label="Incoming worker" value={p.incoming} onChange={v=>set('incoming',v)} options={[{id:'Ben Carter',name:'Ben Carter',detail:'Permitted receiving worker · Aurora House'}]}/><Field label="Items being handed over" value={p.items} onChange={v=>set('items',v)}/>{observation('Handover note')}<p className="muted">Use only when another shift is taking custody. Journey completion does not require a shift handover.</p></>;
   case 'accept':case 'dispute':return <><p>{r.handover?.outgoing} → <strong>{r.handover?.incoming}</strong> · {r.handover?.items}</p>{observation(kind==='dispute'?'What does not match?':'What did you receive?')}</>;
   case 'exception':return <><Field label="Accountable owner" value={p.owner} onChange={v=>set('owner',v)}/>{observation('What needs resolving?')}<p className="muted">The named owner is a synthetic assignment. This does not change a pending, accepted or disputed handover.</p></>;
   case 'resolve':return <><Picker label="Open exception" value={p.exception} onChange={v=>set('exception',v)} options={r.exceptions.filter(e=>e.state==='open').map(e=>({id:e.id,name:e.kind,detail:e.detail}))}/>{observation('Reconciliation evidence')}<p className="muted">Original receipt and handover decisions remain unchanged.</p></>;
   case 'note':return <Field label="Record note" textarea value={p.note} onChange={v=>set('note',v)}/>;
   default:return null;
  }
 };
 const footer=recovered?<Button onClick={()=>onSaved(latestReceipt?.id||uncertain)}>Return to journey</Button>:<><Button variant="outline" onClick={()=>dirty?setDiscard(true):onClose()}>Cancel</Button><Button disabled={planning&&!currentCheck} onClick={submit}>{uncertain?'Retry this operation':actionLabels[kind]}</Button></>;
 const content=<>
  {discard&&<DirtyPrompt onKeep={()=>setDiscard(false)} onDiscard={onClose}/>}
  {uncertain&&!recovered&&<Alert tone="warning" title="Response not confirmed"><p>The return may already be recorded. Recover its original receipt before entering another return.</p><Button variant="outline" onClick={()=>{if(latestReceipt){setRecovered(true);setError('');setDirty(false)}else setError('No receipt found. Retry the same operation.')}}>Recover original receipt</Button></Alert>}
  {recovered&&latestReceipt?<ReviewCard title={latestReceipt.id+' · original saved receipt'} icon={FileCheck}><ReviewRow label="Odometer" value={latestReceipt.odometer+' km'}/><ReviewRow label="Actual return" value={localDateTimeLabel(latestReceipt.time)}/><ReviewRow label="Giver → receiver" value={latestReceipt.giver+' → '+latestReceipt.receiver}/><ReviewRow label="Condition" value={latestReceipt.condition}/><ReviewRow label="Keys / equipment" value={(latestReceipt.keys?'Keys received':'Keys outstanding')+' · '+(latestReceipt.equipment?'Equipment received':'Equipment outstanding')}/></ReviewCard>:body()}
  {error&&<p role="alert" className="form-error" tabIndex={-1}>{error}</p>}{kind==='return'&&p.site!==r.site&&<Button variant="outline" onClick={()=>{try{const result=onCommit({id:op.current+'-exception',record:r.id,type:'exception',version:r.version,payload:{kind:'Unexpected return site',owner:'Mia Chen',reason:'Observed at '+p.time+'; '+siteNames[p.site]+'; '+p.odometer+' km; receiver '+(p.receiver||'not confirmed')+'; '+(p.condition||'condition not provided')+'. Original trip remains open pending source reconciliation.'}});onSaved(result)}catch(e){setError((e as Error).message)}}}>Keep observations as an exception</Button>}</>;
 return inline?<section className="inline-planner-form" aria-label={formTitles[kind]}><div className="form-stack">{content}</div><div className="planner-save"><span>{currentCheck?'Ready for a booking decision':'Unsaved proposal'}</span><div className="button-row">{footer}</div></div></section>:<Modal open onClose={()=>dirty&&!recovered?setDiscard(true):onClose()} title={formTitles[kind]} description={r.id+' · '+r.person+' · Acting as '+actorLabel} footer={footer}>{content}</Modal>;
}

type Upload={id:string;file:File;note:string;state:'staged'|'sending'|'failed'|'saved';attempts:number};
export function EvidenceForm({r,onClose,onCommit}:{r:Transport;onClose:()=>void;onCommit:(c:Command)=>string}){
 const [files,setFiles]=useState<Upload[]>([]),[error,setError]=useState(''),[discard,setDiscard]=useState(false);
 const stage=(input:File[])=>setFiles(old=>[...old,...input.map(file=>({id:crypto.randomUUID(),file,note:'',state:'staged' as const,attempts:0}))]);
 const send=(id:string)=>{const f=files.find(v=>v.id===id);if(!f)return;setFiles(old=>old.map(v=>v.id===id?{...v,state:'sending'}:v));setTimeout(()=>{if(f.attempts===0){setFiles(old=>old.map(v=>v.id===id?{...v,state:'failed',attempts:1}:v));return}try{onCommit({id:'evidence-'+id,record:r.id,type:'evidence',version:r.version,payload:{files:[{name:f.file.name,note:f.note}]}});setFiles(old=>old.map(v=>v.id===id?{...v,state:'saved',attempts:v.attempts+1}:v));setError('')}catch(e){setError((e as Error).message);setFiles(old=>old.map(v=>v.id===id?{...v,state:'failed'}:v))}},450)};
 const dirty=files.some(f=>f.state!=='saved');
 return <Modal open title="Supporting evidence" onClose={()=>dirty?setDiscard(true):onClose()} description={r.id+' · local files only; no transmission or durable storage'} footer={<Button variant="outline" onClick={()=>dirty?setDiscard(true):onClose()}>Return to record</Button>}>
  {discard&&<DirtyPrompt onKeep={()=>setDiscard(false)} onDiscard={onClose}/>}<FileDropzone id="transport-evidence" onFiles={stage} title="Drop supporting files here" hint="Each file has its own simulated result. Original versions are retained."/><Button variant="outline" onClick={()=>stage([new File(['Synthetic observation.'],'condition-note.txt',{type:'text/plain'})])}>Use synthetic sample file</Button>
  {files.map(f=><StagedFileCard key={f.id} file={f.file} onRemove={()=>setFiles(old=>old.filter(v=>v.id!==f.id))}><Field label={'Evidence note '+f.file.name} value={f.note} onChange={note=>setFiles(old=>old.map(v=>v.id===f.id?{...v,note}:v))}/><div className="button-row"><p role="status">{f.state==='sending'?'Simulated submission in progress':f.state==='failed'?'Simulated failure · file retained':f.state==='saved'?'Synthetic evidence receipt saved':'Staged locally'}</p><Button size="sm" variant="outline" disabled={f.state==='sending'||f.state==='saved'} onClick={()=>send(f.id)}>{f.state==='failed'?'Retry file':'Simulate submission'}</Button></div></StagedFileCard>)}
  {r.evidence.length>0&&<div><h3>Saved versions</h3>{r.evidence.map(e=><p key={e.id}>{e.name} · version {e.version} · {e.id}</p>)}</div>}{error&&<p role="alert" className="form-error">{error}</p>}
 </Modal>;
}
