<?php

namespace App\Domain\Governance\Console;

use App\Domain\Governance\Models\ComplianceObligation;
use App\Domain\Governance\Services\GovernanceAuditService;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * Creates `ComplianceObligation` rows 30 days before each donor fund's
 * `next_report_due` date. Idempotent — won't duplicate if one already
 * exists for the same fund + due date.
 *
 * Finance owns the donor fund data; this is purely an oversight surface.
 */
class SyncDonorFundComplianceCommand extends Command
{
    protected $signature = 'governance:sync-donor-fund-compliance
        {--lead-days=30 : Days ahead of report due date to create the obligation}';

    protected $description = 'Generate compliance obligations from upcoming donor fund report deadlines';

    public function handle(): int
    {
        if (! Schema::hasTable('fin_donor_funds')) {
            $this->warn('fin_donor_funds table not present in this environment; skipping.');

            return self::SUCCESS;
        }

        $leadDays = max(1, (int) $this->option('lead-days'));
        $window = now()->addDays($leadDays);

        $funds = DB::table('fin_donor_funds')
            ->whereNotNull('next_report_due')
            ->where('next_report_due', '<=', $window)
            ->where('next_report_due', '>=', now()->startOfDay())
            ->get();

        $created = 0;
        foreach ($funds as $fund) {
            $obligationCode = "DONOR-FUND-{$fund->id}-" . $fund->next_report_due;

            $existing = ComplianceObligation::query()
                ->where('obligation_code', $obligationCode)
                ->first();

            if ($existing) {
                continue;
            }

            try {
                $obligation = ComplianceObligation::create([
                    'framework' => 'funding_moh', // closest match for funder reporting
                    'obligation_code' => $obligationCode,
                    'obligation_title' => sprintf('Donor fund report due: %s', $fund->fund_name ?? "Fund #{$fund->id}"),
                    'description' => sprintf(
                        'Funder reporting deadline for donor fund "%s". Auto-generated by Governance.',
                        $fund->fund_name ?? "fund {$fund->id}",
                    ),
                    'frequency' => 'event_driven',
                    'due_date' => $fund->next_report_due,
                    'next_due_date' => $fund->next_report_due,
                    'reminder_days' => [30, 14, 7, 1],
                    'owner_id' => $fund->owner_id ?? null,
                    'status' => 'not_due',
                    'evidence_required' => true,
                ]);

                GovernanceAuditService::log(
                    'compliance.auto_created',
                    'ComplianceObligation',
                    $obligation->id,
                    [
                        'source' => 'FinDonorFund',
                        'donor_fund_id' => $fund->id,
                        'due_date' => $fund->next_report_due,
                    ],
                );
                $created++;
            } catch (\Throwable $e) {
                $this->error("Failed for fund #{$fund->id}: " . $e->getMessage());
            }
        }

        $this->info("Created {$created} donor-fund compliance obligation(s).");

        return self::SUCCESS;
    }
}
