<?php
// Audit-only fixture/probe host. Ordinary roles, disposable database, no live changes.
declare(strict_types=1);
$root=realpath(__DIR__.'/../../../../../..');
if(!$root || !is_file($root.'/phpunit.xml')) throw new RuntimeException('Repository guard failed');
chdir($root);require $root.'/vendor/autoload.php';
$xml=simplexml_load_file($root.'/phpunit.xml');
foreach($xml->php->env as $entry){$k=(string)$entry['name'];$v=(string)$entry['value'];putenv($k.'='.$v);$_ENV[$k]=$_SERVER[$k]=$v;}
foreach(['DB_DATABASE'=>'oblivion_gov_review2_runtime_20260913','APP_CONFIG_CACHE'=>__DIR__.'/unused-config.php','APP_URL'=>'http://127.0.0.1:8781','MAIL_MAILER'=>'array','QUEUE_CONNECTION'=>'sync'] as $k=>$v){putenv($k.'='.$v);$_ENV[$k]=$_SERVER[$k]=$v;}
use App\Domain\Governance\Models as M;
use App\Domain\Governance\Services as S;
use Illuminate\Support\Facades\DB;
class ReviewHost extends Tests\TestCase {
 use Tests\Support\GovernanceTestHelpers;
 public function prepare():array {
  $this->app=$this->createApplication();$this->seedGovernance();
  Illuminate\Support\Facades\Mail::fake();Illuminate\Support\Facades\Notification::fake();
  $this->withoutVite();
  $actors=[];
  foreach(['chair'=>['board_chair','chair'],'secretary'=>['board_secretary','secretary'],'member'=>['board_member','member'],'finance'=>['board_member','member'],'other'=>['board_member','member'],'ceo'=>['ceo',null],'observer'=>['board_observer','observer']] as $key=>[$role,$seat]) {
   $u=$this->createUserWithRole($role,['name'=>in_array($key,['member','other'])?'Review Alex Morgan':'Review '.ucfirst($key),'email'=>'review-'.$key.'@example.test','password'=>Illuminate\Support\Facades\Hash::make('Review-Only-2026!'),'two_factor_secret'=>null,'two_factor_confirmed_at'=>null,'email_verified_at'=>now()]);
   $bm=$seat?$this->createBoardMember($u,['board_role'=>$seat]):null;
   $actors[$key]=['user_id'=>$u->id,'board_member_id'=>$bm?->id,'email'=>$u->email,'role'=>$role];
  }
  $chair=App\Models\User::findOrFail($actors['chair']['user_id']);$member=App\Models\User::findOrFail($actors['member']['user_id']);
  $meeting=$this->createMeeting($chair,['title'=>'Review September Board','scheduled_at'=>now()->addDays(4)->setTime(22,0),'chair_id'=>$actors['chair']['board_member_id'],'secretary_id'=>$actors['secretary']['board_member_id']]);
  $private=$this->createMeeting($chair,['title'=>'REVIEW PRIVATE personnel matter','meeting_type'=>'executive_session','scheduled_at'=>now()->addDays(2),'chair_id'=>$actors['chair']['board_member_id']]);
  M\MeetingAgendaItem::create(['governance_meeting_id'=>$meeting->id,'order'=>1,'title'=>'REVIEW CONFIDENTIAL agenda','item_type'=>'decision','is_confidential'=>true,'duration_minutes'=>15]);
  $res=$this->createResolution($chair,['title'=>'Review equipment renewal','governance_meeting_id'=>$meeting->id,'deadline'=>now()->addDays(3),'quorum_required'=>true]);
  $hidden=$this->createResolution($chair,['title'=>'REVIEW PRIVATE resolution','governance_meeting_id'=>$private->id,'quorum_required'=>true]);
  $action=$this->createActionItem($chair,$member,['source_type'=>'resolution','source_id'=>$hidden->id,'description'=>'REVIEW PRIVATE assigned action','evidence_required'=>true]);
  for($i=0;$i<40;$i++) $this->createActionItem($chair,$i===39?$member:$chair,['source_type'=>'meeting','source_id'=>$meeting->id,'description'=>'Review ordinary follow-up '.$i,'due_date'=>now()->subDays($i+1)]);
  $this->createActionItem($chair,App\Models\User::find($actors['other']['user_id']),['source_type'=>'meeting','source_id'=>$meeting->id,'description'=>'Review SAME NAME other owner','due_date'=>now()->subDays(50)]);
  for($i=0;$i<12;$i++)$this->createRisk($chair,['title'=>'Review risk '.$i,'likelihood_score'=>5,'impact_score'=>5,'control_effectiveness'=>'weak']);
  $committee=M\BoardCommittee::create(['name'=>'Review finance committee','committee_type'=>'finance','chair_id'=>$actors['finance']['board_member_id'],'is_active'=>true]);
  $committee->members()->attach($actors['finance']['board_member_id'],['role'=>'chair','appointed_at'=>'2026-01-01','term_end'=>'2027-01-01','is_active'=>true]);
  $review=M\PerformanceReview::create(['reviewee_id'=>$actors['ceo']['user_id'],'review_cycle'=>'Review cycle','review_type'=>'annual','period_start'=>'2026-01-01','period_end'=>'2026-12-31','status'=>'board_review','overall_assessment'=>'REVIEW PRIVATE raw appraisal','created_by'=>$chair->id]);
  $minute=M\MeetingMinute::create(['governance_meeting_id'=>$meeting->id,'content_blocks'=>[['heading'=>'Review record','content'=>'Approved synthetic minutes']],'status'=>'approved','drafted_by'=>$chair->id,'drafted_at'=>now(),'version_number'=>1]);
  $obligation=$this->createComplianceObligation($chair,['obligation_title'=>'Review annual assurance','due_date'=>now()->subDay(),'evidence_required'=>false]);
  return ['database'=>config('database.connections.mysql.database'),'pid'=>getmypid(),'actors'=>$actors,'meeting_id'=>$meeting->id,'private_meeting_id'=>$private->id,'resolution_id'=>$res->id,'private_resolution_id'=>$hidden->id,'private_action_id'=>$action->id,'review_id'=>$review->id,'minute_id'=>$minute->id,'obligation_id'=>$obligation->id,'committee_id'=>$committee->id];
 }
 public function paper(App\Models\User $u,array $attributes=[]):M\Resolution{return $this->createResolution($u,$attributes);} public function budget(App\Models\User $u,array $attributes=[]):M\Budget{return $this->createBudget($u,$attributes);} public function action(App\Models\User $u, App\Models\User $assignee,array $attributes=[]):M\ActionItem{return $this->createActionItem($u,$assignee,$attributes);}
}

$host=new ReviewHost('prepare'); $state=$host->prepare();
if(!preg_match('/^oblivion_gov_review2_runtime_20260913_[0-9]+$/',$state['database']??'')) throw new RuntimeException('Disposable database guard failed');
$actors=[]; foreach($state['actors'] as $key=>$actor) $actors[$key]=App\Models\User::findOrFail($actor['user_id']);
$chair=$actors['chair']; $member=$actors['member'];
$normalAction=$host->action($chair,$member,['description'=>'Return review evidence-required action','evidence_required'=>true]);
$state['normal_action_id']=$normalAction->id;
file_put_contents(__DIR__.'/runtime-state.json',json_encode($state,JSON_PRETTY_PRINT));
$out=['checked_at'=>gmdate('c'),'database'=>$state['database'],'cases'=>[]];
function probe(string $name, Closure $fn):void {
 global $out; DB::beginTransaction();
 try {$out['cases'][$name]=$fn();} catch(Throwable $e){$out['cases'][$name]=['exception'=>get_class($e),'message'=>substr($e->getMessage(),0,900)];}
 finally {DB::rollBack();file_put_contents(__DIR__.'/probe-results.json',json_encode($out,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES));echo $name.PHP_EOL;}
}
probe('no_approved_profile_opens',function()use($host,$chair){M\GovernanceVotingProfile::query()->update(['is_active'=>false]);$r=$host->paper($chair);app(S\VotingService::class)->openVoting($r);return ['active_profiles'=>M\GovernanceVotingProfile::active()->count(),'status'=>$r->fresh()->status];});
probe('written_disabled_opens',function()use($host,$chair){M\GovernanceVotingProfile::active()->first()->update(['written_voting_permitted'=>false]);$r=$host->paper($chair);app(S\VotingService::class)->openVoting($r);return ['status'=>$r->fresh()->status];});
probe('written_unanimity_rule_ignored',function()use($host,$chair,$actors){$r=$host->paper($chair,['voting_threshold'=>'simple_majority']);$s=app(S\VotingService::class);$s->openVoting($r);foreach(['chair'=>'for','member'=>'for','finance'=>'abstain'] as $key=>$vote)$s->castVote($r,$actors[$key]->boardMember,$vote);$s->closeVoting($r);return ['written_unanimity_required'=>M\GovernanceVotingProfile::active()->first()->written_unanimity_required,'outcome'=>$r->outcome,'snapshot'=>$r->vote_summary,'electorate_at_open'=>$r->electorate_at_open,'profile_id'=>$r->voting_profile_id];});
probe('unanimous_all_entitled_for',function()use($host,$chair,$actors){$r=$host->paper($chair,['voting_threshold'=>'unanimous']);$s=app(S\VotingService::class);$s->openVoting($r);foreach(['chair','member','finance','other'] as $key)$s->castVote($r,$actors[$key]->boardMember,'for');$s->closeVoting($r);return ['outcome'=>$r->outcome,'electorate_count'=>count($r->electorate_at_open),'for'=>$r->vote_summary['for']];});
probe('new_member_outside_frozen_electorate_can_vote',function()use($host,$chair,$actors){$r=$host->paper($chair);$s=app(S\VotingService::class);$s->openVoting($r);$new=M\BoardMember::create(['user_id'=>$actors['ceo']->id,'board_role'=>'member','term_start'=>today(),'term_end'=>today()->addYear(),'is_active'=>true]);$vote=$s->castVote($r,$new,'for');return ['electorate_at_open'=>array_column($r->electorate_at_open,'board_member_id'),'new_member_id'=>$new->id,'accepted_vote_id'=>$vote->id];});
probe('quorum_profile_ignored',function()use($host,$chair){$p=M\GovernanceVotingProfile::active()->first();$p->update(['quorum_mode'=>'fixed_count','quorum_formula'=>'4']);$r=$host->paper($chair);app(S\VotingService::class)->openVoting($r);return ['configured_mode'=>$p->quorum_mode,'configured_formula'=>$p->quorum_formula,'actual_quorum'=>app(S\VotingService::class)->calculateQuorum(null,$r)];});
probe('draft_resolution_activates_rules',function()use($host,$chair){$r=$host->paper($chair);$p=app(S\GovernanceVotingProfileService::class)->createProfile(['governing_document_reference'=>'Synthetic approved constitution'],$chair);$p=app(S\GovernanceVotingProfileService::class)->activateProfile($p,$chair,$r);return ['is_confirmed'=>$p->isConfirmed()];});
probe('unrelated_carried_resolution_activates_rules',function()use($host,$chair){$r=$host->paper($chair,['title'=>'Approve catering for next board meeting','status'=>'closed','outcome'=>'carried']);$p=app(S\GovernanceVotingProfileService::class)->createProfile(['governing_document_reference'=>'Synthetic approved constitution'],$chair);$p=app(S\GovernanceVotingProfileService::class)->activateProfile($p,$chair,$r);return ['resolution_title'=>$r->title,'is_confirmed'=>$p->isConfirmed()];});
probe('assigned_private_action',function()use($host,$state,$member){$a=M\ActionItem::findOrFail($state['private_action_id']);$s=app(S\GovernanceRecordAccessService::class);$resp=$host->actingAs($member)->get('/governance/actions/'.$a->id);$feed=app(S\GovernanceWorkQuery::class)->queryFeed($member);return ['parent_visible'=>$s->canViewMeeting($member,M\GovernanceMeeting::find($state['private_meeting_id'])),'action_visible'=>$s->canViewActionItem($member,$a),'http_status'=>$resp->status(),'private_title_in_feed'=>str_contains(json_encode($feed),'REVIEW PRIVATE assigned action')];});
probe('attendance_status_still_grants_private_access',function()use($state,$member){$m=M\GovernanceMeeting::findOrFail($state['private_meeting_id']);$s=app(S\ExecutiveMeetingAccessService::class);$before=$s->canViewMeeting($member,$m);$att=M\MeetingAttendance::create(['governance_meeting_id'=>$m->id,'board_member_id'=>$member->boardMember->id,'status'=>'apology','marked_at'=>now(),'marked_by'=>$state['actors']['chair']['user_id']]);$apology=$s->canViewMeeting($member,$m->fresh());$att->update(['status'=>'late']);return ['before'=>$before,'after_apology'=>$apology,'after_late_attendance'=>$s->canViewMeeting($member,$m->fresh())];});
probe('unassigned_executive_committee_grants_access',function()use($state,$member){$c=M\BoardCommittee::create(['name'=>'Unrelated executive committee','committee_type'=>'executive','is_active'=>true]);$c->members()->attach($member->boardMember->id,['role'=>'member','appointed_at'=>'2026-01-01','term_end'=>'2027-01-01','is_active'=>true]);return ['unrelated_committee_id'=>$c->id,'meeting_committee_id'=>M\GovernanceMeeting::find($state['private_meeting_id'])->board_committee_id,'private_access'=>app(S\ExecutiveMeetingAccessService::class)->canViewMeeting($member->fresh(),M\GovernanceMeeting::find($state['private_meeting_id']))];});
probe('ceo_review_detail_and_list',function()use($host,$actors,$state){$detail=$host->actingAs($actors['ceo'])->get('/governance/performance/'.$state['review_id']);$list=$host->actingAs($actors['ceo'])->get('/governance/performance');return ['detail_status'=>$detail->status(),'detail_raw'=>str_contains($detail->getContent(),'REVIEW PRIVATE raw appraisal'),'list_status'=>$list->status(),'list_raw'=>str_contains($list->getContent(),'REVIEW PRIVATE raw appraisal')];});
probe('fabricated_action_evidence_in_testing',function()use($host,$state,$member){$a=M\ActionItem::findOrFail($state['normal_action_id']);$response=$host->actingAs($member)->post('/governance/actions/'.$a->id.'/complete',['completion_notes'=>'Claimed work evidence','evidence_files'=>['does-not-exist.pdf'],'expected_version'=>$a->version_number]);return ['http_status'=>$response->status(),'status'=>$a->fresh()->status,'stored'=>$a->fresh()->evidence_attachments];});
probe('empty_evidence_record_in_local_environment',function()use($host,$state,$member){$a=M\ActionItem::findOrFail($state['normal_action_id']);$previous=app()->environment();app()->instance('env','local');try{$response=$host->actingAs($member)->post('/governance/actions/'.$a->id.'/complete',['completion_notes'=>'Claimed work evidence','evidence_files'=>[[]],'expected_version'=>$a->version_number]);return ['tested_environment'=>app()->environment(),'http_status'=>$response->status(),'status'=>$a->fresh()->status,'stored'=>$a->fresh()->evidence_attachments,'receipt'=>$a->fresh()->completion_receipt];}finally{app()->instance('env',$previous);}});
probe('stale_action_models_overwrite',function()use($state){$a=M\ActionItem::findOrFail($state['normal_action_id']);$b=M\ActionItem::findOrFail($a->id);$v=(int)($a->version_number??1);$a->updateProgress(20,'First writer',$v);$b->updateProgress(80,'Stale second writer',$v);return ['expected_version'=>$v,'final_version'=>$a->fresh()->version_number,'progress'=>$a->fresh()->progress_pct,'notes'=>$a->fresh()->progress_notes];});
probe('completed_action_reopens',function()use($state,$member){$a=M\ActionItem::findOrFail($state['normal_action_id']);$a->markComplete($member->id,'Complete synthetic work',['test.pdf']);$a->updateProgress(20,'Late stale progress');return $a->fresh()->only(['status','progress_pct','completion_receipt']);});
probe('stale_minutes_approval_from_ui_payload',function()use($host,$actors,$state){$minute=M\MeetingMinute::findOrFail($state['minute_id']);$minute->update(['status'=>'reviewed','version_number'=>1]);$service=app(S\MeetingMinuteService::class);$meeting=M\GovernanceMeeting::findOrFail($state['meeting_id']);$service->updateMinutes($meeting,[['heading'=>'Unseen change','content'=>'The reviewer has not seen version two']],$actors['secretary'],1);$response=$host->actingAs($actors['chair'])->post('/governance/meetings/'.$meeting->id.'/minutes/approve',[]);return ['reviewer_saw_version'=>1,'http_status'=>$response->status(),'approved_version'=>$minute->fresh()->version_number,'status'=>$minute->fresh()->status];});
probe('stale_minutes_explicit_version_rejected',function()use($host,$actors,$state){$minute=M\MeetingMinute::findOrFail($state['minute_id']);$minute->update(['status'=>'reviewed','version_number'=>2]);$response=$host->actingAs($actors['chair'])->postJson('/governance/meetings/'.$state['meeting_id'].'/minutes/approve',['expected_version'=>1]);return ['http_status'=>$response->status(),'status'=>$minute->fresh()->status];});
probe('unrelated_same_amount_resolution_approves_budget',function()use($host,$actors){$u=$actors['chair'];$b=$host->budget($u);$line=M\BudgetLineItem::create(['budget_id'=>$b->id,'category'=>'operations','description'=>'Equipment funding','budget_amount'=>100000,'forecast_amount'=>100000,'actual_amount'=>0]);$r=$host->paper($u,['status'=>'closed','outcome'=>'carried','title'=>'Catering for another event','cost_impact'=>['amount'=>6000]]);$adj=M\BudgetAdjustment::create(['budget_id'=>$b->id,'budget_line_item_id'=>$line->id,'adjustment_type'=>'increase','amount'=>6000,'reason'=>'Equipment increase','proposed_by'=>$actors['secretary']->id,'proposed_at'=>now(),'status'=>'submitted','threshold_applies'=>true]);$result=app(S\GovernanceNestedMutationService::class)->approveBudgetAdjustment($u,$b,$adj,$r->id);return ['resolution_title'=>$r->title,'adjustment_reason'=>$adj->reason,'adjustment_status'=>$result->status,'budget_total'=>$b->fresh()->total_budget];});
probe('pack_confidential_agenda_and_motion',function()use($state,$chair,$member){Illuminate\Support\Facades\Auth::setUser($chair);$meeting=M\GovernanceMeeting::findOrFail($state['meeting_id']);$snapshot=(object)['snapshot_data'=>['widgets'=>[]]];$content=(new ReflectionMethod(S\BoardPackBuilderService::class,'buildPackContent'))->invoke(app(S\BoardPackBuilderService::class),$meeting,$snapshot);return ['builder_role'=>'board_chair','member_can_view_meeting'=>app(S\ExecutiveMeetingAccessService::class)->canViewMeeting($member,$meeting),'confidential_title_in_content'=>str_contains(json_encode($content),'REVIEW CONFIDENTIAL agenda'),'paper_keys'=>array_keys($content['resolutions']['items'][0]??[])];});
probe('private_decision_widget',function()use($member,$state){Illuminate\Support\Facades\Auth::setUser($member);M\Resolution::findOrFail($state['private_resolution_id'])->update(['status'=>'open']);$data=app(S\DashboardAggregatorService::class)->getDecisionsRequired();return ['private_title_present'=>str_contains(json_encode($data),'REVIEW PRIVATE resolution')];});
probe('policy_work_feed',function()use($member){$feed=app(S\GovernanceWorkQuery::class)->queryFeed($member);return ['availability'=>$feed['availability'],'totals'=>$feed['totals']];});
probe('calendar_implemented_and_cancelled',function()use($host,$chair,$member){$result=[];foreach(['implemented','cancelled'] as $status){$r=$host->paper($chair,['status'=>$status,'deadline'=>now()->subDay()->setTime(14,30)]);$items=app(S\GovernanceCalendarQuery::class)->queryItems(now()->subDays(2),now()->addDay(),$member,['decisions']);$result[$status]=collect($items['events'])->firstWhere('id','governance:decision:'.$r->id);}return $result;});
probe('role_http_smoke',function()use($host,$actors,$state){$checks=[];foreach(['member','chair','secretary','finance','ceo','observer'] as $key){foreach(['/governance/dashboard','/governance/my-work','/governance/meetings/'.$state['private_meeting_id'],'/governance/performance/'.$state['review_id']] as $path){$response=$host->actingAs($actors[$key])->get($path);$checks[$key][$path]=$response->status();}}return $checks;});
echo 'REVIEW_READY '.json_encode($state).PHP_EOL;
while(!is_file(__DIR__.'/stop-runtime.flag'))sleep(1);

