<?php

namespace App\Domain\It\Services;

/** V2 wire rules shared with the approved Diagram Studio contract. */
final class ItKnowledgeDiagramContract
{
    public const LIMITS = [
        'diagrams' => 12,
        'pages' => 12,
        'layersPerPage' => 16,
        'nodesPerDiagram' => 80,
        'edgesPerDiagram' => 160,
        'groupsPerDiagram' => 80,
        'pointsPerNode' => 512,
        'pointsPerDiagram' => 4096,
        'propertiesPerNode' => 16,
        'diagramBytes' => 262144,
        'collectionBytes' => 2097152,
        'titleLength' => 160,
        'pageNameLength' => 160,
        'subtitleLength' => 240,
        'layerNameLength' => 80,
        'groupNameLength' => 80,
        'nodeTextLength' => 2000,
        'edgeLabelLength' => 80,
        'propertyKeyLength' => 64,
        'propertyValueLength' => 512,
        'scaleLength' => 24,
        'pageDimensionMin' => 100,
        'pageDimensionMax' => 10000,
        'positionMin' => -10000,
        'positionMax' => 10000,
        'nodeDimensionMin' => 1,
        'nodeDimensionMax' => 10000,
        'rotationMin' => -360,
        'rotationMax' => 360,
        'fontSizeMin' => 6,
        'fontSizeMax' => 144,
        'strokeWidthMin' => 0,
        'strokeWidthMax' => 20,
        'gridSizeMin' => 1,
        'gridSizeMax' => 200,
        'bendMin' => -10000,
        'bendMax' => 10000,
    ];

    public const ENUMS = [
        'legacyShape' => [
            0 => 'rectangle',
            1 => 'ellipse',
            2 => 'diamond',
        ],
        'shape' => [
            0 => 'rectangle',
            1 => 'ellipse',
            2 => 'diamond',
            3 => 'process',
            4 => 'decision',
            5 => 'terminator',
            6 => 'document',
            7 => 'data',
            8 => 'database',
            9 => 'subprocess',
            10 => 'manual',
            11 => 'delay',
            12 => 'offpage',
            13 => 'note',
            14 => 'text',
            15 => 'lane',
            16 => 'container',
            17 => 'phase',
            18 => 'list',
            19 => 'event',
            20 => 'intermediate',
            21 => 'end',
            22 => 'task',
            23 => 'gateway',
            24 => 'parallel',
            25 => 'pool',
            26 => 'class',
            27 => 'interface',
            28 => 'actor',
            29 => 'usecase',
            30 => 'component',
            31 => 'package',
            32 => 'lifeline',
            33 => 'state',
            34 => 'entity',
            35 => 'server',
            36 => 'router',
            37 => 'switch',
            38 => 'firewall',
            39 => 'cloud',
            40 => 'laptop',
            41 => 'wifi',
            42 => 'rack',
            43 => 'person',
            44 => 'team',
            45 => 'position',
            46 => 'room',
            47 => 'wall',
            48 => 'door',
            49 => 'window',
            50 => 'desk',
            51 => 'chair',
            52 => 'stairs',
            53 => 'exit',
            54 => 'tree',
            55 => 'dimension',
            56 => 'resistor',
            57 => 'ground',
            58 => 'pump',
            59 => 'valve',
            60 => 'tank',
            61 => 'motor',
            62 => 'duct',
            63 => 'milestone',
            64 => 'taskbar',
            65 => 'funnel',
            66 => 'browser',
            67 => 'phone',
            68 => 'ink',
            69 => 'image',
        ],
        'containerShape' => [
            0 => 'container',
            1 => 'lane',
            2 => 'pool',
            3 => 'list',
        ],
        'route' => [
            0 => 'straight',
            1 => 'orthogonal',
            2 => 'curved',
        ],
        'port' => [
            0 => 'auto',
            1 => 'top',
            2 => 'right',
            3 => 'bottom',
            4 => 'left',
        ],
        'arrow' => [
            0 => 'none',
            1 => 'triangle',
            2 => 'open',
            3 => 'diamond',
            4 => 'circle',
        ],
        'dash' => [
            0 => 'solid',
            1 => 'dashed',
            2 => 'dotted',
        ],
        'font' => [
            0 => 'sans',
            1 => 'serif',
            2 => 'mono',
        ],
        'align' => [
            0 => 'left',
            1 => 'center',
            2 => 'right',
        ],
        'paper' => [
            0 => 'a3',
            1 => 'a4',
            2 => 'a5',
            3 => 'letter',
            4 => 'legal',
            5 => 'custom',
        ],
        'orientation' => [
            0 => 'landscape',
            1 => 'portrait',
        ],
        'imageMime' => [
            0 => 'image/png',
            1 => 'image/jpeg',
        ],
    ];

    public const OBJECTS = [
        'diagramV2' => [
            'schema_version' => [
                'kind' => 'enum',
                'values' => [
                    0 => 2,
                ],
            ],
            'id' => [
                'kind' => 'string',
                'min' => 36,
                'max' => 36,
                'pattern' => '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$',
            ],
            'title' => [
                'kind' => 'string',
                'min' => 1,
                'max' => 160,
                'nonblank' => true,
            ],
            'pages' => [
                'kind' => 'array',
                'items' => [
                    'kind' => 'object',
                    'name' => 'page',
                ],
                'min' => 1,
                'max' => 12,
            ],
        ],
        'page' => [
            'id' => [
                'kind' => 'string',
                'min' => 36,
                'max' => 36,
                'pattern' => '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$',
            ],
            'name' => [
                'kind' => 'string',
                'min' => 1,
                'max' => 160,
                'nonblank' => true,
            ],
            'subtitle' => [
                'kind' => 'string',
                'min' => 0,
                'max' => 240,
                'nullable' => true,
            ],
            'width' => [
                'kind' => 'number',
                'min' => 100,
                'max' => 10000,
                'integer' => false,
            ],
            'height' => [
                'kind' => 'number',
                'min' => 100,
                'max' => 10000,
                'integer' => false,
            ],
            'orientation' => [
                'kind' => 'enum',
                'values' => [
                    0 => 'landscape',
                    1 => 'portrait',
                ],
            ],
            'paper' => [
                'kind' => 'enum',
                'values' => [
                    0 => 'a3',
                    1 => 'a4',
                    2 => 'a5',
                    3 => 'letter',
                    4 => 'legal',
                    5 => 'custom',
                ],
            ],
            'scale' => [
                'kind' => 'string',
                'min' => 3,
                'max' => 24,
                'pattern' => '^[1-9][0-9]{0,10}:[1-9][0-9]{0,10}$',
            ],
            'background' => [
                'kind' => 'string',
                'min' => 7,
                'max' => 7,
                'pattern' => '^#[0-9a-fA-F]{6}$',
            ],
            'grid' => [
                'kind' => 'object',
                'name' => 'grid',
            ],
            'layers' => [
                'kind' => 'array',
                'items' => [
                    'kind' => 'object',
                    'name' => 'layer',
                ],
                'min' => 1,
                'max' => 16,
            ],
            'groups' => [
                'kind' => 'array',
                'items' => [
                    'kind' => 'object',
                    'name' => 'group',
                ],
                'min' => 0,
                'max' => 80,
            ],
            'nodes' => [
                'kind' => 'array',
                'items' => [
                    'kind' => 'object',
                    'name' => 'node',
                ],
                'min' => 0,
                'max' => 80,
            ],
            'edges' => [
                'kind' => 'array',
                'items' => [
                    'kind' => 'object',
                    'name' => 'edge',
                ],
                'min' => 0,
                'max' => 160,
            ],
        ],
        'grid' => [
            'enabled' => [
                'kind' => 'boolean',
            ],
            'size' => [
                'kind' => 'number',
                'min' => 1,
                'max' => 200,
                'integer' => false,
            ],
            'snap' => [
                'kind' => 'boolean',
            ],
        ],
        'layer' => [
            'id' => [
                'kind' => 'string',
                'min' => 36,
                'max' => 36,
                'pattern' => '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$',
            ],
            'name' => [
                'kind' => 'string',
                'min' => 1,
                'max' => 80,
                'nonblank' => true,
            ],
            'visible' => [
                'kind' => 'boolean',
            ],
            'locked' => [
                'kind' => 'boolean',
            ],
            'print' => [
                'kind' => 'boolean',
            ],
        ],
        'group' => [
            'id' => [
                'kind' => 'string',
                'min' => 36,
                'max' => 36,
                'pattern' => '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$',
            ],
            'name' => [
                'kind' => 'string',
                'min' => 1,
                'max' => 80,
                'nonblank' => true,
            ],
            'parentId' => [
                'kind' => 'string',
                'min' => 36,
                'max' => 36,
                'pattern' => '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$',
                'nullable' => true,
            ],
        ],
        'node' => [
            'id' => [
                'kind' => 'string',
                'min' => 36,
                'max' => 36,
                'pattern' => '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$',
            ],
            'type' => [
                'kind' => 'enum',
                'values' => [
                    0 => 'rectangle',
                    1 => 'ellipse',
                    2 => 'diamond',
                    3 => 'process',
                    4 => 'decision',
                    5 => 'terminator',
                    6 => 'document',
                    7 => 'data',
                    8 => 'database',
                    9 => 'subprocess',
                    10 => 'manual',
                    11 => 'delay',
                    12 => 'offpage',
                    13 => 'note',
                    14 => 'text',
                    15 => 'lane',
                    16 => 'container',
                    17 => 'phase',
                    18 => 'list',
                    19 => 'event',
                    20 => 'intermediate',
                    21 => 'end',
                    22 => 'task',
                    23 => 'gateway',
                    24 => 'parallel',
                    25 => 'pool',
                    26 => 'class',
                    27 => 'interface',
                    28 => 'actor',
                    29 => 'usecase',
                    30 => 'component',
                    31 => 'package',
                    32 => 'lifeline',
                    33 => 'state',
                    34 => 'entity',
                    35 => 'server',
                    36 => 'router',
                    37 => 'switch',
                    38 => 'firewall',
                    39 => 'cloud',
                    40 => 'laptop',
                    41 => 'wifi',
                    42 => 'rack',
                    43 => 'person',
                    44 => 'team',
                    45 => 'position',
                    46 => 'room',
                    47 => 'wall',
                    48 => 'door',
                    49 => 'window',
                    50 => 'desk',
                    51 => 'chair',
                    52 => 'stairs',
                    53 => 'exit',
                    54 => 'tree',
                    55 => 'dimension',
                    56 => 'resistor',
                    57 => 'ground',
                    58 => 'pump',
                    59 => 'valve',
                    60 => 'tank',
                    61 => 'motor',
                    62 => 'duct',
                    63 => 'milestone',
                    64 => 'taskbar',
                    65 => 'funnel',
                    66 => 'browser',
                    67 => 'phone',
                    68 => 'ink',
                    69 => 'image',
                ],
            ],
            'text' => [
                'kind' => 'string',
                'min' => 0,
                'max' => 2000,
                'nullable' => true,
            ],
            'x' => [
                'kind' => 'number',
                'min' => -10000,
                'max' => 10000,
                'integer' => false,
            ],
            'y' => [
                'kind' => 'number',
                'min' => -10000,
                'max' => 10000,
                'integer' => false,
            ],
            'w' => [
                'kind' => 'number',
                'min' => 1,
                'max' => 10000,
                'integer' => false,
            ],
            'h' => [
                'kind' => 'number',
                'min' => 1,
                'max' => 10000,
                'integer' => false,
            ],
            'rotation' => [
                'kind' => 'number',
                'min' => -360,
                'max' => 360,
                'integer' => false,
            ],
            'layerId' => [
                'kind' => 'string',
                'min' => 36,
                'max' => 36,
                'pattern' => '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$',
            ],
            'parentId' => [
                'kind' => 'string',
                'min' => 36,
                'max' => 36,
                'pattern' => '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$',
                'nullable' => true,
            ],
            'locked' => [
                'kind' => 'boolean',
            ],
            'style' => [
                'kind' => 'object',
                'name' => 'nodeStyle',
            ],
            'properties' => [
                'kind' => 'array',
                'items' => [
                    'kind' => 'object',
                    'name' => 'property',
                ],
                'min' => 0,
                'max' => 16,
            ],
            'dataGraphic' => [
                'kind' => 'string',
                'min' => 1,
                'max' => 64,
                'pattern' => '^[A-Za-z][A-Za-z0-9 _.-]{0,63}$',
                'nullable' => true,
            ],
            'points' => [
                'kind' => 'array',
                'items' => [
                    'kind' => 'object',
                    'name' => 'point',
                ],
                'min' => 0,
                'max' => 512,
            ],
            'imageFileId' => [
                'kind' => 'number',
                'min' => 1,
                'max' => 9007199254740991,
                'integer' => true,
                'nullable' => true,
            ],
        ],
        'nodeStyle' => [
            'fill' => [
                'kind' => 'string',
                'min' => 4,
                'max' => 7,
                'pattern' => '^(?:#[0-9a-fA-F]{6}|none)$',
            ],
            'stroke' => [
                'kind' => 'string',
                'min' => 4,
                'max' => 7,
                'pattern' => '^(?:#[0-9a-fA-F]{6}|none)$',
            ],
            'color' => [
                'kind' => 'string',
                'min' => 7,
                'max' => 7,
                'pattern' => '^#[0-9a-fA-F]{6}$',
            ],
            'fontSize' => [
                'kind' => 'number',
                'min' => 6,
                'max' => 144,
                'integer' => false,
            ],
            'font' => [
                'kind' => 'enum',
                'values' => [
                    0 => 'sans',
                    1 => 'serif',
                    2 => 'mono',
                ],
            ],
            'bold' => [
                'kind' => 'boolean',
            ],
            'italic' => [
                'kind' => 'boolean',
            ],
            'underline' => [
                'kind' => 'boolean',
            ],
            'align' => [
                'kind' => 'enum',
                'values' => [
                    0 => 'left',
                    1 => 'center',
                    2 => 'right',
                ],
            ],
            'strokeWidth' => [
                'kind' => 'number',
                'min' => 0,
                'max' => 20,
                'integer' => false,
            ],
            'dash' => [
                'kind' => 'enum',
                'values' => [
                    0 => 'solid',
                    1 => 'dashed',
                    2 => 'dotted',
                ],
            ],
            'opacity' => [
                'kind' => 'number',
                'min' => 0,
                'max' => 1,
                'integer' => false,
            ],
        ],
        'property' => [
            'key' => [
                'kind' => 'string',
                'min' => 1,
                'max' => 64,
                'pattern' => '^[A-Za-z][A-Za-z0-9 _.-]{0,63}$',
            ],
            'value' => [
                'kind' => 'string',
                'min' => 0,
                'max' => 512,
                'nullable' => true,
            ],
        ],
        'point' => [
            'x' => [
                'kind' => 'number',
                'min' => 0,
                'max' => 1,
                'integer' => false,
            ],
            'y' => [
                'kind' => 'number',
                'min' => 0,
                'max' => 1,
                'integer' => false,
            ],
        ],
        'edge' => [
            'id' => [
                'kind' => 'string',
                'min' => 36,
                'max' => 36,
                'pattern' => '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$',
            ],
            'from' => [
                'kind' => 'string',
                'min' => 36,
                'max' => 36,
                'pattern' => '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$',
            ],
            'to' => [
                'kind' => 'string',
                'min' => 36,
                'max' => 36,
                'pattern' => '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$',
            ],
            'label' => [
                'kind' => 'string',
                'min' => 0,
                'max' => 80,
                'nullable' => true,
            ],
            'layerId' => [
                'kind' => 'string',
                'min' => 36,
                'max' => 36,
                'pattern' => '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$',
            ],
            'route' => [
                'kind' => 'enum',
                'values' => [
                    0 => 'straight',
                    1 => 'orthogonal',
                    2 => 'curved',
                ],
            ],
            'fromPort' => [
                'kind' => 'enum',
                'values' => [
                    0 => 'auto',
                    1 => 'top',
                    2 => 'right',
                    3 => 'bottom',
                    4 => 'left',
                ],
            ],
            'toPort' => [
                'kind' => 'enum',
                'values' => [
                    0 => 'auto',
                    1 => 'top',
                    2 => 'right',
                    3 => 'bottom',
                    4 => 'left',
                ],
            ],
            'arrow' => [
                'kind' => 'enum',
                'values' => [
                    0 => 'none',
                    1 => 'triangle',
                    2 => 'open',
                    3 => 'diamond',
                    4 => 'circle',
                ],
            ],
            'startArrow' => [
                'kind' => 'enum',
                'values' => [
                    0 => 'none',
                    1 => 'triangle',
                    2 => 'open',
                    3 => 'diamond',
                    4 => 'circle',
                ],
            ],
            'stroke' => [
                'kind' => 'string',
                'min' => 7,
                'max' => 7,
                'pattern' => '^#[0-9a-fA-F]{6}$',
            ],
            'width' => [
                'kind' => 'number',
                'min' => 0,
                'max' => 20,
                'integer' => false,
            ],
            'dash' => [
                'kind' => 'enum',
                'values' => [
                    0 => 'solid',
                    1 => 'dashed',
                    2 => 'dotted',
                ],
            ],
            'bend' => [
                'kind' => 'number',
                'min' => -10000,
                'max' => 10000,
                'integer' => false,
            ],
            'labelPos' => [
                'kind' => 'number',
                'min' => 0,
                'max' => 1,
                'integer' => false,
            ],
        ],
        'legacy' => [
            'id' => [
                'kind' => 'string',
                'min' => 36,
                'max' => 36,
                'pattern' => '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$',
            ],
            'title' => [
                'kind' => 'string',
                'min' => 1,
                'max' => 160,
                'nonblank' => true,
            ],
            'nodes' => [
                'kind' => 'array',
                'items' => [
                    'kind' => 'object',
                    'name' => 'legacyNode',
                ],
                'min' => 0,
                'max' => 80,
            ],
            'edges' => [
                'kind' => 'array',
                'items' => [
                    'kind' => 'object',
                    'name' => 'legacyEdge',
                ],
                'min' => 0,
                'max' => 160,
            ],
        ],
        'legacyNode' => [
            'id' => [
                'kind' => 'string',
                'min' => 36,
                'max' => 36,
                'pattern' => '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$',
            ],
            'shape' => [
                'kind' => 'enum',
                'values' => [
                    0 => 'rectangle',
                    1 => 'ellipse',
                    2 => 'diamond',
                ],
            ],
            'text' => [
                'kind' => 'string',
                'min' => 0,
                'max' => 160,
                'nullable' => false,
            ],
            'x' => [
                'kind' => 'number',
                'min' => 0,
                'max' => 840,
                'integer' => false,
            ],
            'y' => [
                'kind' => 'number',
                'min' => 0,
                'max' => 520,
                'integer' => false,
            ],
        ],
        'legacyEdge' => [
            'id' => [
                'kind' => 'string',
                'min' => 36,
                'max' => 36,
                'pattern' => '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$',
            ],
            'from' => [
                'kind' => 'string',
                'min' => 36,
                'max' => 36,
                'pattern' => '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$',
            ],
            'to' => [
                'kind' => 'string',
                'min' => 36,
                'max' => 36,
                'pattern' => '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$',
            ],
            'label' => [
                'kind' => 'string',
                'min' => 0,
                'max' => 80,
                'nullable' => true,
            ],
        ],
    ];

    public const FORBIDDEN_TEXT_PATTERN = '[\\x00-\\x08\\x0B\\x0C\\x0E-\\x1F\\x7F]';

    public const PERCENT_PATTERN = '^(?:0|[1-9][0-9]?|100)(?:\\.[0-9]{1,6})?$';
}
