import { Head, Link, router } from '@inertiajs/react';
import { PageProps } from '@/types';
import AppLayout from '@/layouts/app-layout';
import { PageHero, PageLayout } from '@/components/page';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { EmptyState } from '@/components/ui/empty-state';
import { FolderOpen, Calendar, ChevronLeft, ChevronRight, ExternalLink } from 'lucide-react';
import { statusColors } from '@/lib/status-colors';

interface Pack {
  id: number;
  meeting_id: number;
  meeting: {
    id: number;
    title: string;
    scheduled_at: string;
    meeting_type: string;
  } | null;
  generatedBy: { id: number; name: string } | null;
  distributed_at: string | null;
  created_at: string;
  updated_at: string;
}

interface Props extends PageProps {
  packs: {
    data: Pack[];
    current_page: number;
    last_page: number;
    total: number;
  };
  filters: {
    status: string | null;
  };
  summary: {
    total: number;
    distributed: number;
    draft: number;
  };
}

export default function PacksIndex({ auth, packs, filters, summary }: Props) {
  const setStatus = (status: string | null) => {
    router.get('/governance/packs', { status }, { preserveState: true, preserveScroll: true, replace: true });
  };

  return (
    <AppLayout
      user={auth.user}
      breadcrumbs={[
        { title: 'Governance', href: '/governance/dashboard' },
        { title: 'Board Packs', href: '/governance/packs' },
      ]}
    >
      <Head title="Board Packs" />

      <PageLayout
        hero={
          <PageHero
            icon={FolderOpen}
            category="governance"
            title="Board Packs"
            description="Generated and distributed board packs across all meetings."
            stats={[
              { label: 'Total', value: summary.total },
              { label: 'Distributed', value: summary.distributed },
              { label: 'Draft', value: summary.draft },
            ]}
          />
        }
      >
        <div className="mb-4 flex flex-wrap items-center gap-2">
          <Button variant={!filters.status ? 'default' : 'outline'} size="sm" onClick={() => setStatus(null)}>
            All
          </Button>
          <Button variant={filters.status === 'distributed' ? 'default' : 'outline'} size="sm" onClick={() => setStatus('distributed')}>
            Distributed
          </Button>
          <Button variant={filters.status === 'draft' ? 'default' : 'outline'} size="sm" onClick={() => setStatus('draft')}>
            Draft
          </Button>
        </div>

        <Card>
          <CardHeader className="pb-3">
            <CardTitle>Packs</CardTitle>
          </CardHeader>
          <CardContent className="space-y-2">
            {packs.data.length === 0 ? (
              <EmptyState
                icon={FolderOpen}
                title="No board packs yet"
                description="Board packs are generated from a scheduled meeting's data once an agenda exists."
              />
            ) : (
              packs.data.map((pack) => (
                <Link
                  key={pack.id}
                  href={`/governance/packs/${pack.id}`}
                  className="flex flex-wrap items-center justify-between gap-3 rounded-lg border p-3 transition-colors hover:bg-muted/30"
                >
                  <div className="space-y-1">
                    <div className="flex flex-wrap items-center gap-2">
                      <Badge className={pack.distributed_at ? statusColors.approved ?? '' : statusColors.draft ?? ''}>
                        {pack.distributed_at ? 'Distributed' : 'Draft'}
                      </Badge>
                      {pack.meeting && (
                        <Badge variant="outline" className="gap-1">
                          <Calendar className="h-3 w-3" />
                          {pack.meeting.meeting_type}
                        </Badge>
                      )}
                    </div>
                    <p className="font-medium">
                      {pack.meeting?.title ?? 'Untitled meeting'}
                    </p>
                    <p className="text-xs text-muted-foreground">
                      {pack.meeting?.scheduled_at && (<>Scheduled {pack.meeting.scheduled_at} · </>)}
                      Generated by {pack.generatedBy?.name ?? 'system'} on {pack.created_at}
                      {pack.distributed_at && <> · Distributed {pack.distributed_at}</>}
                    </p>
                  </div>
                  <ExternalLink className="h-4 w-4 text-muted-foreground" />
                </Link>
              ))
            )}
          </CardContent>
        </Card>

        {packs.last_page > 1 && (
          <div className="mt-4 flex items-center justify-between">
            <p className="text-sm text-muted-foreground">
              Page {packs.current_page} of {packs.last_page} ({packs.total} total)
            </p>
            <div className="flex items-center gap-2">
              <Button
                variant="outline"
                size="sm"
                disabled={packs.current_page <= 1}
                onClick={() => router.get('/governance/packs', { ...filters, page: packs.current_page - 1 }, { preserveState: true })}
              >
                <ChevronLeft className="mr-1 h-4 w-4" /> Previous
              </Button>
              <Button
                variant="outline"
                size="sm"
                disabled={packs.current_page >= packs.last_page}
                onClick={() => router.get('/governance/packs', { ...filters, page: packs.current_page + 1 }, { preserveState: true })}
              >
                Next <ChevronRight className="ml-1 h-4 w-4" />
              </Button>
            </div>
          </div>
        )}
      </PageLayout>
    </AppLayout>
  );
}
