import type { DiagramShapeKind } from './contract';
export const STENCIL_GROUPS = [
    {
        name: 'Flowchart',
        desc: 'Processes, decisions & documents',
        shapes: [
            ['process', 'Process'],
            ['decision', 'Decision'],
            ['terminator', 'Start / end'],
            ['document', 'Document'],
            ['data', 'Input / output'],
            ['database', 'Database'],
            ['subprocess', 'Subprocess'],
            ['manual', 'Manual operation'],
            ['delay', 'Delay'],
            ['offpage', 'Off-page reference'],
            ['note', 'Callout'],
            ['text', 'Text'],
        ],
    },
    {
        name: 'Swimlanes & containers',
        desc: 'Responsibility, phases & groups',
        shapes: [
            ['lane', 'Horizontal lane'],
            ['container', 'Container'],
            ['phase', 'Phase'],
            ['list', 'List'],
        ],
    },
    {
        name: 'BPMN',
        desc: 'Events, activities & gateways',
        shapes: [
            ['event', 'Start event'],
            ['intermediate', 'Intermediate event'],
            ['end', 'End event'],
            ['task', 'Task'],
            ['subprocess', 'Subprocess'],
            ['gateway', 'Exclusive gateway'],
            ['parallel', 'Parallel gateway'],
            ['document', 'Data object'],
            ['database', 'Data store'],
            ['pool', 'Pool / lane'],
        ],
    },
    {
        name: 'UML & database',
        desc: 'Software structure & behaviour',
        shapes: [
            ['class', 'Class'],
            ['interface', 'Interface'],
            ['actor', 'Actor'],
            ['usecase', 'Use case'],
            ['component', 'Component'],
            ['package', 'Package'],
            ['lifeline', 'Lifeline'],
            ['state', 'State'],
            ['entity', 'Entity'],
            ['database', 'Database'],
        ],
    },
    {
        name: 'Network & cloud',
        desc: 'Topology, racks & infrastructure',
        shapes: [
            ['server', 'Server'],
            ['router', 'Router'],
            ['switch', 'Network switch'],
            ['firewall', 'Firewall'],
            ['cloud', 'Cloud'],
            ['laptop', 'Workstation'],
            ['wifi', 'Wireless access point'],
            ['rack', 'Equipment rack'],
            ['database', 'Storage'],
        ],
    },
    {
        name: 'Organisation',
        desc: 'People, teams & reporting lines',
        shapes: [
            ['person', 'Person'],
            ['team', 'Team'],
            ['position', 'Vacant position'],
            ['container', 'Department'],
        ],
    },
    {
        name: 'Floor & site',
        desc: 'Spaces, access & furnishings',
        shapes: [
            ['room', 'Room'],
            ['wall', 'Wall'],
            ['door', 'Door'],
            ['window', 'Window'],
            ['desk', 'Desk'],
            ['chair', 'Chair'],
            ['stairs', 'Stairs'],
            ['exit', 'Exit'],
            ['tree', 'Tree'],
            ['dimension', 'Dimension'],
        ],
    },
    {
        name: 'Engineering',
        desc: 'Representative symbols · no CAD solver',
        shapes: [
            ['resistor', 'Resistor'],
            ['ground', 'Ground'],
            ['pump', 'Pump'],
            ['valve', 'Valve'],
            ['tank', 'Tank'],
            ['motor', 'Motor'],
            ['duct', 'Duct / pipe'],
        ],
    },
    {
        name: 'Business & planning',
        desc: 'Timelines, analysis & wireframes',
        shapes: [
            ['milestone', 'Milestone'],
            ['taskbar', 'Gantt task'],
            ['process', 'Value stream process'],
            ['cloud', 'Mind-map idea'],
            ['funnel', 'Funnel'],
            ['browser', 'Web wireframe'],
            ['phone', 'Mobile wireframe'],
            ['note', 'Annotation'],
        ],
    },
] as const satisfies readonly {
    name: string;
    desc: string;
    shapes: readonly (readonly [DiagramShapeKind, string])[];
}[];
