import React, { useState, type ComponentProps } from 'react';
import { Landmark, FileCheck2, ReceiptText, Link2, Check, ChevronsUpDown } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { Command, CommandInput, CommandItem, CommandList, CommandGroup, CommandEmpty } from '@/components/ui/command';
import { WizardShell, WizardStepPane, WizardSuccessPane } from '@/components/wizard/shell';
import { ModalFrame } from './modal-ui';
export function FinanceRequestFrame({kind,stage,onStage,discard,pct,...props}:ComponentProps<typeof ModalFrame>&{kind:string;stage:'edit'|'review';onStage:(v:'edit'|'review')=>void;discard:boolean;pct:number}){
 if(kind!=='request'||discard)return <ModalFrame {...props} width={discard?480:props.width}/>;
 return <WizardShell open title={props.title} description={props.description} onClose={props.onClose} railIcon={Landmark} railTitle="Finance review" railSub="AS-104 · Transfer hoist" steps={[{key:'details',label:'Review details',blurb:'Type, source and reason',icon:ReceiptText},{key:'review',label:'Check request',blurb:'Confirm the Finance handoff',icon:FileCheck2}]} stepIndex={stage==='edit'?0:1} onStepClick={i=>onStage(i===0?'edit':'review')} pct={pct} pctLabel="Request details" maxWidth="min(92vw, 900px)" footerStart={<><Button variant="outline" onClick={props.onClose}>Cancel</Button>{stage==='review'&&<Button variant="ghost" onClick={()=>onStage('edit')}>Back</Button>}</>} footerEnd={props.actions} success={props.success?<WizardSuccessPane title="Sample request saved" blurb={props.success} actions={<Button onClick={props.onClose}>Return to asset</Button>}/>:undefined}><WizardStepPane>{props.children}</WizardStepPane></WizardShell>;
}
export function FinanceSourcePicker({records,value,onChange}:{records:Array<{id:string;title:string}>;value:string;onChange:(v:string)=>void}){
 const [open,setOpen]=useState(false);const current=records.find(r=>r.id===value);
 return <div className="field"><label id="finance-source-label">Source record <span className="text-status-critical">*</span></label><Popover open={open} onOpenChange={setOpen}><PopoverTrigger asChild><Button variant="outline" role="combobox" aria-labelledby="finance-source-label" aria-expanded={open} className="picker-trigger">{current?`${current.id} · ${current.title}`:'Choose a Finance record'}<ChevronsUpDown size={15}/></Button></PopoverTrigger><PopoverContent className="w-[var(--radix-popover-trigger-width)] p-0" align="start"><Command><CommandInput placeholder="Search Finance reference or name…" aria-label="Search source records"/><CommandList><CommandEmpty>No permitted matching records.</CommandEmpty><CommandGroup heading="Linked Finance records">{records.map(r=><CommandItem key={r.id} value={r.id+' '+r.title} onSelect={()=>{onChange(r.id);setOpen(false);}}><Check size={14} className={r.id===value?'opacity-100':'opacity-0'}/><span>{r.title}<small className="block text-muted-foreground">{r.id} · Kōwhai House</small></span></CommandItem>)}</CommandGroup></CommandList></Command></PopoverContent></Popover><small>Complete permitted sample list · Existing canonical records only.</small></div>;
}
const types=[['Fixed asset update','Correct recognition or asset details',Landmark],['Supplier invoice review','Check a bill and its evidence',ReceiptText],['Cost allocation correction','Review the assigned cost centre',Link2],['Purchase approval','Request an expenditure decision',FileCheck2]] as const;
export function FinanceTypeTiles({value,onChange}:{value:string;onChange:(v:string)=>void}){return <fieldset className="qr-settings"><legend>Review type <span className="text-status-critical">*</span></legend><div className="finance-type-tiles">{types.map(([name,detail,Icon])=><button type="button" key={name} aria-pressed={value===name} onClick={()=>onChange(name)} className={'choice '+(value===name?'selected':'')}><Icon size={18}/><strong>{name}</strong><small>{detail}</small></button>)}</div></fieldset>;}
