[program:oblivion-monitoring-snmp-traps]
command=php /var/www/oblivionfindings/artisan monitoring:listen-snmp-traps
directory=/var/www/oblivionfindings
user=www-data
numprocs=1
autostart=true
autorestart=true
startsecs=3
stopasgroup=true
killasgroup=true
stopwaitsecs=30
redirect_stderr=true
stdout_logfile=/var/log/oblivion/monitoring-snmp-traps.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10

[program:oblivion-monitoring-syslog]
command=php /var/www/oblivionfindings/artisan monitoring:listen-syslog
directory=/var/www/oblivionfindings
user=www-data
numprocs=1
autostart=true
autorestart=true
startsecs=3
stopasgroup=true
killasgroup=true
stopwaitsecs=30
redirect_stderr=true
stdout_logfile=/var/log/oblivion/monitoring-syslog.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10

[program:oblivion-monitoring-flow]
command=php /var/www/oblivionfindings/artisan monitoring:listen-flow
directory=/var/www/oblivionfindings
user=www-data
numprocs=1
autostart=true
autorestart=true
startsecs=3
stopasgroup=true
killasgroup=true
stopwaitsecs=30
redirect_stderr=true
stdout_logfile=/var/log/oblivion/monitoring-flow.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10
