import React,{useEffect,useState} from 'react';
import {BarChart,Bar,CartesianGrid,XAxis,YAxis,Tooltip,ResponsiveContainer,PieChart,Pie,Cell} from 'recharts';
import {ArrowRight,BarChart3,CalendarDays,CheckCircle2,Clock,FileText,Flag,KeyRound,LayoutDashboard,Route,Users} from 'lucide-react';
import {formatDateOnly} from '@/lib/datetime';
import {displayTime} from '@/components/fleet-assets/maintenance/time-picker';
import {Button,Card,LinkButton,StatusBadge,Alert} from './ui';
import {SectionTabs} from './section-tabs';
import {stageCounts,scheduleCounts,attentionItems,nextDepartures,overviewReport} from './overview-data';
import {fleet,NOW,TODAY,siteNames,overdue,type Transport,type LoadState} from './domain';
import type {Report} from './reports';

type Props={rows:Transport[];day:string;site:string;query:string;load:LoadState;onQuery:(s:string)=>void;onRefresh:()=>void;onDrill:(view:string,filter:string)=>void;onOpen:(r:Transport,kind:'requests'|'bookings'|'journeys'|'returns')=>void;onCalendar:()=>void;onOutings:()=>void;onExport:(r:Report)=>void};
export function TransportOverview({rows,day,site,query,load,onQuery,onRefresh,onDrill,onOpen,onCalendar,onOutings,onExport}:Props){
 const [section,setSection]=useState('summary'),[hour,setHour]=useState('all');
 useEffect(()=>setHour('all'),[day,site,query]);
 const stages=stageCounts(rows),schedule=scheduleCounts(rows),attention=attentionItems(rows),departures=nextDepartures(rows),late=rows.filter(overdue),unfinished=rows.filter(r=>r.journey?.arrived&&r.journey.state!=='completed');
 const movements=rows.filter(r=>!['cancelled','unfulfilled'].includes(r.state)&&(hour==='all'||Number(r.start.slice(11,13))===Number(hour)||Number(r.end.slice(11,13))===Number(hour))).sort((a,b)=>a.start.localeCompare(b.start));
 const period=day==='all'?'All selected dates':formatDateOnly(day),scope=[siteNames[site]||'All permitted sites',period,'Search: '+(query||'all'),'Example time: 28 Sep 2026, 10:35 am'];
 const caption=day==='all'?'All dates combined by local hour':period+' · Pacific/Auckland';
 const open=(r:Transport)=>onOpen(r,r.journey?'journeys':r.booking?'bookings':'requests');
 const recordRows=(items:Transport[])=>items.length?<div className="ov-record-list">{items.map(r=><button key={r.id} onClick={()=>open(r)}><span className="ov-record-time">{displayTime(r.start.slice(11))}<small>{day==='all'?formatDateOnly(r.start.slice(0,10)):'Departure'}</small></span><span className="ov-record-person"><strong>{r.person}</strong><small>{r.pickup} → {r.destination}</small><small>{r.booking?fleet[r.booking.vehicle].name+' · '+r.booking.driver:'Vehicle and driver not yet confirmed'}</small></span><StatusBadge variant={r.journey?'info':r.booking?.state==='approved'?'success':'warning'}>{r.journey?.state==='completed'?'Completed':r.journey?.arrived?'Returned':r.journey?'On the road':r.booking?.state==='approved'?'Confirmed':r.booking?.state==='pending'?'Decision needed':'Plan needed'}</StatusBadge><ArrowRight/></button>)}</div>:<p className="ov-empty">No matching departures in this scope.</p>;
 return <div className="page-stack transport-overview">
  <div className="section-heading" data-testid="workspace-heading"><div><h2 className="text-section-title">Transport at a glance</h2><p>{period} · {rows.length} matching requests · {siteNames[site]||'all permitted sites'}</p></div><div className="button-row">{query&&<Button variant="ghost" onClick={()=>onQuery('')}>Clear search</Button>}<Button variant="outline" onClick={onOutings}><Users className="size-4"/>Outings</Button><Button variant="outline" disabled={!rows.length||load!=='ready'} onClick={()=>onExport(overviewReport(rows,scope))}><FileText className="size-4"/>Export summary PDF</Button></div></div>
  <SectionTabs id="overview-sections" label="Overview sections" value={section} onChange={setSection} tabs={[{key:'summary',label:'At a glance',icon:LayoutDashboard},{key:'attention',label:'Needs attention',icon:Flag,count:attention.length},{key:'departures',label:'Departure board',icon:Route,count:departures.length}]}/>
  {load==='stale'&&<Alert tone="warning" title="Overview is showing an earlier result">Graphs and counts are from the last permitted source response.<Button variant="outline" onClick={onRefresh}>Refresh source</Button></Alert>}
  {!rows.length?<div className="empty-panel"><Route/><h3>No transport matches this scope</h3><p>Change the site, date or search. No activity is inferred from an empty result.</p></div>:<>
  {section==='summary'&&<>
   <div className="ov-priorities" aria-label="Priority summary">
    <button className={late.length?'ov-priority warning':'ov-priority'} onClick={()=>onDrill('returns','overdue')}><Clock/><span><strong>{late.length} overdue {late.length===1?'return':'returns'}</strong><small>{late.length?'Confirm where the trip stands':'No overdue return in this scope'}</small></span><ArrowRight/></button>
    <button className="ov-priority" onClick={()=>onDrill('requests','decision')}><Flag/><span><strong>{rows.filter(r=>r.booking?.state==='pending').length} booking {rows.filter(r=>r.booking?.state==='pending').length===1?'decision':'decisions'}</strong><small>Review proposed vehicle and team</small></span><ArrowRight/></button>
    <button className="ov-priority" onClick={()=>onDrill('journeys','returned')}><CheckCircle2/><span><strong>{unfinished.length} {unfinished.length===1?'journey':'journeys'} to finish</strong><small>Returned · final passenger steps due</small></span><ArrowRight/></button>
   </div>
   <div className="ov-charts">
    <Card title="Where each request stands" icon={Route} className="ov-stage-card"><p className="ov-chart-caption">Every request appears once. Select a stage to open its queue.</p><div className="ov-stage-body"><div className="ov-donut" role="img" aria-label={stages.map(s=>s.label+': '+s.value).join('. ')}><ResponsiveContainer width="100%" height="100%" initialDimension={{width:300,height:200}}><PieChart><Pie data={stages.filter(s=>s.value)} dataKey="value" nameKey="label" cx="50%" cy="50%" innerRadius="69%" outerRadius="92%" paddingAngle={2} stroke="var(--card)" isAnimationActive={false}>{stages.filter(s=>s.value).map(s=><Cell key={s.key} fill={s.color}/>)}</Pie></PieChart></ResponsiveContainer><div className="ov-donut-label"><strong>{rows.length}</strong><span>requests</span></div></div><div className="ov-stage-legend">{stages.map(s=><button key={s.key} onClick={()=>onDrill(s.view,s.filter)} aria-label={s.label+': '+s.value+' requests'}><span className="ov-dot" style={{background:s.color}}/><span>{s.label}</span><strong>{s.value}</strong><ArrowRight/></button>)}</div></div><p className="ov-chart-note"><KeyRound/>A completed journey can still have a vehicle return or item to resolve.</p></Card>
    <Card title="Departures & returns by time" icon={BarChart3} className="ov-time-card" action={<LinkButton onClick={onCalendar}>Calendar</LinkButton>}><p className="ov-chart-caption">{caption}</p><div className="ov-chart-legend"><span><i style={{background:'var(--chart-1)'}}/>Scheduled departures</span><span><i style={{background:'var(--chart-2)'}}/>Expected returns</span></div><div className="ov-time-chart" role="img" aria-label="Scheduled departures and expected returns by hour. Exact values and records are available under View the numbers."><ResponsiveContainer width="100%" height="100%" initialDimension={{width:300,height:200}}><BarChart data={schedule} margin={{top:12,right:12,bottom:0,left:-24}} accessibilityLayer><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="3 4"/><XAxis dataKey="label" tick={{fontSize:11,fill:'var(--muted-foreground)'}} axisLine={false} tickLine={false}/><YAxis allowDecimals={false} tick={{fontSize:11,fill:'var(--muted-foreground)'}} axisLine={false} tickLine={false}/><Tooltip cursor={{fill:'var(--muted)'}} contentStyle={{background:'var(--card)',border:'1px solid var(--border)',borderRadius:9,color:'var(--foreground)',fontSize:12}}/><Bar name="Scheduled departures" dataKey="departures" fill="var(--chart-1)" radius={[4,4,0,0]} maxBarSize={24} isAnimationActive={false} onClick={(data:any)=>setHour(String(data.hour))}/><Bar name="Expected returns" dataKey="returns" fill="var(--chart-2)" radius={[4,4,0,0]} maxBarSize={24} isAnimationActive={false} onClick={(data:any)=>setHour(String(data.hour))}/></BarChart></ResponsiveContainer></div><p className="ov-chart-note">Planned times include unallocated requests. Cancelled requests are excluded.</p><details className="ov-chart-data"><summary>View the numbers and matching trips</summary><div className="ov-hour-values">{schedule.filter(h=>h.departures||h.returns).map(h=><button key={h.hour} onClick={()=>setHour(String(h.hour))}>{displayTime(h.label)}<span>{h.departures} depart · {h.returns} return</span></button>)}</div></details></Card>
   </div>
   {hour!=='all'&&<Card title={'Trips scheduled around '+displayTime(String(Number(hour)).padStart(2,'0')+':00')} icon={Clock} action={<Button variant="ghost" onClick={()=>setHour('all')}>Close time selection</Button>}>{recordRows(movements)}</Card>}
  </>}
  {(section==='summary'||section==='attention')&&<Card title={section==='summary'?'Act next':'Work needing attention'} icon={Flag} action={section==='summary'?<LinkButton onClick={()=>setSection('attention')}>All {attention.length} actions</LinkButton>:undefined}><p className="ov-chart-caption">Outstanding return work first, then decisions and planning. One request may need more than one action.</p><div className="ov-attention-list">{(section==='summary'?attention.slice(0,4):attention).map(i=><button key={i.id} onClick={()=>onOpen(i.r,i.kind)}><span className={'ov-action-icon '+(i.priority===0?'warning':'')}><span>{i.priority===0?<Clock/>:i.kind==='returns'?<KeyRound/>:i.kind==='journeys'?<Route/>:<Flag/>}</span></span><span><strong>{i.title}</strong><small>{i.r.person} · {i.detail}</small></span><span className="ov-owner"><small>Next person</small><strong>{i.owner}</strong></span><ArrowRight/></button>)}{!attention.length&&<p className="ov-empty">No outstanding actions in this scope.</p>}</div></Card>}
  {section==='departures'&&<Card title="Departure board" icon={Route} action={<LinkButton onClick={onCalendar}>Open calendar</LinkButton>}><p className="ov-chart-caption">Requests that have not departed, ordered by scheduled time. Confirmed and unconfirmed plans are labelled separately.</p>{recordRows(departures)}</Card>}
  <p className="ov-source-note">{load==='stale'?'Earlier result':'Example snapshot'} · 28 Sep 2026, {displayTime(NOW.slice(11))} · Charts follow your site, date and search. Source records stay separate.</p>
  </>}
 </div>;
}
