<?php

// P09's additive domain fragment; the shared workspace remains the builder.
$field = fn ($label, $type = 'text', $unit = 'number') => ['label' => $label, 'type' => $type, 'unit' => $unit, 'description' => 'Recorded or canonically projected value; missing remains unknown.'];
$base = ['reference' => $field('Reference'), 'date' => $field('NZ day', 'date'), 'person' => $field('Person'), 'site' => $field('House')];
$source = fn ($label, $fields, $permission = null, $note = '') => ['label' => $label, 'domain' => 'medication', 'fields' => $fields, 'permission' => $permission, 'note' => $note];

return ['sources' => [
    'dose_slots' => $source('Scheduled dose slots', $base + ['medicine' => $field('Medicine'), 'status' => $field('Dose state'), 'due_at' => $field('Due at'), 'window_ends_at' => $field('Window ends'), 'recorded_at' => $field('Recorded at'), 'late' => $field('Recorded late', 'number', 'count'), 'away' => $field('Away', 'number', 'count')], note: 'Canonical dose slots by NZ day. Away is separate and outside the adherence denominator. Controlled details require controlled-medicine access.'),
    'medication_rounds' => $source('Rounds', ['reference' => $base['reference'], 'date' => $base['date'], 'site' => $base['site'], 'round' => $field('Round'), 'status' => $field('Result'), 'due' => $field('Owed doses', 'number', 'count'), 'recorded' => $field('Recorded doses', 'number', 'count'), 'away' => $field('Away doses', 'number', 'count')], note: 'Results derive from the projected doses and each round’s actual window. No result applies before its window ends.'),
    'prn_doses' => $source('As-needed doses', $base + ['medicine' => $field('Medicine'), 'recorded_at' => $field('Given at'), 'status' => $field('Recorded result'), 'effect_recorded' => $field('Effect recorded', 'number', 'count')], note: 'One row per effective given as-needed dose and its canonical effect check. Controlled medicine names and dose references are concealed without controlled-medicine access.'),
    'medication_errors' => $source('Medication errors — facts', $base + ['error_type' => $field('Error type'), 'reached' => $field('Reached the person'), 'harm' => $field('Recorded harm'), 'status' => $field('Stage'), 'confirmed_sac' => $field('Confirmed SAC', 'number'), 'in_error' => $field('Recorded in error', 'number', 'count')], note: 'Recorded facts only. Narrative accounts are excluded. In-error accounts are explicitly marked and excluded from default totals.'),
    'medication_stock' => $source('Stock', ['medicine' => $field('Medicine'), 'site' => $base['site'], 'unit' => $field('Unit'), 'on_hand' => $field('On hand', 'number'), 'reorder_level' => $field('Reorder level', 'number'), 'expiry_date' => $field('Expiry', 'date'), 'value_on_hand' => $field('Value on hand', 'number', 'NZD')], note: 'Current stock. Finance sees medicine/house totals only. Controlled lines require controlled-medicine access. Unknown cost stays unknown.'),
    'controlled_register' => $source('Controlled register', $base + ['medicine' => $field('Medicine'), 'movement' => $field('Movement'), 'quantity' => $field('Quantity', 'number'), 'balance' => $field('Balance', 'number'), 'witnessed' => $field('Witnessed', 'number', 'count')], 'medications.controlled.view', 'Append-only register evidence. Controlled-medicine access is required.'),
]];
