import React,{useState,useRef} from 'react';
import {ArrowRight,CalendarDays,KeyRound,MapPin,Route,Search,ShieldCheck} from 'lucide-react';
import {DateTimeField} from '@/components/fleet-assets/maintenance/date-time-field';
import {formatDateOnly} from '@/lib/datetime';
import {displayTime} from '@/components/fleet-assets/maintenance/time-picker';
import {Field} from './forms';
import {Alert,Button,Card,Fact,Input,Modal,Picker,StatusBadge,Tick} from './ui';
import {actors,fleet,siteNames,NOW,permitted,type Role,type Transport,type Store,type Command,type LoadState} from './domain';
import {currentKey,keyRef,keyPlaces,placeLabel,plannedKeys,type KeyPlan} from './custody';
import {type Report} from './reports';
export const matchText=(text:string,query:string)=>{const clean=(v:string)=>v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();return clean(query).trim().split(/\s+/).every(word=>clean(text).includes(word))};
export function KeyPanel({store,r,role,authority,onPlan,onStore,onSite}:{store:Store;r:Transport;role:Role;authority:boolean;onPlan:()=>void;onStore:()=>void;onSite:()=>void}){
 const current=currentKey(store,r),plan=plannedKeys(r),place=keyPlaces.find(v=>v.id===plan.pickup);
 return <Card title="Keys · location and collection" icon={KeyRound}><div className="key-identity"><strong>{keyRef(r)}</strong><StatusBadge variant={current?.kind==='stored'?'success':current?'info':'warning'}>{current?.kind==='stored'?'In secure storage':current?'With a worker':'Location unconfirmed'}</StatusBadge></div><div className="key-summary-grid"><div><span className="eyebrow">Current vehicle key custody</span><h3>{current?.kind==='stored'?placeLabel(current.place):current?.holder||'Needs confirmation'}</h3><p>{current?current.kind==='stored'?'Placement confirmed by '+current.actor:'Last recorded holder · '+placeLabel(current.place):'Ask the owning site to confirm the storage point.'}</p>{current&&<small>{displayTime(current.time.slice(11))} · {current.id}{current.record&&current.record!==r.id?' · from another linked journey':''}</small>}</div><div><span className="eyebrow">Plan for this booking</span><p><strong>Collect:</strong> {placeLabel(plan.pickup)}</p><p><strong>Return to:</strong> {placeLabel(plan.dropoff)}</p><p><strong>Who moves it:</strong> {plan.mover||'Not assigned'}</p><p><strong>Receive:</strong> {plan.receiver||'Not assigned'}</p><p>{plan.method}{plan.deliveryWorker?' · '+plan.deliveryWorker:''}</p></div></div><p className="key-instructions">{plan.note||place?.instructions||'Collection and return arrangements need confirmation.'}</p><div className="button-row"><Button variant="outline" onClick={onSite}><MapPin className="size-4"/>View site key point</Button>{role==='allocator'&&r.booking&&!r.checkout&&<Button variant="outline" onClick={onPlan}>Plan key collection</Button>}{role==='receiver'&&authority&&current?.kind==='received'&&current.holder===actors[role].name&&current.record===r.id&&<Button onClick={onStore}>Confirm keys in storage</Button>}</div><p className="muted">The booking plan and a return receipt do not confirm placement in a key safe. Current custody follows the latest vehicle key event.</p></Card>;
}
export function KeyDialog({r,store,kind,role,onClose,onCommit,onSaved}:{r:Transport;store:Store;kind:'keyplan'|'keymove';role:Role;onClose:()=>void;onCommit:(c:Command)=>string;onSaved:(v:string)=>void}){
 const current=currentKey(store,r),[plan,setPlan]=useState<KeyPlan>(plannedKeys(r)),[place,setPlace]=useState(plannedKeys(r).dropoff),[time,setTime]=useState(current&&current.time>NOW?current.time:NOW),[note,setNote]=useState(''),[confirmed,setConfirmed]=useState(false),[dirty,setDirty]=useState(false),[discard,setDiscard]=useState(false),[error,setError]=useState('');const id=useRef(crypto.randomUUID()),version=useRef(r.version),expected=useRef(current?.id);
 const set=(k:keyof KeyPlan,v:string)=>{setPlan(p=>({...p,[k]:v}));setDirty(true);setError('')};
 const save=()=>{try{const result=onCommit({id:id.current,record:r.id,type:kind,version:version.current,payload:kind==='keyplan'?plan:{place,time,note,confirmed,expectedKey:expected.current}});onSaved(result)}catch(e){setError((e as Error).message)}};
 const places=keyPlaces.filter(v=>actors[role].sites.includes(v.site)&&v.site===r.site).map(v=>({id:v.id,name:v.name,detail:siteNames[v.site]+' · '+v.room,unavailable:v.id==='kowhai-office'?'Exact point not configured':undefined}));
 return <Modal open title={kind==='keyplan'?'Plan key collection & return':'Confirm physical key storage'} description={keyRef(r)+' · '+r.id+' · '+r.person} onClose={()=>dirty?setDiscard(true):onClose()} footer={<><Button variant="outline" onClick={()=>dirty?setDiscard(true):onClose()}>Cancel</Button><Button onClick={save}>{kind==='keyplan'?'Save key plan':'Record storage confirmation'}</Button></>}>
  {discard&&<Alert tone="warning" title="Discard these changes?"><div className="button-row"><Button variant="outline" onClick={()=>setDiscard(false)}>Keep editing</Button><Button onClick={onClose}>Discard changes</Button></div></Alert>}
  {kind==='keyplan'?<><Alert title="Plan the handoff">Saving an arrangement does not move the keys or confirm physical receipt.</Alert><Picker label="Collect keys from" value={plan.pickup} onChange={v=>set('pickup',v)} options={places}/><Picker label="Return keys to" value={plan.dropoff} onChange={v=>set('dropoff',v)} options={places.filter(v=>v.id==='aurora-office')}/><div className="form-grid"><Picker label="Responsible driver" value={plan.mover} onChange={v=>set('mover',v)} options={r.booking?[{id:r.booking.driver,name:r.booking.driver,detail:'Assigned to this booking'}]:[]}/><Picker label="Receiving worker" value={plan.receiver} onChange={v=>set('receiver',v)} options={[{id:'Ben Carter',name:'Ben Carter',detail:'Permitted Aurora receiving worker'}]}/></div><Picker label="How the keys reach the driver" value={plan.method} onChange={v=>set('method',v)} options={['Driver collects and returns','Named worker delivers to driver'].map(id=>({id,name:id,detail:id.startsWith('Named')?'Record the meeting place and arrangement':'Collect and return at the approved key point'}))}/>{plan.method==='Named worker delivers to driver'&&<Picker label="Worker delivering the keys" value={plan.deliveryWorker||''} onChange={v=>set('deliveryWorker',v)} options={[{id:'Ben Carter',name:'Ben Carter',detail:'Approved Aurora key handoff worker'}]}/>}<Field label="Collection / delivery arrangement" textarea value={plan.note} onChange={v=>set('note',v)}/></>:<><Alert title="A separate physical observation">{current?.holder} currently holds these keys. Confirm the actual secure storage point and observation time.</Alert><Picker label="Actual storage point" value={place} onChange={v=>{setPlace(v);setDirty(true)}} options={places.filter(v=>v.id==='aurora-office')}/><DateTimeField id="key-storage-time" label="Placed in storage at" value={time} onChange={v=>{setTime(v);setDirty(true)}}/><Tick label="I physically placed these keys in this secure storage point" checked={confirmed} onChange={v=>{setConfirmed(v);setDirty(true)}}/><Field label="Storage observation" textarea value={note} onChange={v=>{setNote(v);setDirty(true)}}/></>}{error&&<p role="alert" className="form-error">{error}</p>}
 </Modal>;
}
export type VehicleLeg={id:string;journey:string;booking:string;start:string;end:string;from:string;to:string;distance:number};
// Explicit synthetic cross-source links. New/manual journeys have no assumed tracker match.
const vehicleLegFixtures:Record<string,[string,string,string,number][]>= {'J-609':[['VT-901','07:00','07:24',38],['VT-902','07:48','08:10',37]],'J-607':[['VT-899','06:02','06:35',35]]};
export function linkedVehicleLegs(r:Transport):VehicleLeg[]{return (vehicleLegFixtures[r.journey?.id||'']||[]).map(([id,start,end,distance],i)=>({id,journey:r.journey!.id,booking:r.booking!.id,start:r.start.slice(0,10)+'T'+start,end:r.start.slice(0,10)+'T'+end,from:i?r.destination:r.pickup,to:i?r.pickup:r.destination,distance}))}
export function VehicleHistory({store,r,role,load,onJourney,onExport}:{store:Store;r:Transport;role:Role;load:LoadState;onJourney:(r:Transport)=>void;onExport:(report:Report)=>void}){
 const [query,setQuery]=useState(''),[onlyLinked,setOnlyLinked]=useState(true);
 const permittedSource=load==='ready'&&['allocator','approver','driver'].includes(role)&&permitted(r,role,load);
 if(!permittedSource)return <Alert title="Vehicle trip history needs separate access">This source requires vehicle-trip permission and approved-site access. Passenger-journey access alone does not grant it.</Alert>;
 const rows=store.records.filter(v=>permitted(v,role,load)&&v.booking?.vehicle===r.booking?.vehicle&&(!onlyLinked||v.id===r.id)).flatMap(v=>linkedVehicleLegs(v).map(leg=>({...leg,r:v}))).filter(v=>matchText([v.id,v.booking,v.journey,v.from,v.to,v.r.booking?.driver].join(' '),query));
 return <div className="form-stack"><Alert title="Vehicle movements linked to transport">A passenger journey may span several vehicle trips. These are separate records. Manual journeys can exist without a tracker match.</Alert><div className="history-toolbar"><Input aria-label="Search vehicle trip history" placeholder="Search trip, booking, place or driver" value={query} onChange={e=>setQuery(e.target.value)}/><Button variant="outline" disabled={!rows.length} onClick={()=>onExport({title:'Vehicle trip history',scope:[r.booking?fleet[r.booking.vehicle].name:'',onlyLinked?'Linked to '+r.journey?.id:'All permitted example trips for this vehicle','Search: '+(query||'all')],sections:[{title:'Recorded vehicle movements',columns:['Vehicle trip / booking','Times','Route','Distance'],rows:rows.map(v=>[v.id+' / '+v.booking,displayTime(v.start.slice(11))+' – '+displayTime(v.end.slice(11)),v.from+' → '+v.to,v.distance+' km'])}],count:rows.length})}>Export PDF</Button></div><Tick label="Only trips linked to this passenger journey" checked={onlyLinked} onChange={setOnlyLinked}/>{rows.length?<div className="vehicle-trip-list">{rows.map(v=><div key={v.id}><Route/><div><strong>{v.id} · {displayTime(v.start.slice(11))}–{displayTime(v.end.slice(11))}</strong><p>{v.from} → {v.to}</p><small>{v.distance} km · {v.booking} · {v.r.booking?.driver}</small></div><Button variant="outline" onClick={()=>onJourney(v.r)}>Open {v.journey}</Button></div>)}</div>:<Alert title={query?'No vehicle trips match this search':'No matched vehicle trip yet'}>{query?'Change or clear the search.':'The passenger journey remains valid. A vehicle-trip match must come from the vehicle source; it is not inferred from the booking.'}</Alert>}<p className="muted">Vehicle trip history owns tracking, driver attribution and its exports. Personal/restricted movement and clinical detail are excluded from this example.</p></div>;
}
