import React,{useState} from 'react';
import {Download,FileText} from 'lucide-react';
import {Button,Modal,Alert} from './ui';
import {fleet,siteNames,requestLabel,journeyLabel,bookingLabel,type Transport,type Store} from './domain';
import {returnLabel} from './workflow';
import {currentKey,keyRef,placeLabel,plannedKeys} from './custody';
import {formatDateOnly} from '@/lib/datetime';
import {displayTime} from '@/components/fleet-assets/maintenance/time-picker';
export type Report={title:string;scope:string[];count:number;sections:{title:string;columns?:string[];rows?:string[][];paragraphs?:string[]}[]};
const time=(s:string)=>formatDateOnly(s.slice(0,10))+' '+displayTime(s.slice(11));
export function transportReport(rows:Transport[],view:string,scope:string[],store:Store):Report{return {title:view==='returns'?'Returns & handovers':view==='journeys'?'Passenger journeys':'Transport requests',scope,count:rows.length,sections:[{title:'Matching records',columns:['Record / passenger','Vehicle / window','State / next record'],rows:rows.map(r=>[r.id+' · '+r.person+(r.journey?' / '+r.journey.id:''),(r.booking?fleet[r.booking.vehicle].name:'Not allocated')+'\n'+time(r.start)+' – '+displayTime(r.end.slice(11)),(view==='returns'?(currentKey(store,r)?.record===r.id&&currentKey(store,r)?.kind==='received'&&returnLabel(r)==='Return complete'?'Keys to store':returnLabel(r)):view==='journeys'?journeyLabel(r):requestLabel(r))+'\n'+(r.booking?.id||'No booking')])}]}}
export function recordReport(r:Transport,kind:string,store:Store):Report{
 const key=currentKey(store,r),plan=plannedKeys(r);
 return {title:r.person+' · '+(kind==='returns'?'return record':kind==='journeys'?'passenger journey':'transport record'),count:1,scope:[r.id,...(r.booking?[r.booking.id]:[]),...(r.journey?[r.journey.id]:[]),siteNames[r.site],'Status: '+(kind==='requests'?requestLabel(r):kind==='bookings'&&r.booking?bookingLabel(r.booking):kind==='returns'?(key?.record===r.id&&key.kind==='received'&&returnLabel(r)==='Return complete'?'Keys to store':returnLabel(r)):journeyLabel(r))],sections:[{title:'Transport summary',columns:['Detail','Recorded value'],rows:[['Route',r.pickup+' → '+r.destination],['Planned',time(r.start)+' – '+displayTime(r.end.slice(11))],['Actual departure',r.journey?time(r.journey.departed):'Not recorded'],['Actual return',r.journey?.arrived?time(r.journey.arrived):'Not recorded'],['Vehicle / driver',r.booking?fleet[r.booking.vehicle].name+' / '+r.booking.driver:'Not allocated'],['Passenger return',r.journey?.accounted?'Confirmed':'Not confirmed'],['Medication handoff',r.journey?.medication==='outstanding'?'Authorised source action outstanding':'No unresolved source obligation shown']]},{title:'Vehicle return observations',columns:['Receipt / time','Actual parties','Observations'],rows:r.receipts.map(v=>[v.id+'\n'+time(v.time),v.giver+' → '+v.receiver,v.odometer+' km; '+v.fuel+' fuel / charge; '+(v.keys?'keys received':'keys missing')+'; '+(v.equipment?'equipment received':'equipment missing')+'. '+v.condition])},{title:'Keys and site arrangement',paragraphs:[keyRef(r)+' · current vehicle custody: '+(key?key.kind==='stored'?placeLabel(key.place):key.holder:'Not confirmed'), 'Collect: '+placeLabel(plan.pickup)+'. Return to: '+placeLabel(plan.dropoff), 'Responsible driver: '+(plan.mover||'Not assigned')+'. Receiving worker: '+(plan.receiver||'Not assigned')+'. '+plan.method+(plan.deliveryWorker?' · '+plan.deliveryWorker:''),plan.note||'No additional arrangement recorded.','Current key custody can be newer than this historical journey. A receipt alone does not confirm key-safe placement.']},{title:'History',columns:['Time / source','Actor / event','Detail'],rows:r.events.map(e=>[time(e.time)+'\n'+e.source,e.actor+'\n'+e.title,e.detail])}]};
}
export function ExportDialog({report,onClose}:{report:Report;onClose:()=>void}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false);
 const download=async()=>{setBusy(true);setError('');try{const response=await fetch('/preview-report.pdf',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(report)});if(!response.ok)throw Error('The PDF could not be generated. Please retry.');const blob=await response.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=report.title.replace(/[^a-z0-9]+/gi,'-').replace(/-$/,'').toLowerCase()+'.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);setDone(true)}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 return <Modal open title="Export PDF" description="Review the selected scope before downloading." onClose={onClose} footer={<><Button variant="outline" onClick={onClose}>Close</Button><Button disabled={busy} onClick={download}><Download className="size-4"/>{busy?'Preparing PDF…':done?'Download again':'Download PDF'}</Button></>}><div className="export-summary"><FileText/><div><h3>{report.title}</h3><p>{report.count} matching {report.count===1?'record':'records'}</p></div></div><ul className="report-scope">{report.scope.map((s,i)=><li key={i}>{s}</li>)}</ul><p>{report.sections.map(s=>s.title).join(' · ')}</p><Alert title="Synthetic preview export">The PDF contains the visible permitted example records and filters. It does not access production data or include medication details, safe codes or private tracker movements.</Alert>{error&&<p role="alert" className="form-error">{error}</p>}{done&&<p role="status">PDF prepared. Your browser has received the download.</p>}</Modal>;
}
