import React, {useState} from 'react';
import {ArrowRight, AlertTriangle, CheckCircle2, ChevronDown, Info, Search, Shield, UserRound, X, Truck, CircleHelp} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Popover, PopoverTrigger, PopoverContent} from '@/components/ui/popover';
import {Command, CommandInput, CommandList, CommandEmpty, CommandGroup, CommandItem} from '@/components/ui/command';
import {Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription} from '@/components/ui/dialog';
import {StatusBadge} from '@/components/ui/status-badge';
export {Button, Input, StatusBadge};
export type Option={id:string;name:string;detail:string;unavailable?:string};
export function Picker({label,value,onChange,options,optional=false,disabled=false,mode='normal'}:{label:string;value:string;onChange:(v:string)=>void;options:Option[];optional?:boolean;disabled?:boolean;mode?:string}){
 const [open,setOpen]=useState(false);const [recovered,setRecovered]=useState(false);const selected=options.find(o=>o.id===value);
 return <div><label className="field-label">{label}</label><Popover open={open} onOpenChange={setOpen}><PopoverTrigger asChild><Button role="combobox" aria-label={label} aria-expanded={open} variant="outline" className="select-trigger" disabled={disabled}><span>{selected?.name||'Choose '+label.toLowerCase()}<small>{selected?.detail||'Search permitted records'}</small></span><ChevronDown className="size-4"/></Button></PopoverTrigger><PopoverContent align="start" className="w-[380px] max-w-[85vw] p-0" onEscapeKeyDown={e=>e.stopPropagation()}><Command><CommandInput placeholder={'Search '+label.toLowerCase()+'…'}/><CommandList>{mode==='loading'&&!recovered?<div className="p-4"><p role="status" className="muted">Loading permitted results…</p><Button variant="outline" size="sm" onClick={()=>setRecovered(true)}>Finish simulated load</Button></div>:mode==='error'&&!recovered?<div className="p-4"><p role="alert" className="form-error">Results could not load. Your selection is retained.</p><Button variant="outline" size="sm" onClick={()=>setRecovered(true)}>Retry search</Button></div>:<><CommandEmpty>No matching permitted records. Try a name or reference.</CommandEmpty><CommandGroup>{options.map(o=><CommandItem key={o.id} value={o.name+' '+o.detail} disabled={!!o.unavailable} onSelect={()=>{onChange(o.id);setOpen(false)}}><div className="py-2"><strong className="text-[13px]">{o.name}</strong><p className="text-[11px] text-muted-foreground">{o.detail}</p>{o.unavailable&&<p className="text-[11px] text-status-critical">{o.unavailable}</p>}</div></CommandItem>)}</CommandGroup></>}</CommandList></Command>{optional&&value&&<Button variant="ghost" className="m-2" onClick={()=>{onChange('');setOpen(false)}}>Clear selection</Button>}</PopoverContent></Popover></div>;
}
export function Alert({title,children,tone='info'}:{title:string;children?:React.ReactNode;tone?:string}){const Icon=tone==='success'?CheckCircle2:tone==='info'?Info:AlertTriangle;return <div className={'alert-box '+tone} role={tone==='critical'?'alert':'status'}><Icon/><div><strong>{title}</strong>{children}</div></div>}
export function Card({title,icon:Icon,children,action,className=''}:{title?:string;icon?:any;children:React.ReactNode;action?:React.ReactNode;className?:string}){return <section className={'card-body '+className}>{title&&<div className="card-title"><h2>{Icon&&<Icon/>}{title}</h2>{action}</div>}{children}</section>}
export function Fact({label,children}:{label:string;children:React.ReactNode}){return <div className="fact"><dt>{label}</dt><dd>{children}</dd></div>}
export function LinkButton({children,onClick}:{children:React.ReactNode;onClick:()=>void}){return <button className="text-link" onClick={onClick}>{children}<ArrowRight/></button>}
export function Tick({label,hint,checked,onChange}:{label:string;hint?:string;checked:boolean;onChange:(v:boolean)=>void}){return <label className="checkbox-row"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/><span>{label}{hint&&<small>{hint}</small>}</span></label>}
export function Modal({open,onClose,title,description,children,footer}:{open:boolean;onClose:()=>void;title:string;description?:string;children:React.ReactNode;footer?:React.ReactNode}){return <Dialog open={open} onOpenChange={v=>!v&&onClose()}><DialogContent className="max-h-[88vh] overflow-y-auto sm:max-w-[680px]"><DialogHeader><DialogTitle>{title}</DialogTitle><DialogDescription>{description||'Synthetic desktop preview · no operational records are changed.'}</DialogDescription></DialogHeader><div className="form-stack py-3">{children}</div>{footer&&<div className="flex justify-end gap-2 border-t pt-4">{footer}</div>}</DialogContent></Dialog>}
export const people:Option[]=[{id:'nia',name:'Nia Patel',detail:'Driver · Aurora House · HR eligibility recorded for this example'},{id:'eli',name:'Eli Thompson',detail:'Driver · Kōwhai House',unavailable:'Eligibility needs assessment for this period'},{id:'sara',name:'Sara Wilson',detail:'Support worker · Aurora House · escort availability confirmed'},{id:'ben',name:'Ben Carter',detail:'Incoming worker · Aurora House'},{id:'mia',name:'Mia Chen',detail:'Site coordinator · Aurora House'}];
export const sites:Option[]=[{id:'aurora',name:'Aurora House',detail:'Approved site · North Auckland'},{id:'kowhai',name:'Kōwhai House',detail:'Approved site · West Auckland'}];
export const vehicles:Option[]=[{id:'14',name:'Koru · Toyota Hiace',detail:'OFV-014 · KRU482 · Aurora House · wheelchair position'},{id:'22',name:'Tui · Ford Transit',detail:'OFV-022 · TUI226 · Kōwhai House',unavailable:'Unavailable · active Maintenance restriction'},{id:'31',name:'Rimu · Toyota Corolla',detail:'OFV-031 · RMU319 · Aurora House',unavailable:'Not suitable · no wheelchair position'}];
export const clients:Option[]=[{id:'alex',name:'Alex Morgan',detail:'Client · Aurora House · permitted transport context'},{id:'jordan',name:'Jordan Lee',detail:'Client · Kōwhai House · permitted transport context'}];
export const nameFor=(options:Option[],id:string)=>options.find(o=>o.id===id)?.name||'Not assigned';
