<?php

namespace App\Models;

use App\Services\Medication\Audit\MedicationEventFingerprint;
use Illuminate\Database\Eloquent\Model;
use LogicException;

class MedicationEvent extends Model
{
    public $timestamps = false;

    protected $dateFormat = 'Y-m-d H:i:s.u';

    protected $guarded = [];

    protected function casts(): array
    {
        return ['facts' => 'array', 'controlled' => 'boolean', 'occurred_at' => 'immutable_datetime', 'recorded_at' => 'immutable_datetime', 'sequence' => 'integer', 'site_id' => 'integer', 'client_id' => 'integer', 'actor_id' => 'integer', 'corrects_event_id' => 'integer'];
    }

    protected static function booted(): void
    {
        static::updating(fn () => throw new LogicException('Medication events are append-only. Append a correction.'));
        static::deleting(fn () => throw new LogicException('Medication events are retained clinical evidence.'));
    }

    public function client(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(Client::class);
    }

    public function actor(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(User::class, 'actor_id');
    }

    /** All fingerprinted fields; IDs are generated by the database and not fingerprinted. */
    public function fingerprintPayload(): array
    {
        return [
            'site_id' => (int) $this->site_id, 'sequence' => (int) $this->sequence,
            'client_id' => $this->client_id, 'actor_id' => $this->actor_id,
            'kind' => $this->kind, 'subject_type' => $this->subject_type, 'subject_id' => $this->subject_id,
            'occurred_at' => $this->occurred_at->utc()->format('Y-m-d\TH:i:s.u\Z'),
            'recorded_at' => $this->recorded_at->utc()->format('Y-m-d\TH:i:s.u\Z'),
            'summary' => $this->summary, 'facts' => $this->facts, 'controlled' => (bool) $this->controlled,
            'corrects_event_id' => $this->corrects_event_id, 'previous_hash' => $this->previous_hash,
        ];
    }

    public function hasValidFingerprint(): bool
    {
        return hash_equals($this->hash, MedicationEventFingerprint::of($this->fingerprintPayload()));
    }
}
