#!/usr/bin/env python3
"""Apply twelve project-specific Pass-3 catalogue adjudications."""

from __future__ import annotations

import csv
import hashlib
import json
from pathlib import Path


AUDIT = Path(__file__).resolve().parent.parent
REGISTER = AUDIT / "06-open-source-benchmark-register.csv"
OUTPUT = AUDIT / "evidence" / "source" / "project-specific-triage-wave-2026-08-14.json"
COMMIT = "081ef198f9f992f224e8c0c9fba33df33dde40be"
INPUT_SHA = "a12f0d9079212c7509a9cbb820344ee4300d773a6b0dcf6f88af72522b91a01f"
OUTPUT_SHA = "a37144efb4d8c85669ccbd4ce6a450a1e5bc20f480f66bd08d64b3198f19f29f"


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def require(condition: bool, message: str) -> None:
    if not condition:
        raise RuntimeError(message)


def entry(project: str, category: str, url: str, ref: str, commit: str, activity: str,
          licence: str, edition: str, behavior: str, loci: list[str], features: str,
          strengths: str, limitations: str, outcome: str, neutral: str, caveat: str,
          reason: str) -> dict[str, str]:
    return {
        "category": category, "project": project, "canonical_url": url,
        "inspected_ref": ref, "commit_sha": commit, "inspected_date": "2026-08-14",
        "release_activity_signal": activity, "root_licence": licence,
        "edition_boundary": edition,
        "exact_behaviour_screen_workflow_inspected": behavior + " Exact official loci: " + " | ".join(loci),
        "related_feature_ids": features, "strengths": strengths, "limitations": limitations,
        "benchmark_outcome": outcome, "neutral_requirements_extracted": neutral,
        "security_or_operational_caveat": caveat, "reason_selected_or_excluded": reason,
        "observer_agent": "project_triage_wave", "neutral_writer_agent": "root",
        "native_comparator_agent": "p8_adversarial",
    }


ROWS = [
    entry("horilla/horilla-hr", "HR, workforce, rostering, attendance, and time", "https://github.com/horilla/horilla-hr", "2.0", "53e65898c65cd3c4ff0418f81e9f0fb55e1045dc", "commit=2026-08-11T07:06:40Z; pushed=2026-08-13T13:41:10Z; archived=false; README identifies 2.0 as stable", "LGPL-2.1-only", "Pinned repository is LGPL-2.1. Professional support is a service, not a separately credited code edition.", "Manager-authorized leave approval prevents self-approval, checks available plus carry-forward balance, persists approved allocations, and rejection restores consumed balances.", ["leave/views.py:L997-L1080", "leave/views.py:L1245-L1280", "README.md:L10-L42,L175-L184"], "CAP-HR-LEAVE-REQUEST-DECISION | CAP-HR-LEAVE-BALANCES | CAP-HR-MY-HR-LEAVE", "Explicit maker/checker boundary, balance consequence, and approval/rejection states.", "Does not establish supported-living staffing continuity, competencies, fatigue, client-worker exclusions, or NZ employment assurance.", "Native benchmark", "Separate requester from approver; validate balance before approval; persist allocation effects; restore governed effects on rejection; expose state and reason.", "Cited view code does not prove transaction locking, concurrency safety, Site scope, or payroll correctness.", "Selected for the HR leave family because current community source proves decision and balance consequences."),
    entry("orangehrm/orangehrm", "HR, workforce, rostering, attendance, and time", "https://github.com/orangehrm/orangehrm", "main", "56e23b3b09e7af29317a0943523b825843fff527", "commit=2026-06-28T23:42:20Z; pushed=2026-06-28T23:52:36Z; archived=false; release 5.8.1=2026-04-06", "GPL-3.0-or-later", "OrangeHRM Starter repository only; commercial/hosted editions receive no credit.", "Attendance editing checks actor workflow permission, retains local and UTC punch times plus timezone provenance, and rejects overlap.", ["src/plugins/orangehrmAttendancePlugin/Api/AttendanceRecordAPI.php:L188-L224,L263-L347", "README.md:L5-L25,L58-L61"], "CAP-HR-TIME-TRACKING-CLOCKING | CAP-OPS-ATTENDANCE-CLOCK-SESSION", "Actor-sensitive editing, timezone provenance, and overlap validation.", "Not roster authority, EVV, payroll correctness, shift/site/client binding, or break compliance.", "Native benchmark", "Keep local/UTC punch evidence and timezone; enforce actor-specific edit rights; reject overlap before persistence; show validation feedback.", "Admin allowances must not replace Site/ownership rules; locus does not prove concurrency locking.", "Selected for unproved clock-session targets because exact Starter code verifies attendance integrity."),
    entry("lennystepn-hue/schichtplaner", "HR, workforce, rostering, attendance, and time", "https://github.com/lennystepn-hue/schichtplaner", "master", "91a91bbfb33ff6ad2aee0832cca3a38643f1c1f2", "commit=2026-03-02T16:21:17Z; pushed=2026-03-02T16:22:27Z; archived=false", "MIT", "Pinned MIT repository only; no separate enterprise source tree evidenced.", "Employee submits or cancels a shift wish; manager accepts or declines an OPEN request; acceptance refreshes schedule and books the employee.", ["src/components/schedule/wish-plan.tsx:L37-L122,L302-L352", "README.md:L23-L54,L337-L339"], "CAP-OPS-STAFF-AVAILABILITY | CAP-OPS-SHIFT-STAFFING-COVER | CAP-OPS-ROSTERING-PLANNING", "Clear employee-request and manager-decision states with visible success/error feedback.", "No proof of competency, credential expiry, exclusions, fatigue, lone work, sleepover, travel, continuity, or fairness.", "Native benchmark", "Represent preference as OPEN; allow withdrawal; require authorized accept/decline; refresh staffing state; explain failed decisions.", "Frontend requests do not prove server authorization, allocation locking, or audit provenance.", "Selected narrowly for preference-to-decision interaction, not complete supported-living rostering."),
    entry("openmrs/openmrs-core", "Client/patient profiles, clinical records, and identity", "https://github.com/openmrs/openmrs-core", "master", "6c1b124b30b5df1df6d1939fd629cea1ea002a4e", "commit=2026-08-13T21:36:10Z; pushed=2026-08-13T21:38:33Z; archived=false", "MPL-2.0", "Core MPL-2.0 plus Healthcare Disclaimer; optional modules are separate and no module behavior is inferred.", "Authorized duplicate lookup and merge move encounters, visits, identifiers, relationships and observations to preferred identity, void nonpreferred record, require merge audit, and fail on unsafe orders.", ["api/src/main/java/org/openmrs/api/PatientService.java:L532-L609", "README.md:L247-L253,L328-L330"], "OPS-CLIENT | CAP-OPS-CLIENT-RECORD-LIFECYCLE | CAP-OPS-CLIENT-ONBOARDING-WORKFLOW", "Explicit surviving identity, broad relation migration, audit expectations, and unsafe-order guard.", "API contract is not supported-person onboarding UX, Site authorization, NZ NHI integration, consent, or reversible adjudication proof.", "Native benchmark", "Detect duplicate candidates; require privileged adjudication; choose survivor; migrate owned relations without duplicates; retain merge log; block unsafe outstanding records.", "Oblivion requires preview, dual authorization, direct-object concealment, rollback evidence, Site checks and privacy controls.", "Selected for client-record lifecycle because exact core API proves identity consolidation."),
    entry("openmrs/openmrs-esm-task-list", "Client/patient profiles, care tasks, and clinical worklists", "https://github.com/openmrs/openmrs-esm-task-list", "main", "f22e24d0cf933b3e2268844e4aa68364c3d2d475", "commit=2026-05-11T23:28:35Z; pushed=2026-05-13T10:53:18Z; archived=true since 2026-05-14", "MPL-2.0", "Archived frontend requiring a separate Tasks backend; no hosted or enterprise behavior inferred.", "Patient-scoped tasks sort incomplete before completed, retain assignee/due/priority, toggle completed/in-progress, cancel, mark overdue, and report update failure.", ["src/workspace/task-list.resource.ts:L97-L180,L238-L323", "src/workspace/task-list-view.component.tsx:L15-L154", "package.json:L1-L8"], "CAP-DAY-ALL-TASKS-WORKBENCH | CAP-CR-MY-TASKS", "Patient context, due/priority/assignee, completion toggle, and recoverable error state.", "Archived split frontend/backend; no cross-provider aggregate, Site scope, notification or escalation proof.", "Reject", "No feature credit; native design may independently retain person context, completion, overdue visibility and recoverable feedback.", "Archived upstream and split contract make it unsuitable as current production benchmark owner.", "Substantively rejected; exact behavior is retained as exclusion evidence but grants no matrix credit."),
    entry("medic/cht-core", "Client/patient profiles, community care, offline tasks, and forms", "https://github.com/medic/cht-core", "master", "1d7a4827b0f681b42fa67f1eebaa77e7b89349bc", "commit=2026-08-13T04:54:29Z; pushed=2026-08-13T22:35:38Z; archived=false", "AGPL-3.0-only", "CHT Core AGPL-3.0; configuration and cht-conf are separate; hosting/support is a service.", "Task engine derives Draft/Ready/Completed/Failed/Cancelled with timestamped history and terminal states; mobile action hydrates person context, renders/saves form, reports failure and returns to task list.", ["shared-libs/rules-engine/src/task-states.js:L28-L155", "webapp/src/ts/modules/tasks/tasks-content.component.ts:L152-L206,L259-L369", "README.md:L9-L35,L55-L57"], "CAP-DAY-ALL-TASKS-WORKBENCH | CAP-OPS-MY-DAY-SHIFT-TASK-COMPLETION | CAP-RESP-TASK-EXECUTION", "Offline-oriented due-state calculation, durable history, person-context execution and recovery.", "Does not prove Oblivion shift/site/role ownership, medication authority, respite approval or cross-provider aggregation.", "Native benchmark", "Compute due state; persist timestamped transitions; carry person context; distinguish terminal states; expose retryable save errors.", "Offline sync can cause stale/replayed work; Oblivion needs versioning, Site access and idempotent completion.", "Selected for frontline task execution and offline/recovery behavior."),
    entry("glpi-project/glpi", "Assets/sites/facilities and Ticketing/ITSM/PSA", "https://github.com/glpi-project/glpi", "11.0/bugfixes", "9d56231da7e0dc8cfc1a8a6844bf52e839cbf1be", "commit/pushed=2026-08-13T14:29:27Z; archived=false", "GPL-3.0-only", "Core GPL-3.0; Network/cloud and marketplace plugins excluded.", "Ticket visibility distinguishes requester/observer, assigned actor and validator rights; loads linked hardware; solution/closure propagates through configured duplicate links.", ["src/Ticket.php:L305-L425,L897-L918,L1451-L1467", "README.md:L10-L54"], "CAP-IT-SUPPORT-TICKET", "Role-aware visibility, asset context, and linked-ticket completion.", "ITIL semantics do not prove healthcare support ownership, Site concealment, mailbox intake, SLA correctness or provisioning completion.", "Native benchmark", "Separate requester, observer, assignee and validator; show equipment context; constrain transitions; make related completion explicit/auditable.", "GLPI entities/profiles are not Oblivion Sites; linked automatic status changes need transactional preflight.", "Selected as exact-source comparator for IT support ticket."),
    entry("Grashjs/cmms", "Asset, equipment, CMMS, inventory, site, room, and facility profiles", "https://github.com/Grashjs/cmms", "main", "49ca1ecbcadbe1128187068b43f4bcff1f09193f", "commit=2026-08-13T18:42:50Z; pushed=2026-08-13T18:50:19Z; archived=false; v1.7.0=2026-06-23", "AGPL-3.0-only", "Public repository AGPL-3.0; designated advanced/branding features require commercial key and are excluded.", "Work order retains state, completer/time, signature, request and preventive origin, calculates due compliance, gates access by permission/creator/assignment and validates status change.", ["api/src/main/java/com/grash/model/WorkOrder.java:L40-L140", "api/src/main/java/com/grash/controller/WorkOrderController.java:L145-L157", "README.MD:L36-L45,L195-L201", "COMMERCIAL_LICENSE.MD:L13-L34"], "FLEET-WORK-ORDER | FLEET-SERVICE-SCHEDULE | ASSET-ASSET-MAINTENANCE", "Completion provenance, preventive/reactive origin, access boundary and due compliance.", "Does not prove clinical-equipment criticality, Site privacy, roadworthiness, parts segregation or supported-living escalation.", "Native benchmark", "Bind work to asset/source; capture state/completer/time/evidence; enforce creator/assignee/permission scope; report due compliance.", "Role check is not canonical Site ownership; paid behavior remains excluded.", "Selected because exact public code proves a maintenance work-order lifecycle."),
    entry("fleetbase/fleetops", "Fleet, vehicles, driver operations, and vehicle lifecycle", "https://github.com/fleetbase/fleetops", "main", "fa37e7899b78e3cbe2f839e818561ae4c40189c2", "commit=2026-08-07T12:09:14Z; pushed=2026-08-12T20:48:10Z; archived=false", "AGPL-3.0-or-later", "Public engine/API AGPL-3.0-or-later; commercial licensing/support does not add credited behavior.", "Maintenance has scheduled/in-progress/completed/cancelled/on-hold and priority; schedules support time/distance/engine-hours; driver schedules materialize recurring shifts and pending/approved/rejected time off.", ["addon/components/maintenance/form.js:L46-L69", "addon/components/maintenance-schedule/form.js:L58-L80,L182-L198", "addon/components/driver/schedule.js:L171-L213,L237-L295,L368-L428", "README.md:L239-L241"], "CAP-FLEET-DRIVER-DIRECTORY | CAP-FLEET-VEHICLE-REGISTER | FLEET-SERVICE-SCHEDULE | FLEET-WORK-ORDER", "Multiple maintenance triggers, explicit states, recurring shifts and decision-state exceptions.", "Does not prove supported-person custody, medication transport, competency, compliance, fatigue law or Site access.", "Native benchmark", "Support time/odometer/engine-hour rules; show next due; separate recurring template/materialized shift; represent time off pending then decided; expose maintenance state/priority.", "Frontend paths do not prove backend authorization or concurrency; hours-of-service loading is best-effort.", "Selected narrowly for maintenance and driver scheduling."),
    entry("MeyerThorsten/QAtrial", "Health and safety, incidents, hazards, risks, evidence, and corrective action", "https://github.com/MeyerThorsten/QAtrial", "main", "b10fab722caf9561bcf4fdb03cc9733156992635", "commit/pushed=2026-04-17T11:57Z; archived=false", "AGPL-3.0-only", "Pinned AGPL-3.0 repository; standalone/server are modes of the same codebase.", "CAPA validates transitions, retains cause/corrective/preventive/effectiveness, logs change and emits resolution cascade; deviations progress detected through closed with actor/time.", ["server/routes/capa.ts:L137-L185", "server/routes/deviations.ts:L154-L197,L224-L344", "README.md:L223-L239,L576-L580"], "CAP-HS-CORRECTIVE-ACTION-DELIVERY-CLOSURE | CAP-HS-CORRECTIVE-ACTION-VERIFICATION-REWORK | CAP-HS-INVESTIGATION-CONDUCT-SUBMIT", "Closed-loop deviation/CAPA states, effectiveness, transition validation and consequences.", "Young project; compliance claims are not certification, immutable-audit assurance, NZ WorkSafe compliance or maturity proof.", "Native benchmark", "Use governed states; link deviation/action; capture cause, corrective/preventive action and effectiveness; record actor/time; validate transitions.", "Do not treat README compliance claims as assurance; immutability, authorization and transactions need proof.", "Selected for exact lifecycle behavior with explicit maturity limitation."),
    entry("zabbix/zabbix", "IoT, telemetry, physical security, and IT monitoring", "https://github.com/zabbix/zabbix", "master", "22cb74d2d3d649543c0f18a93422b12700465f16", "commit=2026-08-12T14:33:31Z; pushed=2026-08-12T15:00:48Z; archived=false", "AGPL-3.0-only", "Core AGPL-3.0; commercial support/services are not credited behavior.", "Problem update separately authorizes acknowledge, close, severity, comment, suppression and cause/symptom rank and groups allowed effects; maintenance requires authorized active window, recurrence and host/group scope.", ["ui/app/controllers/CControllerPopupAcknowledgeCreate.php:L86-L268,L353-L552", "ui/app/controllers/CControllerMaintenanceCreate.php:L30-L152", "README.md:L23-L25"], "SEC-ALERTS-EVENTS | CAP-CR-ALERT-TRIAGE | CAP-CR-ALERT-RESPONSE-CLOSURE | CAP-CR-CONTROL-ROOM-SETTINGS-MAINTENANCE-WINDOWS", "Fine-grained action authority, grouping, acknowledgement/suppression/recovery and scoped maintenance.", "Infrastructure monitoring does not prove human-safety confirmation, consent/custody, clinical escalation or incident ownership.", "Native benchmark", "Authorize each action independently; preflight multi-event effects; preserve provenance; bound maintenance scope/time; distinguish cause/symptom.", "Machine acknowledgement must never equal confirmation of person safety; mixed-Site bulk work must fail before write.", "Selected for alert triage and maintenance while excluding clinical assurance."),
    entry("formbricks/formbricks", "Cross-cutting forms, surveys, and feedback", "https://github.com/formbricks/formbricks", "main", "b344ddd73cfb0f7af86573176d53534a5321d982", "commit=2026-08-13T18:33:38Z; pushed=2026-08-13T18:46:51Z; archived=false; v5.2.2=2026-07-29", "AGPL-3.0-only", "AGPL core excludes proprietary /apps/web/modules/ee; all cited paths are outside it.", "Core response creation validates workspace/display/survey/contact ownership, records partial/final and completion time; update refuses closed/final responses, validates merged data, conceals cross-workspace IDs and emits response-finished; survey has explicit lifecycle.", ["apps/web/app/api/v2/client/[workspaceId]/responses/lib/response.ts:L23-L87", "apps/web/app/api/v1/client/[workspaceId]/responses/[responseId]/lib/put-response-handler.ts:L96-L265", "apps/web/app/(app)/workspaces/[workspaceId]/surveys/[surveyId]/components/SurveyStatusDropdown.tsx:L24-L119", "README.md:L208-L224"], "CAP-OPS-CUSTOM-FORM-DEFINITION | CAP-OPS-CUSTOM-FORM-SUBMISSION | CAP-HR-FEEDBACK-BULK-SUMMARY | CAP-HR-FEEDBACK-REQUEST-RESPONSE", "Partial/final boundary, ownership checks, closed/final immutability, lifecycle and finish event.", "Experience surveys are not clinical forms, HR confidentiality, consent authority, statutory evidence, offline care or reviewer approval.", "Native benchmark", "Separate partial/final; prevent post-final edits; close intake; validate ownership; preserve timing/language/metadata; emit completion once; archive read-only.", "Exclude /apps/web/modules/ee; responses require Oblivion Site/privacy/direct-object concealment.", "Selected for custom-form and feedback lifecycles from exact AGPL-core paths."),
]


require(sha(REGISTER) in {INPUT_SHA, OUTPUT_SHA}, "Benchmark register input SHA drift")
with REGISTER.open("r", encoding="utf-8-sig", newline="") as handle:
    reader = csv.DictReader(handle)
    fields = list(reader.fieldnames or [])
    current = list(reader)
require(len(current) == 98 and len({row["project"] for row in current}) == 98, "Register identity drift")
replacement = {row["project"]: row for row in ROWS}
require(len(replacement) == 12 and set(replacement) <= {row["project"] for row in current}, "Replacement key drift")
updated = [{field: replacement.get(row["project"], row).get(field, "") for field in fields} for row in current]

tmp = REGISTER.with_suffix(".csv.tmp")
with tmp.open("w", encoding="utf-8", newline="") as handle:
    writer = csv.DictWriter(handle, fieldnames=fields, lineterminator="\n")
    writer.writeheader(); writer.writerows(updated)
tmp.replace(REGISTER)

identity_lines = sorted(f"{row['project']}@{row['commit_sha']}" for row in ROWS)
identity_sha = hashlib.sha256(("pass3-project-triage-wave-2026-08-14-12|" + COMMIT + "|" + "\n".join(identity_lines)).encode()).hexdigest()
artifact = {
    "schema_version": "1.0.0", "artifact": "project-specific-triage-wave-2026-08-14",
    "audited_commit": COMMIT, "read_only": True, "input_register_sha256": INPUT_SHA,
    "output_register_sha256": sha(REGISTER), "row_count": 12,
    "gate_projection": {"before": 36, "after": 48, "denominator": 97, "percent": 49.48},
    "identity_sha256": identity_sha, "rows": ROWS,
    "claim_limit": "Project-specific source triage only. It does not grant target-level matrix credit except through separate target-specific adjudication.",
}
OUTPUT.write_text(json.dumps(artifact, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print(json.dumps({"register_sha256": sha(REGISTER), "artifact_sha256": sha(OUTPUT), "replaced": 12}, indent=2))
