<?php

use App\Domain\Finance\Models\FinBill;
use App\Domain\Finance\Models\FinPurchaseOrder;

/**
 * Bill + PO numbers were generated by two divergent hand-rolled methods
 * (AccountsPayableService vs PurchaseOrderController) using a string orderBy that
 * broke past 999/month. Consolidated into FinBill::nextNumber / FinPurchaseOrder::
 * nextNumber (MAX of the numeric suffix) so both creation paths share one robust
 * generator.
 */
it('FinBill::nextNumber increments per org/month and handles >999', function () {
    $month = now()->format('Ym');

    expect(FinBill::nextNumber(1))->toBe("BILL-{$month}-001");

    FinBill::factory()->create(['organization_id' => 1, 'bill_number' => "BILL-{$month}-999"]);

    // The old string orderBy returned '999' as "latest" forever → collisions.
    expect(FinBill::nextNumber(1))->toBe("BILL-{$month}-1000");
});

it('FinPurchaseOrder::nextNumber increments per org/month', function () {
    $month = now()->format('Ym');

    expect(FinPurchaseOrder::nextNumber(1))->toBe("PO-{$month}-001");

    FinPurchaseOrder::factory()->create(['organization_id' => 1, 'po_number' => "PO-{$month}-005"]);

    expect(FinPurchaseOrder::nextNumber(1))->toBe("PO-{$month}-006");
});

it('scopes numbering per organisation', function () {
    $month = now()->format('Ym');
    FinBill::factory()->create(['organization_id' => 1, 'bill_number' => "BILL-{$month}-007"]);

    // A different org starts its own sequence.
    expect(FinBill::nextNumber(2))->toBe("BILL-{$month}-001");
});
